<?php

$host = OpenContext_OCConfig::get_host_config();
$atom = $this->xml_string;

$doc = new DOMDocument();
$doc->substituteEntities = TRUE;
    
$useragent = @$_SERVER['HTTP_USER_AGENT'];
/*
    if(strstr($useragent,"MSIE")){
        $doc->load("xsl/defaultProject_rdfa_ie.xsl");
    }    
    else{
        $doc->load("xsl/defaultProject_rdfa.xsl");
    }
*/ 
$doc->load("xsl/rev2-project.xsl");

$proc = new XSLTProcessor();
$xslt = $proc->importStylesheet($doc);
$atomDoc = new DomDocument();
$atomDoc->loadXML($atom);


$XHTMLbody = $proc->transformToXML($atomDoc);

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    
    <title>Open Context view of all Projects</title>
    
    <link rel="shortcut icon" href="/images/layout/oc-favicon.ico" type="image/x-icon" />
    <link rel="alternate" type="application/atom+xml" tilte="Atom feed of all projects" href="<?php echo $host; ?>/projects.atom" />
    <link href="<?php echo $host; ?>/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $host; ?>/css/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $host; ?>/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $host; ?>/css/project-rev2.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $host; ?>/css/bibliographic.css" rel="stylesheet" type="text/css" />
    <!--
    <link href="<?php echo $host; ?>/css/default_project.css" rel="stylesheet" type="text/css" />
    -->
    
    <script src="<?php echo $host; ?>/js/jquery/jquery-1.7.2.min.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-transition.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-carousel.js" type="text/javascript"></script>
    <script type="text/javascript">
        <!--
        
                
        -->
    </script>
    
    
    </head>
    <body>
        <!-- 
            Logo,
        -->    
        <?php echo $this->render('header.phtml'); //reader document top ?>
           
        <!-- 
            Navigation tabs, search box
        -->
        <?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>
    
        <?php echo $XHTMLbody; ?>
        
        <div id="bottomBuffer">
        </div>
        </div>
        <?php echo $this->render('footer.phtml'); //reader document footer ?>
    </body>
</html>