<?php


$requestURI = $this->requestURI;
$requestParams = $this->requestParams;
$request_array = explode('?', $requestURI, 2);
$host = OpenContext_OCConfig::get_host_config();
define ('HOST', $host);

$request_array[0] = str_replace(".kml", "", $request_array[0]);
$request_array[0] = str_replace("/facets", "", $request_array[0]);

if(count($request_array)>1){
   $request_array[1] = "?".$request_array[1];
}

//$filter_output = OpenContext_FacetOutput::facet_removal_context_links($requestParams, $request_array, $host);
$filter_output = OpenContext_FacetOutput::facet_removal_links($requestParams, $request_array, $host);

//echo var_dump($request_array);

if(strlen($filter_output)<4){
   $filter_output = "<br/><em>The selection is not filtered</em><br/>";
}
else{
   $filter_output = "<br/><strong>Filtered by:</strong><br/>".$filter_output;
}


$default_context_path = $this->DefaultContextPath;







$atomXML = $this->atomXML;
//echo var_dump($atomXML);

$title = $this->title;
//echo var_dump($title)."<br/><br/>";

$contextCount = $this->contextCount;
$contextURIs = $this->contextURIs;    
$contextNames =	$this->contextNames;
$contextLats = $this->contextLats;
$contextLons = $this->contextLons;
$contextBegin = $this->contextBegin;
$contextEnd = $this->contextEnd;
$contextFacCount = $this->contextFacCount;

$maxDistance = $this->maxDistance;

        
$contextColor = $this->contextColor;
$contextHeight = $this->contextHeight;
$contextPolygon = $this->contextPolygon;
$contextPoint = $this->contextPoint;

//echo "There are: ".$contextCount." context(s).<br/><br/>";
//echo "This max distance is: ".$maxDistance."<br/><br/>";

//echo var_dump($contextLons);

$kmlFullDoc = new DOMDocument("1.0", "utf-8");
	
$root = $kmlFullDoc->createElementNS("http://www.opengis.net/kml/2.2", "kml");
$kmlFullDoc->appendChild($root);
$kmlDocument = $kmlFullDoc->createElement("Document");
$root->appendChild($kmlDocument);

$i=0;
while($i<$contextCount){
   
   //create a new KML placemark
   $placemark = $kmlFullDoc->createElement("Placemark");
   
   //add a name for the placemark
   $placeName = $kmlFullDoc->createElement("name");
   $placeNameText = $kmlFullDoc->createTextNode($contextNames[$i]);
   $placeName->appendChild($placeNameText);
   $placemark->appendChild($placeName);
   
   //add a description to the placemark
   //$des_text =  "Context: ".$contextNames[$i];
   $des_text = " This context has <strong>".$contextFacCount[$i]."</strong> item(s) <br/>";
   //$des_text .= " found at: ".$contextLats[$i]." (lat) ".$contextLons[$i]." (lon)  <br/>";
   $des_text .= $filter_output;
   $des_text .= " Within this time range: ".$contextBegin[$i]." to ".$contextEnd[$i]."<br/>";
   //$des_text .= " poly: ".$contextPolygon[$i];
   //echo "<br/><br/><br/>";
   //$des_text = htmlspecialchars($des_text);
   $placeDes = $kmlFullDoc->createElement("description");
   //$placeDesText = $kmlFullDoc->createTextNode($des_text);
   $placeDesText = $kmlFullDoc->createCDATASection($des_text);
   $placeDes->appendChild($placeDesText);
   $placemark->appendChild($placeDes);
   
   //add color information to the placemark
   $place_style = $kmlFullDoc->createElement("Style");
   $polystyle = $kmlFullDoc->createElement("PolyStyle");
   $p_color = $kmlFullDoc->createElement("color");
   $p_color_text = $kmlFullDoc->createTextNode($contextColor[$i]);
   $p_color->appendChild($p_color_text);
   $polystyle->appendChild($p_color);
   $place_style->appendChild($polystyle);
   
   //add label style information
   $labelstyle = $kmlFullDoc->createElement("LabelStyle");
   $l_color = $kmlFullDoc->createElement("color");
   $l_color_text = $kmlFullDoc->createTextNode("ff0000c");
   $l_color->appendChild($l_color_text);
   $labelstyle->appendChild($l_color);
   $l_mode = $kmlFullDoc->createElement("colorMode");
   $l_mode_text = $kmlFullDoc->createTextNode("random");
   //$l_mode->appendChild($l_mode_text);
   $labelstyle->appendChild($l_mode);
   $l_scale = $kmlFullDoc->createElement("scale");
   $l_scale_text = $kmlFullDoc->createTextNode("1");
   $l_scale->appendChild($l_scale_text);
   $labelstyle->appendChild($l_scale);
   $place_style->appendChild($labelstyle);
   //$polystyle->appendChild($labelstyle);

   
   //add icon so polygon can be clicked
   $iconstyle = $kmlFullDoc->createElement("IconStyle");
   $icon_pict = $kmlFullDoc->createElement("Icon");
   $icon_plink = $kmlFullDoc->createElement("href");
   $icon_plink_text = $kmlFullDoc->createTextNode("http://maps.google.com/mapfiles/kml/paddle/purple-circle.png");
   $icon_plink->appendChild($icon_plink_text);
   $icon_pict->appendChild($icon_plink);
   $iconstyle->appendChild($icon_pict);
   $icon_scale = $kmlFullDoc->createElement("scale");
   $icon_scale_text = $kmlFullDoc->createTextNode(".6");
   $icon_scale->appendChild($icon_scale_text);
   $iconstyle->appendChild($icon_scale);
   $place_style->appendChild($iconstyle);
   
   $placemark->appendChild($place_style);
   
   
   
   //this is a container for points and polygons assocated with the placemark
   $multgeometry = $kmlFullDoc->createElement("MultiGeometry");
   
   //add a point to the placemark
   //$point_coords = $contextLons[$i].",".$contextLats[$i].",".$contextHeight[$i];
   $point = $kmlFullDoc->createElement("Point");
   $point_altmode = $kmlFullDoc->createElement("altitudeMode");
   $point_altmode_val = $kmlFullDoc->createTextNode("relativeToGround");
   $point_altmode->appendChild($point_altmode_val);
   $point->appendChild($point_altmode);
   $p_coords = $kmlFullDoc->createElement("coordinates");
   //$p_coords_text = $kmlFullDoc->createTextNode($point_coords);
   $p_coords_text = $kmlFullDoc->createTextNode($contextPoint[$i]);
   $p_coords->appendChild($p_coords_text);
   $point->appendChild($p_coords);
   $multgeometry->appendChild($point);
   
   //-----------------------------------
   //add a polygon to the placemark
   $polygon = $kmlFullDoc->createElement("Polygon");
   
   $poly_extrude = $kmlFullDoc->createElement("extrude");
   $poly_extrude_val = $kmlFullDoc->createTextNode("1");
   $poly_extrude->appendChild($poly_extrude_val);
   $polygon->appendChild($poly_extrude);

   $poly_altmode = $kmlFullDoc->createElement("altitudeMode");
   $poly_altmode_val = $kmlFullDoc->createTextNode("relativeToGround");
   $poly_altmode->appendChild($poly_altmode_val);
   $polygon->appendChild($poly_altmode);
   
   $poly_out = $kmlFullDoc->createElement("outerBoundaryIs");
   $poly_oring = $kmlFullDoc->createElement("LinearRing");
   $poly_coords = $kmlFullDoc->createElement("coordinates");
   $poly_coords_text = $kmlFullDoc->createTextNode($contextPolygon[$i]);
   $poly_coords->appendChild($poly_coords_text);
   $poly_oring->appendChild($poly_coords);
   $poly_out->appendChild($poly_oring);
   $polygon->appendChild($poly_out);   
   $multgeometry->appendChild($polygon);
   
   //add the placemark to the Document element
   $placemark->appendChild($multgeometry);
   
   
   //add time data
   $timespan = $kmlFullDoc->createElement("TimeSpan");
   $time_begin = $kmlFullDoc->createElement("begin");
   $time_begin_val = $kmlFullDoc->createTextNode($contextBegin[$i]);
   $time_begin->appendChild($time_begin_val);
   $timespan->appendChild($time_begin);
   $time_end = $kmlFullDoc->createElement("end");
   $time_end_val = $kmlFullDoc->createTextNode($contextEnd[$i]);
   $time_end->appendChild($time_end_val);
   $timespan->appendChild($time_end);
   $placemark->appendChild($timespan);
   
   //add placemark to whole document
   $kmlDocument->appendChild($placemark);
   
   
   $i++;
}//end loop through contexts

//header('Content-type: application/xml', true);
header('Content-type: application/vnd.google-earth.kml+xml; charset=UTF-8');

$kmlString = $kmlFullDoc->saveXML();

echo $kmlString;

?>
