<?php

// used to help create hyperlinks; set to current hostname.
//$host = "http://ishmael.ischool.berkeley.edu";
//$host = "http://opencontext";
$host = OpenContext_OCConfig::get_host_config();

define ('HOST', $host);


$unfold_vals = $this->unfold_vals;
$requestURI = $this->requestURI;
$requestParams = $this->requestParams;
$solrParams = $this->solrParams;
$extendfacets = $this->extendedFacets;
$unfold_vals = $this->unfold_vals;
$queryString = $this->queryString;
//echo $queryString." <br/><br/>";
//echo var_dump($requestParams);

//echo var_dump($solrParams);
//$solrqTerm = $solrParams["fq"];
//echo $solrqTerm ." <br/><br/>";


$request_array = explode('?', $requestURI, 2);
//array explode  ( string $delimiter  , string $string  [, int $limit  ] )
//echo var_dump($request_array);

if (substr_compare($request_array[0], '/' , -1)) {  // if the uri doesn't end in a slash (minus query parameters), 
    $request_array[0] = $request_array[0] . '/';  // add one
}


if (isset($request_array[1])) { // if there are query parameters,
    $request_array[1] = "?" . $request_array[1];  // prepend a '?' to the set of parameters since we exploded on the '?' to get this string. 
    //echo $request_array[1]; // for testing
} else {
    $request_array[1] = null;
}


$requestURI = str_replace("/lightbox","/lightbox/",$requestURI);
$requestURI = str_replace("/lightbox//","/lightbox/",$requestURI);


/* this complex check is needed because the request parameter 'module' with the value 'default' is present if the user selects a
 * non-context parameter.  The reason for this behavior is not clear.  
 */
if ((count($requestParams) < 3)  ||  ((count($requestParams) < 4) && (in_array('module', array_keys($requestParams))))) {

    $filter_message = "(View is not filtered)";
    
    $googleURI = str_replace("/lightbox","/lightbox/facets/.kml",$requestURI);
    $googleURI = str_replace("/lightbox/","/lightbox/facets/.kml",$requestURI);
    $facetAtomURI = str_replace("/lightbox","/lightbox/facets/.atom",$requestURI);
    $facetAtomURI = str_replace("/lightbox","/lightbox/facets/.atom",$requestURI);
    $resultAtomURI = $requestURI.".atom";
    $searchMessage = "Search Open Context";
}//end case with no filters
else{
    
    $filter_message = "";
    $searchMessage = "Search this Set";
    
    $requestURI = str_replace("[", "%5B",$requestURI);
    $requestURI = str_replace("]", "%5D",$requestURI);
    
    $googleURI = str_replace("?",".kml?",$requestURI);
    $googleURI = str_replace("/lightbox/","/lightbox/facets/",$googleURI);
    $facetAtomURI = str_replace("?",".atom?",$requestURI);
    $resultAtomURI = $facetAtomURI;
    $facetAtomURI = str_replace("/lightbox/","/lightbox/facets/",$facetAtomURI);
    $resultAtomURI = str_replace(".org.org", ".org", $resultAtomURI);
    
    if(substr_count($googleURI,".kml?")<1){
        $googleURI .= ".kml";
        $facetAtomURI .= ".atom";
        $resultAtomURI = $requestURI.".atom";
    }
    
    if(substr_count($googleURI,"facets/.kml")<1){
        $googleURI = str_replace("/.kml",".kml",$googleURI);
        $facetAtomURI = str_replace("/.atom",".atom",$facetAtomURI);
        $resultAtomURI = str_replace("/.atom",".atom",$resultAtomURI);
    }
}//end case with filter parameters

$resultAtomURI = $host.$resultAtomURI;
$facetAtomURI = $host.$facetAtomURI;

$resultAtomURI = str_replace("&", "&amp;", $resultAtomURI);
$resultAtomURI = str_replace("&amp;amp;", "&amp;", $resultAtomURI);
$facetAtomURI = str_replace("&", "&amp;", $facetAtomURI);
$facetAtomURI = str_replace("&amp;amp;", "&amp;", $facetAtomURI);
$googleURI = str_replace("&", "&amp;", $googleURI);
$googleURI = str_replace("&amp;amp;", "&amp;", $googleURI);

$openSearchURI = str_replace("lightbox/facets", "lightbox/search", $facetAtomURI);
$openSearchURI = str_replace(".atom", ".xml", $openSearchURI);
$openSearchURI = str_replace("search//", "search/", $openSearchURI);
$openSearchURI = str_replace(".xml/", ".xml", $openSearchURI);

$openSearchURI = $host."/lightbox/search/.xml";
                             
//echo $resultAtomURI."<br/>";
//$googleURI = str_replace("[", "%5B",$googleURI);
//$googleURI = str_replace("]", "%5D",$googleURI);
//$facetAtomURI = str_replace("[", "%5B",$facetAtomURI);
//$facetAtomURI = str_replace("]", "%5D",$facetAtomURI);
//$resultAtomURI = str_replace("[", "%5B",$resultAtomURI);
//$resultAtomURI = str_replace("]", "%5D",$resultAtomURI);

$numFound = $this->numFound;

$filter_output = $filter_message;


//$filter_output .= OpenContext_FacetOutput::facet_removal_context_links($requestParams, $request_array, $host);
//$filter_output .= OpenContext_FacetOutput::facet_removal_links($requestParams, $request_array, $host);
$filter_output = OpenContext_FacetOutput::make_filters_html($requestParams, $host);
$filter_output = str_replace("/sets/","/lightbox/", $filter_output);

// get the facet counts 
$facet_fields = $this->facet_fields;
$facet_queries = $this->facet_queries;
$extendedFacets = $this->extendedFacets; //show more available facets 

$facet_output = OpenContext_FacetOutput::facets_available($extendedFacets, $facet_fields, $facet_queries, $requestParams, $request_array, $host);
$facet_output = str_replace("/sets/", "/lightbox/", $facet_output);
//echo "<a href='".$resultAtomURI."'>".$resultAtomURI."</a>";

$all_result_output = OpenContext_ResultAtom::image_atom_to_html($resultAtomURI);
$firstPreviewURI = $all_result_output["pict1"];
$firstImageTitle = $all_result_output["title1"];
$result_output = $all_result_output["items"];
$result_output = str_replace("http://opencontext/",$host."/", $result_output);
//$result_output = "";


//add a full text form?
if(substr_count($requestURI,"q=")<1){
    $full_link = $host.$requestURI;
    $full_link  = str_replace("&", "&amp;", $full_link );
    $full_link  = str_replace("&amp;amp;", "&amp;", $full_link );

    $fulltext = '<p class="bodyText">Or, type a search term in the box below (works like Google):</p>'.chr(13);
    //$fulltext .= '<form id="searchbox" name="form4" method="get" action="'.$requestURI.'">'.chr(13);
    $fulltext .= '<input id="act_uri" type="hidden" value="'.$full_link.'" />';
    $fulltext .='<input name="q" type="text" id="q_string" size="30" maxlength="100" class="bodyText" alt="Enter full-text search term(s)" onchange="textSearch();" />'.chr(13);
    $fulltext .='<input type="submit" id="submit" value="'.$searchMessage.'" class="bodyText" alt="Run full-text search" onclick="textSearch();"/>'.chr(13);
    //$fulltext .='</form>';
}
else{
    $fulltext = "";
}



?>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
        <title><?php echo 'Open Context Image Lightbox: ('.$numFound.' Images Showing)'; ?></title> 
        <link rel="shortcut icon" href="/images/general/oc_favicon.ico" type="image/x-icon"/>
        <link href="<?php echo $host; ?>/components/css/lightbox" rel="stylesheet" type="text/css" />
        <link rel="alternate" type="application/atom+xml" title="Atom facet feed" href="<?php echo $facetAtomURI; ?>" />
        <link rel="search" type="application/opensearchdescription+xml" href="<?php echo $openSearchURI; ?>" title="Open Context Web Search" />
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
        <script src="<?php echo $host; ?>/components/js/lightbox" type="text/javascript"></script>
        <script type="text/javascript">
        <!--
            
            <?php
        
        echo "var baseURI = '".$host.$requestURI."'; \n";
        echo "var contextBase = '".$host.$request_array[0]."'; \n";
        echo "var paramterBase = '".$request_array[1]."'; \n";
        
        echo chr(13).chr(13);
        
        $activeTaxaValue = OpenContext_FacetOutput::active_taxon_value($requestParams);
        echo "var activeTaxaValue = '".$activeTaxaValue."'; \n";
        
        ?>
            
            
            function openList(listId){
                var displayControl = listId + "control";
                var displayStatus = document.getElementById(listId).style.display;
                if( displayStatus == "none"){
                    document.getElementById(listId).style.display = "";
                    document.getElementById(displayControl).innerHTML = "<em>(Hide list below)</em>";
                }
                else{
                    document.getElementById(listId).style.display = "none";
                    document.getElementById(displayControl).innerHTML = "More...";
                }
            }
            
            
        
        
        $(document).ready(function(){
				//Examples of how to assign the ColorBox event to elements.
				
				$("a[rel='colorbox_prev']").colorbox({transition:"elastic"});
				
			});
      
      -->
        </script>
    </head>
    <body>
        
    <div id="oc_logo">
	<a href="<?php echo $host;?>" title="Open Context (Home)"><img alt="Open Context Logo" src="http://static.alexandriaarchive.org/images/general/oc_logo.jpg" border="0" /></a>
    </div>
    <div id="oc_tagline">
	<img alt="Open Context Tagline" src="http://static.alexandriaarchive.org/images/general/oc_tagline.jpg" />
    </div>
    <div id="oc_beta">
	<img alt="Beta Stamp" src="http://static.alexandriaarchive.org/images/general/oc_betastamp.jpg" />
    </div>
    
    <div id="oc_top_search">
	<form method="get" action="<?php echo $host;?>/lightbox/" id="search-form">
	<div id="search_box">
	<input type='text' name='q' class='tinyText' value='Search Images' size='30' onfocus="if(this.value=='Search Images')this.value='';" onblur="if(this.value=='')this.value='Search Images';" />
	</div>
	<div id="search_cntrl">
	    <input class="oc_top_sbutton" type="submit" value="" />
	</div>
	</form>
    </div>
   
   
   <!-- 
    Navigation tabs
    -->    
    <?php echo OpenContext_NavMenus::GeneralNavMenu("lightbox"); ?> 
    
    
    
        
<!--
BEGIN Container for main page content
--> 
    <div id="main_page"> 
        <!--Begin code for showing available facets-->
        <div id="main_content">
            <div id="left_cont">
                <div id="filter_options" class="bodyText">
                    <p class="bodyText"><strong>Click on one of the links below to further limit your view of images in Open Context.</strong></p>
                        <?php echo  $fulltext; ?>
                    <br/>
                        <?php echo $facet_output; ?>
                            
                    <br/>
                    <p>View in <a href="<?php echo $googleURI; ?>">GoogleEarth</a></p>
                    <p>Get in <a href="<?php echo $facetAtomURI; ?>">Atom</a></p>
                </div>
            </div>
            <div id="right_cont">   
                <div id="selected_filters" class="rounded-corners" >
                    <p class="subHeader">Open Context currently has <strong><?php echo $numFound; ?></strong> images, filtered by the following criteria:</p>
                    <p class="bodyText"><?php echo $filter_output; ?></p>
                    <p class="tinyText" style="text-align:right;">Last Updated: <em><?php echo date("F j, Y, g:i a", strtotime(OpenContext_OCConfig::last_update("media"))); ?></em></p>
                    <!--
                    <form action="<?php echo $host."/tables/add"; ?>" method="post">
                        <input type="hidden" value="<?php echo $requestURI; ?>" name="set" />
                        <input type="hidden" value="<?php echo htmlentities($filter_output); ?>" name="filter" />
                        <input type="submit" value="make table" />
                    </form>
                    
                    <p class="bodyText"><a href='<?php echo $firstPreviewURI; ?>' rel='colorbox_prev' title='<?php echo $firstImageTitle; ?>'>Slideshow of Preview Size Images</a></p>
                    -->
                </div>
                        
                <br />
                <br />
                        
                <?php echo $result_output; ?>
            </div>
                    
   
        <!--
        END of div container for placing main page content
        -->
        <div id="bottom_cont"> 
          <br /> 
          <br /> 
        </div> 
        <!--
        END Code for showing the database-like content
        -->
   
     </div>
    <br />
    
        <div id="footer"> 
            <div id="w3c_val_logo"> 
              <a href="http://validator.w3.org/check?uri=referer"> 
                <img src="http://www.w3.org/Icons/valid-xhtml10-blue" alt="Valid XHTML 1.0 Transitional" height="31" width="88" /> 
              </a> 
            </div>     
        </div>
   
     </div>
    </body>
</html>    