<?php

function URIescape($uri){
    return str_replace("&", "&amp;", $uri);
}

// used to help create hyperlinks; set to current hostname.
$host = OpenContext_OCConfig::get_host_config();

define ('HOST', $host);

$auth = Zend_Auth::getInstance();
if (!$auth->hasIdentity()){
    $displayName = false;
}
else{
    $identity = $auth->getIdentity();
    $displayName = $identity->name;
}


$requestURI = $this->requestURI;
$request_array = explode('?', $requestURI, 2);
//array explode  ( string $delimiter  , string $string  [, int $limit  ] )

if (substr_compare($request_array[0], '/' , -1)) {  // if the uri doesn't end in a slash (minus query parameters), 
    $request_array[0] = $request_array[0] . '/';  // add one
}


if (isset($request_array[1])) { // if there are query parameters,
    $request_array[1] = "?" . $request_array[1];  // prepend a '?' to the set of parameters since we exploded on the '?' to get this string. 
    //echo $request_array[1]; // for testing
} else {
    $request_array[1] = null;
}


$requestParams = $this->requestParams;
if(!isset($requestParams["q"])){
    
    $checkParam = $requestParams;
    unset($checkParam["page"]);
    unset($checkParam["recs"]);
    unset($checkParam["sort"]);
    
    if(count($checkParam)>3){
        $searchMessage = "Search this set of images";
    }
    else{
        $searchMessage = "Search all images";
    }
    
    $full_link = $host.$requestURI;
    $full_link  = str_replace("&", "&amp;", $full_link );
    $full_link  = str_replace("&amp;amp;", "&amp;", $full_link );

$full_link = $host.$requestURI;
    $full_link  = str_replace("&", "&amp;", $full_link );
    $full_link  = str_replace("&amp;amp;", "&amp;", $full_link );

    $fulltext = '';
    $fulltext .= '<input id="act_uri" type="hidden" value="'.$full_link.'" />';
    $fulltext .= '<div style="display:table; border-collapse:collapse; width:100%;">';
    $fulltext .= '<div style="display:table-row">';
    $fulltext .= '<div style="display:table-cell; text-align:left; vertical-align:middle; width:75%;"> ';
    $fulltext .= '<span style="text-align:left; font-size:.75em;" >';
    $fulltext .= 'Or, type a search term in the box';
    $fulltext .= '</span><br/>';
    $fulltext .= '<div id="b_search_tab">
                    <div id="b_search_row" class="b_search">
                        <div id="b_search_cell_in" >
                            <input name="q" type="text" id="q_string" placeholder="Search here..." />
                        </div>
                        <div id="b_search_cell_button">
                            <button type="submit" onclick="textSearch();">Search</button>
                        </div>
                    </div>
                </div>
    ';
    
    $fulltext .= '</div>';
    $fulltext .= '</div>';
    $fulltext .= '</div>';
}
else{
    $fulltext = "";
}



$numFound = $this->numFound;
$facets = $this->facets;
$docs = $this->docs;

$filter_message = "(View is not filtered)";
$filter_output = $filter_message;
$filter_output = OpenContext_FacetOutput::make_filters_html($requestParams, $host);

$facet_fields = $facets["facet_fields"];
$facet_queries = $facets["facet_queries"];
$extendedFacets = true; //show more available facets 


//do advanced search interface
if(substr_count($requestURI, "advanced=true")>0){
    $advanced = true;
}
else{
    $advanced = false;
}


$facet_output = OpenContext_FacetOutput::facets_available($extendedFacets, $facet_fields, $facet_queries, $requestParams, $request_array, $host, $advanced);



//make sort links
$sortingArray = array(0 => array("value" => "context", "display" => "Context"),
                      1 => array("value" => "proj", "display" => "Project name"),
                      2 => array("value" => "label", "display" => "Item label"),
                      3 => array("value" => "updated", "display" => "Updated time"),
                      4 => array("value" => "created", "display" => "Publication time"),
                );

if(isset($requestParams["sort"])){
    $newSort = array();
    $newSort[] = array("value" => false, "display" => "Interest Score [Default]");
    $skip = 0;
    foreach($sortingArray as $sorter){
        if(strstr($requestParams["sort"], $sorter["value"])){
            $skip++;
        }
        if($skip != 1){
            $newSort[] = $sorter;
        }
        else{
            $skip = 2;
        }
    }
    $sortingArray = $newSort;
    unset($newSort);
}



$googleURI = "";
$facetAtomURI = "";
$openSearchURI = "";


?>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
        <title><?php echo 'Open Context Image Lightbox: ('.$numFound.' Images Showing)'; ?></title> 
        <link rel="shortcut icon" href="/images/general/oc_favicon.ico" type="image/x-icon"/>
        <!--
        <link href="<?php echo $host; ?>/components/css/lightbox" rel="stylesheet" type="text/css" />
        -->
        <link href="<?php echo $host; ?>/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" /> 
        <link href="<?php echo $host; ?>/css/opencontext-browse-rev2.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/colorbox.css" rel="stylesheet" type="text/css" />
        
        <link rel="alternate" type="application/atom+xml" title="Atom facet feed" href="<?php echo URIescape($this->facetURI_Atom); ?>" />
        <link rel="alternate" type="application/atom+xml" title="Atom feed of results" href="<?php echo URIescape($this->currentAtom); ?>" />
        
        <link rel="first" type="application/atom+xml" title="Atom feed of results" href="<?php echo URIescape($this->firstPage_XHTML); ?>" />
        <?php
            if($this->prevPage_XHTML != false){
                echo '<link rel="prev" type="application/atom+xml" title="Atom feed of results" href="'.URIescape($this->prevPage_XHTML).'" />'.chr(13);
            }
            if($this->nextPage_XHTML != false){
                echo '<link rel="next" type="application/atom+xml" title="Atom feed of results" href="'.URIescape($this->nextPage_XHTML).'" />'.chr(13);
            }
        ?>
        
        <link rel="last" type="application/atom+xml" title="Atom feed of results" href="<?php echo URIescape($this->lastPage_XHTML); ?>" />
        <link rel="search" type="application/opensearchdescription+xml" href="<?php echo $openSearchURI; ?>" title="Open Context Web Search" />
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
        <script src="<?php echo $host; ?>/components/js/lightbox" type="text/javascript"></script>
        <style type="text/css">
        
            div.imageCell {
                display:table-cell; width: 33%; text-align: center; padding: 4px; vertical-align:middle;
            }
            div.imageCell img {
                max-width: 120px;
                height: auto;
            }
            div.controlCell {
                display:table-cell; text-align:center; vertical-align:middle;
            }
        
        </style>
        
        
        <script type="text/javascript">
        <!--
            
            <?php
        
        echo "var baseURI = '".$host.$requestURI."'; \n";
        echo "var contextBase = '".$host.$request_array[0]."'; \n";
        echo "var paramterBase = '".$request_array[1]."'; \n";
        
        echo chr(13).chr(13);
        
        $activeTaxaValue = OpenContext_FacetOutput::active_taxon_value($requestParams); //for local taxonomies
        echo "var activeTaxaValue = '".$activeTaxaValue."'; \n";
        
        echo chr(13);
        $activeRelationValue = OpenContext_FacetOutput::active_taxon_value($requestParams, false); //for linked data relations
        echo "var activeRelationValue = '".$activeRelationValue."'; \n";
        
        ?>
            
            
            function openList(listId){
                var displayControl = listId + "control";
                var displayStatus = document.getElementById(listId).style.display;
                if( displayStatus == "none"){
                    document.getElementById(listId).style.display = "";
                    document.getElementById(displayControl).innerHTML = "<em>(Hide list below)</em>";
                }
                else{
                    document.getElementById(listId).style.display = "none";
                    document.getElementById(displayControl).innerHTML = "More...";
                }
            }
            
            
        
        
        $(document).ready(function(){
				//Examples of how to assign the ColorBox event to elements.
				
				$("a[rel='colorbox_prev']").colorbox({transition:"elastic"});
				
			});
      
      -->
        </script>
    </head>
    <body>
    
        <!-- 
            Logo,
        -->    
        <?php echo $this->render('header.phtml'); //reader document top ?>
           
        <!-- 
            Navigation tabs, search box
        -->
        <?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>
    
    
        <div id="main"> 
            <!--Begin code for showing available facets-->
            <div id="main_content">
                <div id="main_row">
                    <div id="left_cont">
                        <div id="filter_options">
                            <h3>Browse and Filter Images</h3>
                            <p>Click on one of the links below to further limit your view of <em>images</em> in Open Context.</p>
                            <div>
                            <?php echo  $fulltext; ?>
                            </div>
                            <div id="facet_sort_tab">
                                <div id="facet_sort_row">
                                    <?php
                                    if(isset($requestParams["facetSort"])){
                                        $facetSort = "10,9,8 &darr;";
                                        $facetSortMessage = "Sort facets by count:";
                                        unset($requestParams["facetSort"]);
                                        $facetSortLink = OpenContext_FacetOutput::generateFacetURL($requestParams, false, false, false);
                                    }
                                    else{
                                        $facetSort = "A,B,C &darr;";
                                        $facetSortMessage = "Sort facets alphabetically:";
                                        $facetSortLink = OpenContext_FacetOutput::generateFacetURL($requestParams, "facetSort", true, false);
                                    }
                                    
                                    ?>
                                    <div id="facet_sort_message_cell">
                                        <?php echo $facetSortMessage; ?>
                                    </div>
                                    <div id="facet_sort_control_cell">
                                        <div id="facet_sort_control"><a href="<?php echo $facetSortLink; ?>" title="Change the order of the facet filters below"><?php echo $facetSort; ?></a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="all_facets">
                            <?php echo $facet_output; ?>
                        </div>
                    </div>
                    <div id="right_cont">
                        <div id="selected_filters" >
                            <p>Open Context currently has <strong><?php echo $numFound; ?></strong> images, filtered by the following criteria:</p>
                            <div><?php echo $filter_output; ?></div>
                            <div style="text-align:right;">
                                <p class="tinyText">Last Updated: <em><?php echo date("F j, Y, g:i a", strtotime($this->lastUpdate)); ?></em></p>
                            </div>
                        </div>
                        <div id="item_list_outer">
                        
                            <?php  
                                /*
                                    Prepare image thumnail list 
                                */
                                
                                $xmlString = "<div style='width:100%;'></div>";
                                $xmlALL = simplexml_load_string($xmlString);
                                $xml = $xmlALL->addChild('div', '');
                                $xml->addAttribute('style', "display:table; width:100%;");
                                $xml->addAttribute('id', "result_tab");
                                
                                $newRow = true;
                                $cc = 0;
                                $firstDone = false;
                                foreach($this->result_output as $imageArray){
                                    
                                    
                                    $prevLink =  $xmlALL->addChild('a', '');
                                    $prevLink->addAttribute('href', $imageArray["previewURI"]);
                                    $prevLink->addAttribute('title', $imageArray["label"]);
                                    $prevLink->addAttribute('rel', 'colorbox_prev');
                                    
                                    if(!$firstDone){
                                        $firstPreviewURI = $imageArray["previewURI"];
                                        $firstTitle = $imageArray["label"];
                                        $firstDone = true;
                                    }
                                    
                                    if($cc >= 3){
                                        $newRow = true;
                                    }
                                    
                                    if($newRow){
                                        $actRow = $xml->addChild('div', '');
                                        $actRow->addAttribute('style', 'display:table-row;');
                                        $cc = 0;
                                        $newRow = false;
                                    }
                                    
                                    $newCell = $actRow->addChild('div', '');
                                    //$newCell->addAttribute('style', 'display:table-cell; width: 33%; text-align: center;');
                                    $newCell->addAttribute('class', 'imageCell');
                                    $newLink =  $newCell->addChild('a', '');
                                    $newLink->addAttribute('href', $imageArray["uri"]);
                                    $newLink->addAttribute('title', $imageArray["label"]);
                                    $newImg = $newLink->addChild('img', '');
                                    $newImg->addAttribute('src', $imageArray["thumbURI"]);
                                    $newImg->addAttribute('alt', $imageArray["label"]);
                                
                                $cc++;
                                }//end loop
                                
                                $dom = dom_import_simplexml($xml)->ownerDocument;
                                $dom->formatOutput = true;
                                $imageThumbs = str_replace('<?xml version="1.0"?>', '', $dom->saveXML());

                            ?>
                        
                        
                            <div id="paging_outer">
                                <div id="paging_tab">
                                    <div id="paging_row">
                                        <div class="paging_cell">
                                            <?php
                                            
                                            if($this->firstPage_XHTML && $this->firstPage_XHTML != $this->currentXHTML){
                                                $linkClass = "pager_active";
                                                $pageLink = "<a href=\"".$this->firstPage_XHTML."\" class=\"btn btn-small btn-primary\" title=\"Go to the first page of results\" >|&larr;</a>";
                                            }
                                            else{
                                                $linkClass = "pager_inactive";
                                                $pageLink = "|&larr;";
                                                $pageLink = "<a href=\"\" class=\"btn btn-small btn-primary disabled\">|&larr;</a>";
                                            }
                                            
                                            ?>
                                            <div class="<?php echo $linkClass; ?>" >
                                                <?php echo $pageLink; ?>
                                            </div>
                                        </div>
                                        <div class="paging_cell">
                                            <?php
                                            
                                            if($this->prevPage_XHTML){
                                                $linkClass = "pager_active";
                                                $pageLink = "<a href=\"".$this->prevPage_XHTML."\" class=\"btn btn-small btn-primary\" title=\"Go to the previous page of results\" >&larr;</a>";
                                            }
                                            else{
                                                $linkClass = "pager_inactive";
                                                $pageLink = "&larr;";
                                                $pageLink = "<a href=\"\" class=\"btn btn-small btn-primary disabled\">&larr;</a>";
                                            }
                                            
                                            ?>
                                            <div class="<?php echo $linkClass; ?>" >
                                                <?php echo $pageLink; ?>
                                            </div>
                                        </div>
                                        <div id="paging_cell_center">
                                            <div id="paging_ct_tab">
                                                <div id="paging_ct_row">
                                                    <div id="paging_slide_cell">
                                                        <a href="<?php echo $firstPreviewURI; ?>" rel="colorbox_prev" title="<?php echo "Slide show starting with: ".$firstTitle; ?>"><img src="<?php echo $host; ?>/images/layout/slides.png" /></a>
                                                    </div>
                                                    <div id="paging_ct_cell_pageNum">
                                                        <?php
                                                            if(isset($requestParams["page"])){
                                                                $page = $requestParams["page"];
                                                            }
                                                            else{
                                                                $page = 1;
                                                            }
                                                            
                                                            $numRecs = $this->number_recs;
                                                            $lastPage = intval($this->numFound/$numRecs);
                                                            if($lastPage * $numRecs < $numFound){
                                                                $lastPage++;
                                                            }
                                                            echo "Page $page of $lastPage";
                                                            echo ", sorted by ".$this->sorting;
                                                        ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <div id="sort_tab" style="width:100%;">
                                                <div id="sort_row">
                                                    <div id="sort_start">
                                                        Sort By:
                                                    </div>
                                                    <?php
                                                    foreach($sortingArray as $sorter){
                                                        $sortLink = OpenContext_FacetOutput::generateFacetURL($requestParams, "sort", $sorter["value"], false);
                                                    ?>
                                                    <div class="sort_cell">
                                                        <a href="<?php echo $sortLink; ?>" title="Sort results by <?php echo $sorter["display"]; ?>" ><?php echo $sorter["display"]; ?></a>
                                                    </div>
                                                    <?php
                                                    }//end loop through the sorting array
                                                    ?>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="paging_cell">
                                            <?php
                                            
                                            if($this->nextPage_XHTML){
                                                $linkClass = "pager_active";
                                                $pageLink = "<a href=\"".$this->nextPage_XHTML."\" class=\"btn btn-small btn-primary\" title=\"Go to the next page of results\" >&rarr;</a>";
                                            }
                                            else{
                                                $linkClass = "pager_inactive";
                                                $pageLink = "&rarr;";
                                                $pageLink = "<a href=\"\" class=\"btn btn-small btn-primary disabled\">&rarr;</a>";
                                            }
                                            
                                            ?>
                                            <div class="<?php echo $linkClass; ?>" >
                                                <?php echo $pageLink; ?>
                                            </div>
                                        </div>
                                        <div class="paging_cell">
                                            <?php
                                            
                                            if($this->lastPage_XHTML && $this->lastPage_XHTML != $this->currentXHTML){
                                                $linkClass = "pager_active";
                                                $pageLink = "<a href=\"".$this->lastPage_XHTML."\" title=\"Go to the last page of results\" class=\"btn btn-small btn-primary\" >&rarr;|</a>";
                                            }
                                            else{
                                                $linkClass = "pager_inactive";
                                                $pageLink = "&rarr;|";
                                                $pageLink = "<a href=\"\" class=\"btn btn-small btn-primary disabled\">&rarr;|</a>";
                                            }
                                            ?>
                                            <div class="<?php echo $linkClass; ?>" >
                                                <?php echo $pageLink; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        
                            <div id="image_results">
                                <?php
                                echo $imageThumbs;
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
    <div id="bottomBuffer">
    </div>
    <?php echo $this->render('footer.phtml'); //reader document footer ?>
    </body>
</html>    