<?php

function URIescape($uri){
    return str_replace("&", "&amp;", $uri);
}

// used to help create hyperlinks; set to current hostname.
$host = OpenContext_OCConfig::get_host_config();

define ('HOST', $host);

$auth = Zend_Auth::getInstance();
if (!$auth->hasIdentity()){
    $displayName = false;
}
else{
    $identity = $auth->getIdentity();
    $displayName = $identity->name;
}


$requestURI = $this->requestURI;
$request_array = explode('?', $requestURI, 2);
//array explode  ( string $delimiter  , string $string  [, int $limit  ] )

if (substr_compare($request_array[0], '/' , -1)) {  // if the uri doesn't end in a slash (minus query parameters), 
    $request_array[0] = $request_array[0] . '/';  // add one
}


if (isset($request_array[1])) { // if there are query parameters,
    $request_array[1] = "?" . $request_array[1];  // prepend a '?' to the set of parameters since we exploded on the '?' to get this string. 
    //echo $request_array[1]; // for testing
} else {
    $request_array[1] = null;
}


$requestParams = $this->requestParams;
if(!isset($requestParams["q"])){
    
    $checkParam = $requestParams;
    unset($checkParam["page"]);
    unset($checkParam["recs"]);
    unset($checkParam["sort"]);
    
    if(count($checkParam)>3){
        $searchMessage = "Search this set of images";
    }
    else{
        $searchMessage = "Search all images";
    }
    
    $full_link = $host.$requestURI;
    $full_link  = str_replace("&", "&amp;", $full_link );
    $full_link  = str_replace("&amp;amp;", "&amp;", $full_link );

    /*
    $fulltext = '<p class="bodyText">Or, type a search term in the box below (works like Google):</p>'.chr(13);
    //$fulltext .= '<form id="searchbox" name="form4" method="get" action="'.$requestURI.'">'.chr(13);
    $fulltext .= '<div style="padding:4px; text-align:center;">';
    $fulltext .= '<input id="act_uri" type="hidden" value="'.$full_link.'" />';
    $fulltext .='<input name="q" type="text" id="q_string" size="30" maxlength="100" class="bodyText" alt="Enter full-text search term(s)" onchange="textSearch()" />'.chr(13);
    $fulltext .= '<div style="display:table-row; width:100%;">';
    //$fulltext .='<input type="submit" id="submit" value="'.$searchMessage.'" class="bodyText" alt="Run full-text search" onclick="textSearch();"/>'.chr(13);
    $fulltext .= '<div style="display:table-cell; text-align:center; vertical-align:middle; padding-left:20px;" class="bodyText"> ';
    $fulltext .= $searchMessage;
    $fulltext .= '</div>';
    $fulltext .= '<div style="display:table-cell; text-align:right; vertical-align:middle; padding-top:3px;" > ';
    $fulltext .= '<a href="javascript:textSearch();"><img src="http://static.alexandriaarchive.org/images/general/searchButtonSmall.png" alt="Search icon"/></a>';
    $fulltext .= '</div>';
    $fulltext .= '</div>';
    $fulltext .= '</div>';
    */
    
    //$fulltext = '<p class="bodyText">Or, type a search term in the box below (works like Google):</p>'.chr(13);
    //$fulltext .= '<form id="searchbox" name="form4" method="get" action="'.$requestURI.'">'.chr(13);
    $fulltext = '';
    $fulltext .= '<div style="display:table;">';
    $fulltext .= '<div style="display:table-row; width:100%;">';
    $fulltext .= '<div style="display:table-cell; text-align:left;" class="bodyText">';
    $fulltext .= 'Or, type a search term in the box below (works like Google):';
    $fulltext .= '</div>';
    $fulltext .= '</div>';
    $fulltext .= '<input id="act_uri" type="hidden" value="'.$full_link.'" />';
    $fulltext .= '<div style="display:table-row; width:100%;">';
    $fulltext .= '<div style="display:table-cell; text-align:left; vertical-align:middle; padding-left:4px;"> ';
    $fulltext .='<input style="background-color:#FBF7EC;" name="q" type="text" id="q_string" size="25" maxlength="100" class="bodyText" alt="'.$searchMessage.'" onchange="textSearch()" />'.chr(13);
    $fulltext .= '</div>';
    $fulltext .= '<div style="display:table-cell; text-align:right; vertical-align:middle; " > ';
    //$fulltext .='<input type="submit" id="submit" value="'.$searchMessage.'" class="bodyText" alt="Run full-text search" onclick="textSearch();"/>'.chr(13);
    $fulltext .= '<a title="'.$searchMessage.'" href="javascript:textSearch();"><img src="http://static.alexandriaarchive.org/images/general/searchButtonSmall.png" alt="Search icon"/></a>';
    $fulltext .= '</div>';
    $fulltext .= '</div>';
    $fulltext .= '</div>';
    
    
    
    //$fulltext .='</form>';
}
else{
    $fulltext = "";
}



$numFound = $this->numFound;
$facets = $this->facets;
$docs = $this->docs;

$filter_message = "(View is not filtered)";
$filter_output = $filter_message;
$filter_output = OpenContext_FacetOutput::make_filters_html($requestParams, $host);

$facet_fields = $facets["facet_fields"];
$facet_queries = $facets["facet_queries"];
$extendedFacets = true; //show more available facets 


//do advanced search interface
if(substr_count($requestURI, "advanced=true")>0){
    $advanced = true;
}
else{
    $advanced = false;
}


$facet_output = OpenContext_FacetOutput::facets_available($extendedFacets, $facet_fields, $facet_queries, $requestParams, $request_array, $host, $advanced);




$googleURI = "";
$facetAtomURI = "";
$openSearchURI = "";


?>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
        <title><?php echo 'Open Context Image Lightbox: ('.$numFound.' Images Showing)'; ?></title> 
        <link rel="shortcut icon" href="/images/general/oc_favicon.ico" type="image/x-icon"/>
        <link href="<?php echo $host; ?>/components/css/lightbox" rel="stylesheet" type="text/css" />
        <link rel="alternate" type="application/atom+xml" title="Atom facet feed" href="<?php echo URIescape($this->facetURI_Atom); ?>" />
        <link rel="alternate" type="application/atom+xml" title="Atom feed of results" href="<?php echo URIescape($this->currentAtom); ?>" />
        
        <link rel="first" type="application/atom+xml" title="Atom feed of results" href="<?php echo URIescape($this->firstPage_XHTML); ?>" />
        <?php
            if($this->prevPage_XHTML != false){
                echo '<link rel="prev" type="application/atom+xml" title="Atom feed of results" href="'.URIescape($this->prevPage_XHTML).'" />'.chr(13);
            }
            if($this->nextPage_XHTML != false){
                echo '<link rel="next" type="application/atom+xml" title="Atom feed of results" href="'.URIescape($this->nextPage_XHTML).'" />'.chr(13);
            }
        ?>
        
        <link rel="last" type="application/atom+xml" title="Atom feed of results" href="<?php echo URIescape($this->lastPage_XHTML); ?>" />
        <link rel="search" type="application/opensearchdescription+xml" href="<?php echo $openSearchURI; ?>" title="Open Context Web Search" />
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
        <script src="<?php echo $host; ?>/components/js/lightbox" type="text/javascript"></script>
        <style type="text/css">
        
            div.imageCell {
                display:table-cell; width: 33%; text-align: center; padding: 4px; vertical-align:middle;
            }
            div.imageCell img {
                max-width: 120px;
                height: auto;
            }
            div.controlCell {
                display:table-cell; text-align:center; vertical-align:middle;
            }
        
        </style>
        
        
        <script type="text/javascript">
        <!--
            
            <?php
        
        echo "var baseURI = '".$host.$requestURI."'; \n";
        echo "var contextBase = '".$host.$request_array[0]."'; \n";
        echo "var paramterBase = '".$request_array[1]."'; \n";
        
        echo chr(13).chr(13);
        
        $activeTaxaValue = OpenContext_FacetOutput::active_taxon_value($requestParams); //for local taxonomies
        echo "var activeTaxaValue = '".$activeTaxaValue."'; \n";
        
        echo chr(13);
        $activeRelationValue = OpenContext_FacetOutput::active_taxon_value($requestParams, false); //for linked data relations
        echo "var activeRelationValue = '".$activeRelationValue."'; \n";
        
        ?>
            
            
            function openList(listId){
                var displayControl = listId + "control";
                var displayStatus = document.getElementById(listId).style.display;
                if( displayStatus == "none"){
                    document.getElementById(listId).style.display = "";
                    document.getElementById(displayControl).innerHTML = "<em>(Hide list below)</em>";
                }
                else{
                    document.getElementById(listId).style.display = "none";
                    document.getElementById(displayControl).innerHTML = "More...";
                }
            }
            
            
        
        
        $(document).ready(function(){
				//Examples of how to assign the ColorBox event to elements.
				
				$("a[rel='colorbox_prev']").colorbox({transition:"elastic"});
				
			});
      
      -->
        </script>
    </head>
    <body>
        
    <div id="oc_logo">
	<a href="<?php echo $host;?>" title="Open Context (Home)"><img alt="Open Context Logo" src="http://static.alexandriaarchive.org/images/general/oc_logo.jpg" border="0" /></a>
    </div>
    <div id="oc_tagline">
	<img alt="Open Context Tagline" src="http://static.alexandriaarchive.org/images/general/oc_tagline.jpg" />
    </div>
    <div id="oc_beta">
	<img alt="Beta Stamp" src="http://static.alexandriaarchive.org/images/general/oc_betastamp.jpg" />
    </div>
    <!--
    <div id="oc_top_search">
	<form method="get" action="<?php echo $host;?>/search/" id="search-form">
	<div id="search_box">
	<input type='text' name='q' class='tinyText' value='New Search' size='30' onfocus="if(this.value=='New Search')this.value='';" onblur="if(this.value=='')this.value='New Search';" />
	</div>
	<div id="search_cntrl">
	    <input class="oc_top_sbutton" type="submit" value="" />
	</div>
	</form>
    </div>
   -->
   
   <!-- 
    Navigation tabs
    -->    
    <?php echo OpenContext_NavMenus::GeneralNavMenu("lightbox"); ?> 
    
    
        
<!--
BEGIN Container for main page content
--> 
    <div id="main_page"> 
        <!--Begin code for showing available facets-->
        <div id="main_content">
            <div id="left_cont">
                <div id="filter_options" class="bodyText">
                    <p class="bodyText"><strong>Click on one of the links below to further limit your view of <em>images</em> in Open Context.</strong></p>
                        <?php echo  $fulltext; ?>
                    <br/>
                        <?php echo $facet_output; ?>
                            
                    <br/>
                    
                    <!--
                    <p>View in <a href="<?php echo URIescape($this->facetURI_KML); ?>">GoogleEarth</a></p>
                    -->
                    <p>Get in <a href="<?php echo URIescape($this->facetURI_Atom); ?>">Atom</a></p>
                </div>
            </div>
            <div id="right_cont">   
                <div id="selected_filters" class="rounded-corners" >
                    <p class="subHeader">Open Context currently has <strong><?php echo $numFound; ?></strong> images, filtered by the following criteria:</p>
                    <div class="bodyText"><?php echo $filter_output; ?></div>
                    <p class="tinyText" style="text-align:right;">Last Updated: <em><?php echo date("F j, Y, g:i a", strtotime($this->lastUpdate)); ?></em></p>
                    
                </div>
                        
                <br />
                <br />
                        
                <?php
                
                /*
                    Prepare image thumnail list 
                */
                
                $xmlString = "<div style='width:100%;'></div>";
                $xmlALL = simplexml_load_string($xmlString);
                $xml = $xmlALL->addChild('div', '');
                $xml->addAttribute('style', "display:table; width:100%;");
                $xml->addAttribute('id', "result_tab");
                
                $newRow = true;
                $cc = 0;
                $firstDone = false;
                foreach($this->result_output as $imageArray){
                    
                    
                    $prevLink =  $xmlALL->addChild('a', '');
                    $prevLink->addAttribute('href', $imageArray["previewURI"]);
                    $prevLink->addAttribute('title', $imageArray["label"]);
                    $prevLink->addAttribute('rel', 'colorbox_prev');
                    
                    if(!$firstDone){
                        $firstPreviewURI = $imageArray["previewURI"];
                        $firstTitle = $imageArray["label"];
                        $firstDone = true;
                    }
                    
                    if($cc >= 3){
                        $newRow = true;
                    }
                    
                    if($newRow){
                        $actRow = $xml->addChild('div', '');
                        $actRow->addAttribute('style', 'display:table-row;');
                        $cc = 0;
                        $newRow = false;
                    }
                    
                    $newCell = $actRow->addChild('div', '');
                    //$newCell->addAttribute('style', 'display:table-cell; width: 33%; text-align: center;');
                    $newCell->addAttribute('class', 'imageCell');
                    $newLink =  $newCell->addChild('a', '');
                    $newLink->addAttribute('href', $imageArray["uri"]);
                    $newLink->addAttribute('title', $imageArray["label"]);
                    $newImg = $newLink->addChild('img', '');
                    $newImg->addAttribute('src', $imageArray["thumbURI"]);
                    $newImg->addAttribute('alt', $imageArray["label"]);
                
                $cc++;
                }//end loop
                
                $dom = dom_import_simplexml($xml)->ownerDocument;
                $dom->formatOutput = true;
                $imageThumbs = str_replace('<?xml version="1.0"?>', '', $dom->saveXML());
                
                
                /*
                Add paging controls
                */
                if($this->firstPage_XHTML != $this->currentXHTML){
                    //not page 1
                    $first_control = '<a href="'.URIescape($this->firstPage_XHTML).'">';
		    $first_control .= '<img src="/images/atom_results/left_button_last.gif" alt="first page" border="0" />';
		    $first_control .= '</a>'; 
                }
                else{
                    //we're on the first page
                    $first_control = '<img src="/images/atom_results/left_button_last_deact.gif" alt="first page" border="0" />'.chr(13);
                }
                if($this->prevPage_XHTML != false){
                    //previous page exists
                    $prev_control = '<a href="'.URIescape($this->prevPage_XHTML).'">';
		    $prev_control .= '<img src="/images/atom_results/left_button.gif" alt="first page" border="0" />';
		    $prev_control .= '</a>';
                }
                else{
                    //no previous page
                    $prev_control = '<img src="/images/atom_results/left_button_deact.gif" alt="first page" border="0" />'.chr(13);
                }
                if($this->nextPage_XHTML != false){
                    $next_control = '<a href="'.URIescape($this->nextPage_XHTML).'">';
		    $next_control .= '<img src="/images/atom_results/right_button.gif" alt="next page" border="0" />';
		    $next_control .= '</a>';
                }
                else{
                    $next_control = '<img src="/images/atom_results/right_button_deact.gif" alt="previous page" border="0" />'.chr(13);
                }
                if($this->lastPage_XHTML != $this->currentXHTML){
                    $last_control = '<a href="'.URIescape($this->lastPage_XHTML).'">';
		    $last_control .= '<img src="/images/atom_results/right_button_last.gif" alt="last page" border="0" />';
		    $last_control .= '</a>';
                }
                else{
                    $last_control = '<img src="/images/atom_results/right_button_last_deact.gif" alt="previous page" border="0" />'.chr(13);
                }
                ?>
                
                <div id="result_head">
                    <div style="display:table; width:100%;">
                        <div style="display:table-row;">
                            <div class="controlCell">
                                <?php echo $first_control; ?>
                            </div>
                            <div class="controlCell">
                                <?php echo $prev_control; ?>
                            </div>
                            <div style="display:table-cell; text-align:center; vertical-align:middle;" class="bodyText">
                                <strong>Results: </strong>
                                <?php   echo ($this->offset + 1)." to ".($this->number_recs + $this->offset)." of ".$numFound." images <br/>";
                                        echo "<a href='".$firstPreviewURI."' rel='colorbox_prev' title='".$firstTitle."'>Slideshow view</a>";
                                ?>
                            </div>
                            <div class="controlCell">
                                <?php echo $next_control; ?>
                            </div>
                            <div class="controlCell">
                                <?php echo $last_control; ?>
                            </div>
                        </div>
                    </div>
                </div>
                    
                    <div id="item_list">
                        
                        <?php
                            echo $imageThumbs;
                            $feed_link = '<div class="container_a">'.chr(13);
                            $feed_link .= '<div class="container_l"><p class="tinyText">Get results as an Atom Feed: <br/><a href="'.$host.'/about/services">(About web services)</a></p></div>'.chr(13);
                            $feed_link .= '<div class="container_r"><a href="'.URIescape($this->currentAtom).'"><img border="0" src="http://validator.w3.org/feed/images/valid-atom.png" alt="[Valid Atom 1.0]" title="Atom 1.0 feed"/></a></div>'.chr(13);
                            $feed_link .= '</div>'.chr(13);
                            echo $feed_link;
                        ?>
                        
                    </div>
                
                <?php //echo var_dump($request_array)."<br/><br/>"; ?>
                
            </div>
                    
   
        <!--
        END of div container for placing main page content
        -->
        <div id="bottom_cont">  
          <br /> 
          <br /> 
        </div> 
        <!--
        END Code for showing the database-like content
        -->
   
     </div>
    <br />
    
        <div id="footer"> 
            <div id="w3c_val_logo"> 
              <a href="http://validator.w3.org/check?uri=referer"> 
                <img src="http://www.w3.org/Icons/valid-xhtml10-blue" alt="Valid XHTML 1.0 Transitional" height="31" width="88" /> 
              </a> 
            </div>     
        </div>
   
     </div>
    </body>
</html>    