<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>item</title>
</head>
<body>
    <h1>Here are your media.</h1>
    <p>
    <?php
    //echo $this->query.'<br/>';
    //echo var_dump($this->result).'<br/>';
    echo $this->uuid.'<br/>';
    ?>
    </p>
</body>
</html>
