<?php

$host = OpenContext_OCConfig::get_host_config();
$XML = $this->xml_string;
if ($XML) {

    $doc = new DOMDocument();

    $useragent = @$_SERVER['HTTP_USER_AGENT'];

    /*
    if(strstr($useragent,"MSIE")){
        $doc->load("xsl/defaultSpatial.xsl");
    }    
    else{
        $doc->load("xsl/defaultSpatial_rdfa.xsl");
    }
    */
    $doc->load("xsl/rev2-media.xsl");
    
    $proc = new XSLTProcessor();
    $xslt = $proc->importStylesheet($doc);
    $archaeoMLDoc = new DomDocument();
    $archaeoMLDoc->loadXML($XML);
    
    $newDom = $proc->transformToDoc($archaeoMLDoc);
    $newDom->formatOutput = true;
    //$rootNode = $newDom->getElementsByTagName("div")->item(0);
    //$XHTMLbody = $newDom->saveXML($rootNode);
    $XHTMLbody = $newDom->saveHTML();
	 $XHTMLbody = str_replace('<!DOCTYPE div PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">','', $XHTMLbody); // a hack to get rid of this for older php

}
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    
    <title>Open Context Media Item: <?php echo $this->label; ?></title>
    
    <link rel="shortcut icon" href="/images/layout/oc-favicon.ico" type="image/x-icon" />
    <link rel="alternate" type="application/atom+xml" tilte="Atom representation" href="<?php echo $host; ?>/media/<?php echo $this->itemUUID; ?>.atom" />
    <link href="<?php echo $host; ?>/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $host; ?>/css/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $host; ?>/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $host; ?>/css/subject-rev2.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $host; ?>/css/general-item-rev2.css" rel="stylesheet" type="text/css" />
    <script src="<?php echo $host; ?>/js/jquery/jquery-1.7.2.min.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-transition.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-tab.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-dropdown.js" type="text/javascript"></script>
    <script type="text/javascript">
        <!--
        
        $('.dropdown-toggle').dropdown()
        
        
        -->
    </script>
    </head>
    <body>
        <!-- 
            Logo,
        -->    
        <?php echo $this->render('header.phtml'); //reader document top ?>
           
        <!-- 
            Navigation tabs, search box
        -->
        <?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>
    
        <?php echo $XHTMLbody; ?>
        
        <div id="bottomBuffer">
        </div>
        </div>
        <?php echo $this->render('footer.phtml'); //reader document footer ?>
        <script type="text/javascript">
        <!--
         $('#obsTabs a').click(function (e) {
            e.preventDefault();
            $(this).tab('show');
          });
         
            var url = document.location.toString();
            if (url.match('#')) {
                $('.nav-tabs a[href=#'+url.split('#')[1]+']').tab('show') ;
            }
            
            // Change hash for page-reload
            $('.nav-tabs a').on('shown', function (e) {
                window.location.hash = e.target.hash;
            })
         -->
    </script>
    </body>
</html>
