<?php

// used to help create hyperlinks; set to current hostname.
//$host = "http://ishmael.ischool.berkeley.edu";
//$host = "http://opencontext";
$host = OpenContext_OCConfig::get_host_config();
$GMapURI = OpenContext_OCConfig::get_google_api();
//$GMapURI = "http://maps.google.com/maps?file=api&amp;v=2&amp;key=".$GMapURI;
//$GMapURI = "http://maps.google.com/maps/api/js?sensor=false&amp;key=".$GMapURI;
$GMapURI = "http://maps.googleapis.com/maps/api/js?sensor=false";

$OAI_url = $host."/oai/request";
$lastUpdate = date("F j, Y", strtotime(OpenContext_OCConfig::last_update()));


?>


<!DOCTYPE html>
<html lang="en"> 
    <head> 
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Open Context: Data Publication for Cultural Heritage and Field Research</title> 
        <link rel="shortcut icon" href="/images/general/oc_favicon.ico" type="image/x-icon" />
        <script src="<?php echo $GMapURI; ?>" type="text/javascript"></script> 
        
        
        <link href="/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
        <link href="/css/home-rev2.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" />
        
        
        <!-- <script type="text/javascript" src="../js/timemap2/lib/jquery-1.4.4.min.js"></script> -->
        <script src="<?php echo $host; ?>/js/jquery/jquery-1.7.2.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="../js/timemap2/lib/mxn/mxn.js?(googlev3)"></script>
        <script type="text/javascript" src="http://opencontext.org/js/timemap/lib/timeline-2.3.0.js"></script>
        <script src="http://opencontext.org/js/timemap2/src/timemap.js" type="text/javascript"></script>
        <script src="http://opencontext.org/js/timemap2/src/loaders/json.js" type="text/javascript"></script>
        <script src="../js/timemap2/oc.js" type="text/javascript"></script>
        <script src="../js/timemap2/circle_icons.js" type="text/javascript"></script>
        
        <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-transition.js" type="text/javascript"></script>
        <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-collapse.js" type="text/javascript"></script>
     
        <script type="text/javascript">
            var tm;
            var timeMapURL = "<?php echo $host; ?>/maps/time-map.json";
            
            
            var numRangeThemes = 9;
            var redRange = [255,255];
            var greenRange = [200,0];
            var blueRange = [0,0];
            var alphaRange = [225,150];
            
            //calculates a new color between a range
            function rangeDiff(colorRange, themeNumber, doHex){
                var colorDif = (colorRange[1] - colorRange[0]) / numRangeThemes;
                var newColor = colorRange[0]+ (colorDif * themeNumber);
                newColor = Math.round(newColor);
                if(doHex){
                    newColor =  newColor.toString(16);
                }
                return newColor;
            }
            
            function addLegendImage(actSize, actColor, actAlpha){
                var recCells = document.getElementById("legend-cells");
                var legCell = document.createElement("div");
                legCell.setAttribute("class", "div-cell-leg");
                var legImage = document.createElement("img");
                var imageSRC = circleURL(actSize, actColor, actAlpha);
                legImage.setAttribute("src", imageSRC);
                legCell.appendChild(legImage);
                recCells.appendChild(legCell);
           
            }
            
            function onLoadTM() {
                // add new interval
                SimileAjax.DateTime.addInterval('TFK', 25000);
                SimileAjax.DateTime.addInterval('TFH', 250);
                SimileAjax.DateTime.addInterval('TENK', 10000);
                SimileAjax.DateTime.addInterval('FTK', 5000);
                SimileAjax.DateTime.addInterval('FHK', 500);
                SimileAjax.DateTime.addInterval('HNDK', 100000);
                
                
                var zones1 = [
                        {   
                            start:    "-250000",
                            end:      "-10000",
                            magnify:  1,
                            unit:     Timeline.DateTime.TENK
                        },
                        {   
                            start:    "-9999",
                            end:      "-4000",
                            magnify:  1,
                            unit:     Timeline.DateTime.MILLENNIUM
                        },
                        {   
                            start:    "-3999.999",
                            end:      "1000",
                            magnify:  8,
                            unit:     Timeline.DateTime.TFH
                        },

                        {   
                            start:    "1000.001",
                            end:      "2050",
                            magnify:  8,
                            unit:     Timeline.DateTime.CENTURY
                        }
                    ];
                var zones2 = [
                        {   
                            start:    "-250000",
                            end:      "-30000",
                            magnify:  3,
                            unit:     Timeline.DateTime.TFK
                        },
                        {   
                            start:    "-29999.999",
                            end:      "-10000",
                            magnify:  4,
                            unit:     Timeline.DateTime.TENK
                        },
                        {   
                            start:    "-9999.999",
                            end:      "2050",
                            magnify:  5,
                            unit:     Timeline.DateTime.FTK
                        }
                    ];
                

                var actColor = "rgb(" + redRange[0] + "," + greenRange[0] + "," + blueRange[0] + ")";
                var actAlpha = alphaRange[0].toString(16); 
                for (var awe = 1; awe <= numRangeThemes ; awe++) {
                    // Create a new theme and add it to the TimeMap.themes namespace
                    var actSize = 12 + (awe * 4);
                    TimeMap.themes["theme-size-" + awe] = TimeMapTheme.createCircleTheme({
                        size: actSize,
                        color: actColor,
                        alpha: actAlpha
                    });
                    addLegendImage(actSize, actColor, actAlpha);
                    actColor = "rgb(" + rangeDiff(redRange, awe, 0) + "," +rangeDiff(greenRange, awe, 0) + "," + rangeDiff(blueRange, awe, 0) + ")";
                    actAlpha = rangeDiff(alphaRange, awe, 1);
                }
               
                TimeMap.themes["forthcoming"] = TimeMapTheme.createCircleTheme({
                        size: 20,
                        color: "rgb(30,1,200)"
                        //color: "BB07ED"
                    });
               
                
                
                tm = TimeMap.init({
                    mapId: "map",               // Id of map div element (required)
                    timelineId: "timeline",     // Id of timeline div element (required)
                    scrollTo: "-500",
                    options: {
                        dateParser: "gregorian",
                        eventIconPath: "/js/timemap2/images/"
                    },
                    datasets: [
                        {
                            title: "Open Context",
                            id: "ocData",
                            theme: "red",
                            type: "json_string",
                            options: {
                                url: timeMapURL
                            }
                        }
                    ],
                     // need to make the bands in this verbose manner to set max/min dates
                  
                    
                        bands: [
                            Timeline.createHotZoneBandInfo({
                                eventSource:    false,
                                width:          "75%",
                                intervalUnit:   Timeline.DateTime.FHK,
                                intervalPixels: 65,
                                zones:          zones1
                            }),
                            Timeline.createHotZoneBandInfo({
                                eventSource:    false,
                                width:          "25%",
                                intervalUnit:   Timeline.DateTime.TENK,
                                intervalPixels: 85,     
                                layout:         'overview',
                                zones:          zones2
                            })
                        ]
                } );
            }
        </script>
        
      
  </head>

  <body onload="onLoadTM();" >
        
        <!-- 
            Logo,
        -->    
        <?php echo $this->render('header.phtml'); //reader document top ?>
           
        <!-- 
            Navigation tabs, search box
        -->
        <?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>
        
        
        <div id="main">
            <div id="main_content">
                <div id="intro-row">
                    <div id="intro-cell">
                        <h1>Welcome to Open Context</h1>
                    </div>
                    <div id="into-cellB">
                        <br/>
                    </div>
                </div>
            </div>
    
    
    
            <div id="timemap">
                <div class="accordion" id="accordion2">
                    <div class="accordion-group">
                        <div class="accordion-heading">
                          <div class="div-tab">
                              <div class="div-row">
                                  <div class="div-cell">
                                      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                                        Timeline
                                      </a>
                                  </div>
                                  <div id="proj-size">
                                        <div class="div-tab">
                                            <div class="div-row">
                                                <div class="div-cell" style="width:22%;">
                                                    <h5>Number of Records</h5>
                                                </div>
                                                <div class="div-cell" style="padding-left:4px; padding-right:6px;">50</div>
                                                <div id="legend-cells"></div>
                                                <div class="div-cell" style="text-align: left;">150,000</div>
                                            </div>
                                        </div>
                                  </div>
                              </div>
                          </div>
                        </div>
                        <div id="collapseOne" class="accordion-body collapse">
                          <div class="accordion-inner">
                              
                              <div id="timelinecontainer">
                                  <div id="timeline"></div>
                              </div>
                              
                          </div>
                        </div>
                        
                        <div id="mapcontainer">
                            <div id="map"></div>
                        </div>
                        
                    </div>
                    
                    
                    
                </div>
                
                
                
            </div>
    
    
            <!--
    
            <div id="timemap">
                <div id="timelinecontainer">
                  <div id="timeline"></div>
                </div>
                <div id="mapcontainer">
                  <div id="map"></div>
                </div>
            </div>
            
            -->
        </div>
        <!-- end main div -->
        
        <?php echo $this->render('footer.phtml'); //reader document footer ?>
        
    </body>
</html>    