<?php

function URIescape($uri){
    return str_replace("&", "&amp;", $uri);
}


$host = OpenContext_OCConfig::get_host_config();

define ('HOST', $host);

$auth = Zend_Auth::getInstance();
if (!$auth->hasIdentity()){
    $displayName = false;
}
else{
    $identity = $auth->getIdentity();
    $displayName = $identity->name;
}


$requestURI = $this->requestURI;
$request_array = explode('?', $requestURI, 2);
//array explode  ( string $delimiter  , string $string  [, int $limit  ] )

if (substr_compare($request_array[0], '/' , -1)) {  // if the uri doesn't end in a slash (minus query parameters), 
    $request_array[0] = $request_array[0] . '/';  // add one
}


if (isset($request_array[1])) { // if there are query parameters,
    $request_array[1] = "?" . $request_array[1];  // prepend a '?' to the set of parameters since we exploded on the '?' to get this string.
    //echo $request_array[1]; // for testing
} else {
    $request_array[1] = null;
}




$requestParams = $this->requestParams;
if(!isset($requestParams["q"])){
    
    $checkParam = $requestParams;
    unset($checkParam["page"]);
    unset($checkParam["recs"]);
    unset($checkParam["sort"]);
    
    if(count($checkParam)>3){
        $searchMessage = "Search this set of data";
    }
    else{
        $searchMessage = "Search all analytic data";
    }
    
    $full_link = $host.$requestURI;
    $full_link  = str_replace("&", "&amp;", $full_link );
    $full_link  = str_replace("&amp;amp;", "&amp;", $full_link );

    $fulltext = '';
    $fulltext .= '<input id="act_uri" type="hidden" value="'.$full_link.'" />';
    $fulltext .= '<span style="text-align:left; margin-left:2%; font-size:.75em;" >';
    $fulltext .= 'Or, type a search term in the box';
    $fulltext .= '</span><br/>';
    $fulltext .= '<div id="b_search_tab">
                    <div id="b_search_row" class="b_search">
                        <div id="b_search_cell_in" >
                                <input name="q" class="bb" type="text" id="q_string" value="Search here..."
                                onfocus="if(this.value==\'Search here...\')this.value=\'\';" onblur="if(this.value==\'\')this.value=\'Search here...\';"
                                />
                        </div>
                        <div id="b_search_cell_button">
                                <button class="bb" type="submit" onclick="textSearch();">Search</button>
                        </div>
                    </div>
                </div>
    ';
    
}
else{
    $fulltext = "";
}



$numFound = $this->numFound;
$facets = $this->facets;
$docs = $this->docs;

if(!isset($requestParams["rel"])){
    $link_filter_message = "<p>Some data in Open Context uses shared terminology systems published by experts in various fields:</p>";
    $link_filter_message .= "<ul>".chr(13);
    
    $eolLink = OpenContext_FacetOutput::generateFacetURL($requestParams, "rel", "http://purl.org/NET/biol/ns#term_hasTaxonomy", true);
    $pleiadesLink = OpenContext_FacetOutput::generateFacetURL($requestParams, "rel", "http://gawd.atlantides.org/terms/origin", true);
    
    $link_filter_message .= "<li><a href='$eolLink'>Browse Items</a> with <strong>biological taxa</strong> (from <a href='http://wwww.eol.org'>Encyclopedia of Life</a>)</li>".chr(13);
    $link_filter_message .= "<li><a href='$pleiadesLink'>Browse Items</a> linked to <strong>ancient places</strong> (from <a href='http://pleiades.stoa.org'>Pleaides</a>)</li>".chr(13);
    $link_filter_message .= "<li><a href='../about/concepts#linked-data'><em>More about Linked Data in Open Context</em></a></li>".chr(13);
    $link_filter_message .= "</ul>".chr(13);
}
else{
    $link_filter_message = "<p><a href='../about/concepts#linked-data'><em>More about Linked Data in Open Context</em></a></p>".chr(13);
}

$filter_output = OpenContext_FacetOutput::make_filters_html($requestParams, $host);


$facet_fields = $facets["facet_fields"];
$facet_queries = $facets["facet_queries"];
$extendedFacets = true; //show more available facets 


//do advanced search interface
if(substr_count($requestURI, "advanced=true")>0){
    $advanced = true;
}
else{
    $advanced = false;
}

if($numFound>0){
    $facet_output = OpenContext_FacetOutput::facets_available($extendedFacets, $facet_fields, $facet_queries, $requestParams, $request_array, $host, $advanced);
}
else{
    $facet_output = "(No results to this cquery, please try other search options)";
}



$googleURI = "";
$facetAtomURI = "";
$openSearchURI = "";


?>


<!DOCTYPE html>
<html lang="en"> 
    <head> 
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Open Context: Data Publication for Cultural Heritage and Field Research</title> 
        <link rel="shortcut icon" href="/images/layout/oc-favicon.ico" type="image/x-icon" />
        <script src="<?php echo $GMapURI; ?>" type="text/javascript"></script> 
        
        
        <link href="/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
        <link href="/css/home-rev2.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" />
        
        
        <!-- <script type="text/javascript" src="../js/timemap2/lib/jquery-1.4.4.min.js"></script> -->
        <script src="<?php echo $host; ?>/js/jquery/jquery-1.7.2.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="../js/timemap2/lib/mxn/mxn.js?(googlev3)"></script>
        <script type="text/javascript" src="http://opencontext.org/js/timemap/lib/timeline-2.3.0.js"></script>
        <script src="http://opencontext.org/js/timemap2/src/timemap.js" type="text/javascript"></script>
        <script src="http://opencontext.org/js/timemap2/src/loaders/json.js" type="text/javascript"></script>
        <script src="../js/timemap2/oc.js" type="text/javascript"></script>
        <script src="../js/timemap2/circle_icons.js" type="text/javascript"></script>
        <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-transition.js" type="text/javascript"></script>
        <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-collapse.js" type="text/javascript"></script>
        
     
        <script type="text/javascript">
            var tm;
            var timeMapURL = "<?php echo $host; ?>/maps/time-map.json";
            
            
            var numRangeThemes = 9;
            var redRange = [255,255];
            var greenRange = [200,0];
            var blueRange = [0,0];
            var alphaRange = [225,150];
            
            //calculates a new color between a range
            function rangeDiff(colorRange, themeNumber, doHex){
                var colorDif = (colorRange[1] - colorRange[0]) / numRangeThemes;
                var newColor = colorRange[0]+ (colorDif * themeNumber);
                newColor = Math.round(newColor);
                if(doHex){
                    newColor =  newColor.toString(16);
                }
                return newColor;
            }
            
            function addLegendImage(actSize, actColor, actAlpha, forthComing){
                var recCells = document.getElementById("legend-cells");
                var legCell = document.createElement("div");
                legCell.setAttribute("class", "div-cell-leg");
                var legImage = document.createElement("img");
                var imageSRC = circleURL(actSize, actColor, actAlpha);
                legImage.setAttribute("src", imageSRC);
                legCell.appendChild(legImage);
                if(!forthComing){
                    recCells.appendChild(legCell);
                }
                else{
                    var fCell = document.getElementById("forthcomingIcon");
                    fCell.appendChild(legCell);
                }
           
            }
            
            function onLoadTM() {
                // add new interval
                SimileAjax.DateTime.addInterval('TFK', 25000);
                SimileAjax.DateTime.addInterval('TFH', 250);
                SimileAjax.DateTime.addInterval('TENK', 10000);
                SimileAjax.DateTime.addInterval('FTK', 5000);
                SimileAjax.DateTime.addInterval('FHK', 500);
                SimileAjax.DateTime.addInterval('HNDK', 100000);
                
                
                var zones1 = [
                        {   
                            start:    "-250000",
                            end:      "-10000",
                            magnify:  1,
                            unit:     Timeline.DateTime.TENK
                        },
                        {   
                            start:    "-9999",
                            end:      "-4000",
                            magnify:  1,
                            unit:     Timeline.DateTime.MILLENNIUM
                        },
                        {   
                            start:    "-3999.999",
                            end:      "1000",
                            magnify:  8,
                            unit:     Timeline.DateTime.TFH
                        },

                        {   
                            start:    "1000.001",
                            end:      "2050",
                            magnify:  8,
                            unit:     Timeline.DateTime.CENTURY
                        }
                    ];
                var zones2 = [
                        {   
                            start:    "-250000",
                            end:      "-30000",
                            magnify:  3,
                            unit:     Timeline.DateTime.TFK
                        },
                        {   
                            start:    "-29999.999",
                            end:      "-10000",
                            magnify:  4,
                            unit:     Timeline.DateTime.TENK
                        },
                        {   
                            start:    "-9999.999",
                            end:      "2050",
                            magnify:  5,
                            unit:     Timeline.DateTime.FTK
                        }
                    ];
                

                var actColor = "rgb(" + redRange[0] + "," + greenRange[0] + "," + blueRange[0] + ")";
                var actAlpha = alphaRange[0].toString(16); 
                for (var awe = 1; awe <= numRangeThemes ; awe++) {
                    // Create a new theme and add it to the TimeMap.themes namespace
                    var actSize = 16 + (awe * 4);
                    TimeMap.themes["theme-size-" + awe] = TimeMapTheme.createCircleTheme({
                        size: actSize,
                        color: actColor,
                        alpha: actAlpha
                    });
                    addLegendImage(actSize, actColor, actAlpha, false);
                    actColor = "rgb(" + rangeDiff(redRange, awe, 0) + "," +rangeDiff(greenRange, awe, 0) + "," + rangeDiff(blueRange, awe, 0) + ")";
                    actAlpha = rangeDiff(alphaRange, awe, 1);
                }
               
                var fSize = 20;
                var fColor = "rgb(0,52,102)";
                var fAlpha = "ff";
                TimeMap.themes["forthcoming"] = TimeMapTheme.createCircleTheme({
                        size: fSize,
                        color: fColor,
                        alpha: fAlpha
                    });
                addLegendImage(fSize, fColor, fAlpha, true); // add forthcoming image
                
                
                tm = TimeMap.init({
                    mapId: "map",               // Id of map div element (required)
                    timelineId: "timeline",     // Id of timeline div element (required)
                    scrollTo: "-500",
                    options: {
                        dateParser: "gregorian",
                        eventIconPath: "/js/timemap2/images/"
                    },
                    datasets: [
                        {
                            title: "Open Context",
                            id: "ocData",
                            //theme: "red",
                            type: "json_string",
                            options: {
                                url: timeMapURL
                            }
                        }
                    ],
                     // need to make the bands in this verbose manner to set max/min dates
                  
                    
                        bands: [
                            Timeline.createHotZoneBandInfo({
                                eventSource:    false,
                                width:          "75%",
                                intervalUnit:   Timeline.DateTime.FHK,
                                intervalPixels: 65,
                                zones:          zones1
                            }),
                            Timeline.createHotZoneBandInfo({
                                eventSource:    false,
                                width:          "25%",
                                intervalUnit:   Timeline.DateTime.TENK,
                                intervalPixels: 85,     
                                layout:         'overview',
                                zones:          zones2
                            })
                        ]
                } );
            }
        </script>
        
      
  </head>

  <body onload="onLoadTM();" >
        
        <!-- 
            Logo,
        -->    
        <?php echo $this->render('header.phtml'); //reader document top ?>
           
        <!-- 
            Navigation tabs, search box
        -->
        <?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>
        
        
        <div id="main">
            <div id="main_content">
                <div id="intro-row">
                    <div id="intro-cell">
                        <h1>Welcome to Open Context</h1>
                        <p>Open Context reviews, edits, and publishes archaeological research data and archives data with
                        university-backed repositories, including the California Digital Library.
                        </p>
                    </div>
                    <div id="intro-cell-pict" style="vertical-align: middle; text-align: right; padding-left: 20%;">
                        <!-- <img src="../images/layout/open-context-gen-logo-med.png" alt="Open Context Logo" /> -->
                        <a href="http://alexandriaarchive.org/contribute/" title="Support innovation and open publication of cultural heritage" >
                            <button class="btn btn-success btn-large" type="button">Donate</button>
                        </a>
                        <p>Make a donation or volunteer services</p>
                    </div>
                    <!--
                    <div id="into-cellB">
                        <h5>Introduction</h5>
                    </div>
                    <div id="into-cellC">
                        <h5>How to Publish + Archive Data</h5>
                    </div>
                    <div id="into-cellD">
                        <h5>Current Data Publications</h5>
                    </div>
                    -->
                </div>
            </div>
    
    
    
            <div id="timemap">
                <div class="accordion" id="accordion2">
                    <div class="accordion-group">
                        <div class="accordion-heading">
                          <div class="div-tab">
                              <div class="div-row">
                                  <div class="div-cell">
                                        <h3 id="map-title">Content Map and
                                            <a title="Click to open + close timeline" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                                            Timeline
                                            </a>
                                        </h3>
                                  </div>
                                  <div id="proj-size">
                                        <div class="div-tab">
                                            <div class="div-row">
                                                <div id="n-recs-head">
                                                    <h5>Number of Records</h5>
                                                </div>
                                                <div class="div-cell" style="padding-left:4px; padding-right:6px;">50</div>
                                                <div id="legend-cells"></div>
                                                <div class="div-cell">150,000</div>
                                                <div id="f-outer">
                                                    <span id="forthcomingIcon"></span>(Forthcoming)
                                                </div>
                                            </div>
                                        </div>
                                  </div>
                              </div>
                          </div>
                        </div>
                        <div id="collapseOne" class="accordion-body collapse">
                          <div class="accordion-inner">
                              
                              <div id="timelinecontainer">
                                  <div id="timeline"></div>
                              </div>
                              
                          </div>
                        </div>
                        
                        <div id="mapcontainer">
                            <div id="map"></div>
                        </div>
                        
                        <div id="time-map-credit">
		Timeline and mapping credit: <a href="http://code.google.com/p/timemap/" title="Project home and source code">Timemap.js</a>
      library by <a href="http://www.nickrabinowitz.com/" title="Project lead">Nick Rabinowitz</a>
      using <a href="http://www.simile-widgets.org/timeline/" title="Timeline home and source code">Timeline</a>
      by the <a href="http://simile.mit.edu/" title="SIMILIE Project Home">SIMILE Project</a>
	    </div>

                        
                    </div>
                    
                    
                    
                </div>
                
                
                
            </div>
    
    
            <!--
    
            <div id="timemap">
                <div id="timelinecontainer">
                  <div id="timeline"></div>
                </div>
                <div id="mapcontainer">
                  <div id="map"></div>
                </div>
            </div>
            
            -->
        </div>
        <!-- end main div -->
        
        <?php echo $this->render('footer.phtml'); //reader document footer ?>
        
    </body>
</html>    