<?php

$GMapURI = OpenContext_OCConfig::get_google_api();
$GMapURI = "http://maps.google.com/maps?file=api&v=2&key=".$GMapURI;
$KML_url = OpenContext_OCConfig::get_host_config();
$KML_url = "/sets/facets/.kml";
$host = OpenContext_OCConfig::get_host_config();
$OAI_url = $host."/oai/request";
$lastUpdate = date("F j, Y, g:i a", strtotime(OpenContext_OCConfig::last_update()));

?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
      <title>Open Context (Home)</title> 
      <link href="/css/opencontext_style.css" rel="stylesheet" type="text/css" /> 
      <link href="/css/test_landing_page.css" rel="stylesheet" type="text/css" />
      <link href="/css/default_banner.css" rel="stylesheet" type="text/css" />
        
      <script src="<?php echo $GMapURI; ?>" type="text/javascript"></script> 
      <script type="text/javascript" src="http://simile.mit.edu/timeline/api/timeline-api.js"></script> 
      <script src="/js/timemap/timemap.js" type="text/javascript"></script> 
      <script src="/js/timemap/kmlparser.js" type="text/javascript"></script> 
      <script type="text/javascript"> 
 
function onLoad() {
    TimeMap.init({
        mapId: "map",               // Id of map div element (required)
        timelineId: "timeline",     // Id of timeline div element (required)
        datasets: [
            {
                title: "Open Context",
                theme: TimeMapDataset.redTheme({eventIconPath: '/images/timemap/'}),
                data: {
                    type: "kml",     // Data to be loaded in KML - must be a local URL
                    url: "<?php echo $KML_url; ?>" // KML file to load
                }
            }
        ],
        bandInfo: [
            {
              width:          "50%",
              intervalUnit:   Timeline.DateTime.CENTURY,
              intervalPixels: 100
            },
            {
               width:          "50%",
               intervalUnit:   Timeline.DateTime.MILLENNIUM,
           intervalPixels: 65,
               showEventText:  true,
               trackHeight:    0.4,
               trackGap:       0.2
            }
        ]
    });
}
    </script> 
  <link href="/css/timemap.css" type="text/css" rel="stylesheet"/> 
    <style> 
    div#timelinecontainer{ height: 210px; }
    div#mapcontainer{ height: 400px; }
    </style> 
        
        
        
        
    </head>
<body onload="onLoad();" onunload="GUnload();">
  <div id="oc_logo">
	<img alt="Open Context Logo" src="/images/general/oc_logo.jpg" border="0" ></img>
    </div>
    <div id="oc_tagline">
	<img alt="Open Context Tagline" src="/images/general/oc_tagline.jpg" ></img>
    </div>
    <div id="oc_beta">
	<img alt="Beta Stamp" src="/images/general/oc_betastamp.jpg" ></img>
    </div>
    
    <div id="oc_main_nav">
        <div class="sides"></div>
        <div class="n_act_nav"><a href="../about" title="Learn more about Open Context">About</a></div>
        <div class="sides"></div>
        <div class="n_act_nav"><a href="../projects/" title="Summary of datasets in Open Context">Projects</a></div>
        <div class="sides"></div>
        <div class="n_act_nav"><a href="../sets/" title="Explore data">Browse</a></div>
        <div class="sides"></div>
        <div class="n_act_nav"><a href="../lightbox/" title="Browse images">Lightbox</a></div>
        <div class="sides"></div>
        <div class="n_act_nav"><span title="Coming soon">Tables</span></div>
        <div class="sides"></div>
        <div class="n_act_nav"><span title="Browse to get details of items">Details</span></div>
        <div class="sides"></div>
        <div class="n_act_nav"><span title="Coming soon">My Account</span></div>
    </div>
    
    
    <div id="main">
    <br/>
    <p class="subHeader" align="center">Welcome to Open Context!</p>
    <div id="left">
    
    <p class="bodyText">Use Open Context to explore, obtain, and publish primary data and documentation collected in the field sciences, especially
    archaeology. While all contributions are evaluated by a credentialed editorial staff prior to publication,
    most content represents "field notes" and "raw data", and will likely contain typographic and other errors. So please use with discretion.</p>
    <p class="bodyText">Open Context is in the process of major upgrades and enhancements to offer new features and capabilities. Please check back often!</p>
    <p class="bodyText">Content last updated: <br/><em><?php echo $lastUpdate ?></em></p>
    <p class="bodyText"><a href="http://opencontext.org/projects/">Explore Open Context</a></p>
    <p class="bodyText"><a href="http://opencontext.org/about/services">About New Web Services</a></p>
    <p class="bodyText"><a href="http://ux.opencontext.org/blog/about/">Blog Discussion</a></p>
    
    </div>
    
    <div id="right">
    
    <img src="http://farm1.static.flickr.com/119/296367267_b035d8f908.jpg?v=0" />
 
    <p class="tinyText">Image by Jeff Kubina <a href="http://www.flickr.com/photos/kubina/296367267/">via Flickr</a> (CC-by license)</p>
    
    
    <!--
      <div id="timemap"> 
          <div id="timelinecontainer"> 
            <div id="timeline"></div> 
          </div>
          <br/>
          <div id="mapcontainer"> 
            <div id="map"></div> 
          </div> 
      </div> 
    -->
    
    <br/>
    <br/>
    
    </div>
    
    <div style='clear:both;'>
      
      <div style='float:left; width:75%; margin-right:5px;'>
        <p class='tinyText' style='text-align:right;'>Open Context is a registered Open Archives Initiative - Protocol for Metadata Harvesting (<a href='http://www.openarchives.org/'>OAI-PMH</a>) Ver. 2.0 Data Provider</p>
        <p class='tinyText' style='text-align:right;'><a href='<?php echo $OAI_url; ?>' title='Link to OAI-PMH metadata service'>Link to the Open Context OAI-PMH Service</a></p>
      </div>
      <div style='float:right; width:20%; padding-bottom:5px;'>
        <a href='http://www.openarchives.org/' title='Learn more about OAI-PMH'>
          <img border='0' src='http://www.openarchives.org/images/OA100.gif' alt='OAI-PMH Logo'/>
        </a>
      </div>
      
    </div>
    
    <div id="bottom">
      <!--
      <div style='float:left; width:70%; margin-right:10px;'>
        <p class='tinyText'>Open Context is an Open Archives Initiative - Protocol for Metadata Harvesting (OAI-PMH) Ver. 2.0 Data Provider</p>
        <p class='tinyText'><a href='<?php echo $OAI_url; ?>'>Link to OAI-PMH Service</a></p>
      </div>
      <div style='float:right; width:20%;'>
        <a href='<?php echo $OAI_url; ?>'><img src='http://www.openarchives.org/images/OA100.gif' alt='OAI-PMH Logo'></a>
      </div>
    -->
    </div>
    
    </div>

    
</body>
</html>
