<?php

// used to help create hyperlinks; set to current hostname.
//$host = "http://ishmael.ischool.berkeley.edu";
//$host = "http://opencontext";
$host = OpenContext_OCConfig::get_host_config();
$GMapURI = OpenContext_OCConfig::get_google_api();
$GMapURI = "http://maps.google.com/maps?file=api&amp;v=2&amp;key=".$GMapURI;
$OAI_url = $host."/oai/request";
$lastUpdate = date("F j, Y, g:i a", strtotime(OpenContext_OCConfig::last_update()));


?>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title><?php echo 'Open Context: Data Publication for Cultural Heritage and Field Research'; ?></title> 
        <link href="/components/css/home" type="text/css" rel="stylesheet"/>
        <link rel="shortcut icon" href="/images/general/oc_favicon.ico" type="image/x-icon" />
        <script src="<?php echo $GMapURI; ?>" type="text/javascript"></script> 
        <!--
        <script type="text/javascript">
            Timeline_ajax_url='http://static.alexandriaarchive.org/js/timeline/timeline_ajax/simile-ajax-api.js';
            Timeline_urlPrefix='http://static.alexandriaarchive.org/js/timeline/timeline_js/';
            Timeline_parameters='bundle=true';
        </script>
        -->
        
        <!--
        <script type="text/javascript" src="http://static.simile.mit.edu/timeline/api-2.3.0/timeline-api.js"></script>
        -->
        
        
        <script type="text/javascript" src="http://static.alexandriaarchive.org/js/timemap/lib/timeline-2.3.0.js"></script>
        
        
        
        <script type="text/javascript">
            var tm;
            var timeMapURL = "<?php echo $host; ?>/map/start/.json";
            
            function onLoadTM() {
                // add new interval
                SimileAjax.DateTime.addInterval('TFK', 25000);
                SimileAjax.DateTime.addInterval('TFH', 250);
                SimileAjax.DateTime.addInterval('TENK', 10000);
                SimileAjax.DateTime.addInterval('FTK', 5000);
                SimileAjax.DateTime.addInterval('FHK', 500);
                SimileAjax.DateTime.addInterval('HNDK', 100000);
                
                var zones1 = [
                        {   
                            start:    "-250000",
                            end:      "-10000",
                            magnify:  1,
                            unit:     Timeline.DateTime.TENK
                        },
                        {   
                            start:    "-9999",
                            end:      "-4000",
                            magnify:  1,
                            unit:     Timeline.DateTime.MILLENNIUM
                        },
                        {   
                            start:    "-3999.999",
                            end:      "1000",
                            magnify:  8,
                            unit:     Timeline.DateTime.TFH
                        },

                        {   
                            start:    "1000.001",
                            end:      "2050",
                            magnify:  8,
                            unit:     Timeline.DateTime.CENTURY
                        }
                    ];
                var zones2 = [
                        {   
                            start:    "-250000",
                            end:      "-30000",
                            magnify:  3,
                            unit:     Timeline.DateTime.TFK
                        },
                        {   
                            start:    "-29999.999",
                            end:      "-10000",
                            magnify:  4,
                            unit:     Timeline.DateTime.TENK
                        },
                        {   
                            start:    "-9999.999",
                            end:      "2050",
                            magnify:  5,
                            unit:     Timeline.DateTime.FTK
                        }
                    ];
                
                
                tm = TimeMap.init({
                    mapId: "map",               // Id of map div element (required)
                    timelineId: "timeline",     // Id of timeline div element (required)
                    scrollTo: "-500",
                    options: {
                        dateParser: "gregorian",
                        eventIconPath: "/js/timemap/images/"
                    },
                    datasets: [
                        {
                            title: "Open Context",
                            id: "ocData",
                            theme: "red",
                            type: "json_string",
                            options: {
                                url: timeMapURL
                            }
                        }
                    ],
                     // need to make the bands in this verbose manner to set max/min dates
                  
                    
                        bands: [
                            Timeline.createHotZoneBandInfo({
                                eventSource:    false,
                                width:          "75%",
                                intervalUnit:   Timeline.DateTime.FHK,
                                intervalPixels: 65,
                                zones:          zones1
                            }),
                            Timeline.createHotZoneBandInfo({
                                eventSource:    false,
                                width:          "25%",
                                intervalUnit:   Timeline.DateTime.TENK,
                                intervalPixels: 85,     
                                layout:         'overview',
                                zones:          zones2
                            })
                        ]
                } );
            }
        </script>
        <!--
	<script src="http://static.alexandriaarchive.org/js/timeline/timeline_js/timeline-api.js" type="text/javascript"></script>
        -->
        
        <script src="components/js/home" type="text/javascript"></script>
  </head>

  <body onload="onLoadTM();" onunload="GUnload();">     
    <div id="oc_logo">
	<a href="<?php echo $host;?>" title="Open Context (Home)"><img alt="Open Context Logo" src="http://static.alexandriaarchive.org/images/general/oc_logo.jpg" border="0" /></a>
    </div>
    <div id="oc_tagline">
	<img alt="Open Context Tagline" src="http://static.alexandriaarchive.org/images/general/oc_tagline.jpg" />
    </div>
    <div id="oc_beta">
	<img alt="Beta Stamp" src="http://static.alexandriaarchive.org/images/general/oc_betastamp.jpg" />
    </div>
   
   <div id="oc_top_search">
	<form method="get" action="<?php echo $host;?>/search/" id="search-form">
	<div id="search_box">
	<input type='text' name='q' class='tinyText' value='Search' size='30' onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';" />
	</div>
	<div id="search_cntrl">
	    <input class="oc_top_sbutton" type="submit" value="" />
	</div>
	</form>
    </div>
   
   
   <!-- 
    Navigation tabs
    -->    
    <?php echo OpenContext_NavMenus::GeneralNavMenu("index"); ?>
        
	
<!--
BEGIN Container for main page content
--> 
    <div id="main_page" > 
        <!--Begin code for showing available facets-->
        <div id="main_content">
            
	    <div id="welcome_box">
		<div class="pageHeader" id="welcome_main">Welcome to<br/>Open Context</div>
		<div id='welcome_text_box'>
		    <p class="bodyText" id="welcome_text">Use Open Context to discover, reference, and publish primary data and documentation collected in archaeology and other field sciences by professional researchers. <em style="color:#8B2323;" title="Drag / scroll through the timeline and sites will come and go on the map">Scroll</em> through the timeline and map below to begin exploring data, images, reports and field documentation.</p>
		</div>
		<div style="position: relative; clear:both; width:700px;"></div>
	    </div>
	    
	    <div id="timemap">
                <div id="timelinecontainer">
                  <div id="timeline"></div>
                </div>
                <div id="mapcontainer">
                  <div id="map"></div>
                </div>
            </div>
            
            
	    <div style='text-align:right; margin-right:14px; color:#666666; margin-top:20px; height:30px;' class='tinyText'>
		Timeline and mapping credit: <a href='http://code.google.com/p/timemap/' title='Project home and source code' style='color:#8B3E2F;'>Timemap.js</a> library by <a href='http://www.nickrabinowitz.com/' title='Project lead' style='color:#8B3E2F;'>Nick Rabinowitz</a> using <a href='http://www.simile-widgets.org/timeline/' title='Timeline home and source code' style='color:#8B3E2F;'>Timeline</a> by the <a href='http://simile.mit.edu/' title='SIMILIE Project Home' style='color:#8B3E2F;'>SIMILE Project</a>
	    </div>

	    <div style='text-align:right; margin-right:14px; margin-top:5px;'>
		<p class="bodyText" style="color:#666666; ">Content last updated: <br/><em><?php echo $lastUpdate ?></em></p>
	    </div>
   
        <!--
        END of div container for placing main page content
        -->
        <div id="bottom_cont"> 
          <br /> 
          <br /> 
        </div> 
        <!--
        END Code for showing the database-like content
        -->
   
     </div>
    <br />
    
        <div id="footer"> 
            <div id="w3c_val_logo"> 
              <a href="http://validator.w3.org/check?uri=referer"> 
                <img src="http://www.w3.org/Icons/valid-xhtml10-blue" alt="Valid XHTML 1.0 Transitional" height="31" width="88" /> 
              </a> 
            </div>     
        </div>
   
     </div>
    </body>
</html>    