<?php
$host = OpenContext_OCConfig::get_host_config();
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
      <title>Open Context: Registration Confirmation Success</title> 
      <link href="/css/opencontext_style.css" rel="stylesheet" type="text/css" /> 
      <link href="/css/test_landing_page.css" rel="stylesheet" type="text/css" />
      <link href="/css/default_banner.css" rel="stylesheet" type="text/css" />
      <link href="/css/rounded_corners.css" rel="stylesheet" type="text/css" />
      <link rel="shortcut icon" href="/images/general/oc_favicon.ico" type="image/x-icon" />
      
      <style type="text/css">
      dl {
	margin-bottom:50px;
	}
	
	dl dt {
		float:left;
		font-weight:bold;
		margin-right:10px;
		margin-top:10px;
		padding:5px;
		width:100px;
	}
	
	dl dd {
		margin:2px 0;
		padding:10px 0;
		text-align: right;
		display: table-cell;
		vertical-align: top;
		line-height:95%;
	}
	#registerUser {
	    margin-left: 60%;
	}
	dl.zend_form{
	    margin-left:30px;
	    width: 50%;
	    background-color:#fffdbe;
	    border-width: thin;
	    border-style: solid;
	    border-color: #D7D7D7;
	    padding:10px;
	}
	dl.zend_form dd ul.errors {
	    list-style: none;
	    padding: 0;
	    margin: 0;
	}
	dl.zend_form dd ul.errors li {
	    float: right;
	    padding-bottom: 5px;
	    font-style:italic;
	    font-size: 12px;
	    color: #666666;
	}
      </style>
      
    </head>
    
<body>
  <div id="oc_logo">
	<a href="<?php echo $host; ?>" title="Open Context (Home)"><img alt="Open Context Logo" src="/images/general/oc_logo.jpg" border="0" ></img></a>
    </div>
    <div id="oc_tagline">
	<img alt="Open Context Tagline" src="/images/general/oc_tagline.jpg" ></img>
    </div>
    <div id="oc_beta">
	<img alt="Beta Stamp" src="/images/general/oc_betastamp.jpg" ></img>
    </div>
    
    <div id="oc_top_search">
	<form method="get" action="<?php echo $host;?>/search/" id="search-form">
	<div id="search_box">
	<input type='text' name='q' class='tinyText' value='Search' size='30' onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';" />
	</div>
	<div id="search_cntrl">
	    <input class="oc_top_sbutton" type="submit" value="" />
	</div>
	</form>
    </div>
   
   
   <!-- 
    Navigation tabs
    -->    
    <?php echo OpenContext_NavMenus::GeneralNavMenu("accounts"); ?>
    
    <div id="main">
	<div id="pageTop">
            <div id="pageIntro">
                <p class="pageName" align="center">Your Open Context User Registration is Complete</p>
                
                <div style="margin:10px;">
                    <p class="bodyText">Thank you <strong><?php echo $this->name; ?></strong>! You have successfully completed the Open Context user registration process. You may now login to your user account by completing the form below.</p>
		    <br/>
		    
		</div>
		
		<div style="margin:10px;" class="bodyText">
		    <form action="<?php echo $this->baseUrl ?>/auth/login" method="post">
			<div style="width:80%; text-align:right; padding:10px;">
			    <label style="padding:10px;" for="username">Username (email address)</label>
			    <input type="text" name="username" value=""/>
			</div>
			<div style="width:80%; text-align:right; padding:10px;">
			    <label style="padding:10px;" for="password">Password</label>
			    <input type="password" name="password" value=""/>
			</div>
			<div id="formbutton">
			<div style="width:80%; text-align:right;"><input type="submit" name="login" value="Login" /></div>
			</div>
		    </form>
		    
		</div>
            </div>
            <div id="about_submenu" style="background-color:#EDEDED;" class="rounded-corners">
                    <p class="subHeader">Why Have an Open Context User Account?</p>
                    <p class="bodyText">While no login is required to use or download existing data tables,
                    user accounts let you make your own custom selections of data for download.</p>
            </div>
            <div id="pageTopEnd">
                <br/>
            </div>
        </div>
        
        
        <br/>
	
	<div id="bottom">
	</div>
	
    </div>

</body>
</html>
