<?php

// used to help create hyperlinks; set to current hostname.
$host = OpenContext_OCConfig::get_host_config();

define ('HOST', $host);

$auth = Zend_Auth::getInstance();
if (!$auth->hasIdentity()){
    $displayName = false;
}
else{
    $identity = $auth->getIdentity();
    $displayName = $identity->name;
}

$requestURI = $this->requestURI;
$request_array = explode('?', $requestURI, 2);
//array explode  ( string $delimiter  , string $string  [, int $limit  ] )

if (substr_compare($request_array[0], '/' , -1)) {  // if the uri doesn't end in a slash (minus query parameters), 
    $request_array[0] = $request_array[0] . '/';  // add one
}


if (isset($request_array[1])) { // if there are query parameters,
    $request_array[1] = "?" . $request_array[1];  // prepend a '?' to the set of parameters since we exploded on the '?' to get this string. 
    //echo $request_array[1]; // for testing
} else {
    $request_array[1] = null;
}
$requestParams = $this->requestParams;


$numFound = $this->numFound;
$facets = $this->facets;
$docs = $this->docs;



$filter_message = "(View is not filtered)";
$filter_output = $filter_message;
$filter_output = OpenContext_FacetOutput::make_filters_html($requestParams, $host);

$facet_fields = $facets["facet_fields"];
$facet_queries = $facets["facet_queries"];
$extendedFacets = true; //show more available facets 


//do advanced search interface
if(substr_count($requestURI, "advanced=true")>0){
    $advanced = true;
}
else{
    $advanced = false;
}


$facet_output = OpenContext_FacetOutput::facets_available($extendedFacets, $facet_fields, $facet_queries, $requestParams, $request_array, $host, $advanced);




$googleURI = "";
$facetAtomURI = "";
$openSearchURI = "";

$GoogleAPIkey = OpenContext_OCConfig::get_google_api();



$requestParams = $this->requestParams;
if(!isset($requestParams["q"])){
    
    $checkParam = $requestParams;
    unset($checkParam["page"]);
    unset($checkParam["recs"]);
    unset($checkParam["sort"]);
    
    if(count($checkParam)>3){
        $searchMessage = "Search this set of tables";
    }
    else{
        $searchMessage = "Search all tables";
    }
    
    $full_link = $host.$requestURI;
    $full_link  = str_replace("&", "&amp;", $full_link );
    $full_link  = str_replace("&amp;amp;", "&amp;", $full_link );

    $fulltext = '';
    $fulltext .= '<input id="act_uri" type="hidden" value="'.$full_link.'" />';
    $fulltext .= '<span style="text-align:left; margin-left:2%; font-size:.75em;" >';
    $fulltext .= 'Or, type a search term in the box';
    $fulltext .= '</span><br/>';
    $fulltext .= '<div id="b_search_tab">
                    <div id="b_search_row" class="b_search">
                        <div id="b_search_cell_in" >
                                <input name="q" class="bb" type="text" id="q_string" placeholder="Search here..." />
                        </div>
                        <div id="b_search_cell_button">
                                <button class="bb" type="submit" onclick="textSearch();">Search</button>
                        </div>
                    </div>
                </div>
    ';
}
else{
    $fulltext = "";
}


?>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
        <title><?php echo 'Open Context Search: ('.$numFound.' Items Showing)'; ?></title>
        <link rel="shortcut icon" href="/images/general/oc_favicon.ico" type="image/x-icon" />
        
        <!--
        <link href="<?php echo $host; ?>/components/css/browse" rel="stylesheet" type="text/css" /> 
        -->
        <link href="<?php echo $host; ?>/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" /> 
        <link href="<?php echo $host; ?>/css/opencontext-browse-rev2.css" rel="stylesheet" type="text/css" />
        
        <link rel="alternate" type="application/atom+xml" title="Atom facet feed" href="<?php echo $this->facetURI_Atom; ?>" />
        <link rel="alternate" type="application/atom+xml" title="Atom feed of results" href="<?php echo $this->currentAtom; ?>" />
        
        <link rel="first" type="application/atom+xml" title="Atom feed of results" href="<?php echo $this->firstPage_XHTML; ?>" />
        <?php
            if($this->prevPage_XHTML != false){
                echo '<link rel="prev" type="application/atom+xml" title="Atom feed of results" href="'.$this->prevPage_XHTML.'" />'.chr(13);
            }
            if($this->nextPage_XHTML != false){
                echo '<link rel="next" type="application/atom+xml" title="Atom feed of results" href="'.$this->nextPage_XHTML.'" />'.chr(13);
            }
        ?>
        
        <link rel="last" type="application/atom+xml" title="Atom feed of results" href="<?php echo $this->lastPage_XHTML; ?>" />
        <link rel="search" type="application/opensearchdescription+xml" href="<?php echo $host."/search/search/.xml"; ?>" title="Open Context Open Search Service" />
        <script src="../js/advance_browse/advance_browse.js" type="text/javascript"></script>
        <script src="https://www.google.com/jsapi?key=<?php echo $GoogleAPIkey; ?>" type="text/javascript"></script>
        
        <style type="text/css">
        
            div.controlCell {
                display:table-cell; text-align:center; vertical-align:middle;
            }
            div.resultCell {
                display: table-cell;
                text-align: left;
                padding-left: 4px;
                padding-right: 4px;
                padding-top:8px;
                padding-bottom:12px;
            }
            
            div.colorRow {
                display:table-row;
                background-color: #fffdbe;
            }
            div.whiteRow {
                display:table-row;
            }
            
            .highlight
            {
            background: #CEDAEB;
            color: #000000;
            }
            
            .highlight_important
            {
            background: #F8DCB8;
            color: #000000;
            }
            .snippet
            {
            color: #707070;
            }
            
        
        </style>
        
        
        <script type="text/javascript">
        <!--
        
        <?php
        
        echo "var baseURI = '".$host.$requestURI."'; \n";
        echo "var contextBase = '".$host.$request_array[0]."'; \n";
        echo "var paramterBase = '".$request_array[1]."'; \n";
        
        if(isset($requestParams["q"])){
            //echo "var OSfeedURI = 'http://opencontext.org/sets/.atom?q=".urlencode($requestParams["q"])."'; \n";
            echo "var OSfeedURI = 'http://core.tdar.org/search/rss?query=".urlencode($requestParams["q"])."'; \n";
        }
        else{
            echo "var OSfeedURI = false; \n";
        }
        
        echo chr(13).chr(13);
        
        $activeTaxaValue = OpenContext_FacetOutput::active_taxon_value($requestParams); //for local taxonomies
        echo "var activeTaxaValue = '".$activeTaxaValue."'; \n";
        
        echo chr(13);
        $activeRelationValue = OpenContext_FacetOutput::active_taxon_value($requestParams, false); //for linked data relations
        echo "var activeRelationValue = '".$activeRelationValue."'; \n";
        
        ?>
        
        -->
        </script>
        
        <script type="text/javascript">
        <!--
            
            window.onload = function(){
               ConvertRowsToLinks("item_list_tab");
               //AddRowLinks();
             }
             
             function ConvertRowsToLinks(xTableId){
                   convertRows(xTableId, "item_row");
                   convertRows(xTableId, "item_row_shade");
             }
       
       
             function convertRows(xTableId, rowClass){
               var rows = document.getElementById(xTableId).getElementsByClassName(rowClass);
               for(i=0; i < rows.length; i++){
                 var link = rows[i].getElementsByTagName("a")
                 if(link.length >= 1){
                   rows[i].onclick = new Function("document.location.href='" + link[0].href + "'");
                   rows[i].onmouseover = new Function("this.style.cursor = 'pointer'");
                   rows[i].onmouseout = new Function("this.style.cursor = 'default'");
                 }
               }
             }
      
      
      function openList(listId){
            var displayControl = listId + "control";
            var displayStatus = document.getElementById(listId).style.display;
            if( displayStatus == "none"){
                document.getElementById(listId).style.display = "";
                document.getElementById(displayControl).innerHTML = "<em>(Hide list below)</em>";
            }
            else{
                document.getElementById(listId).style.display = "none";
                document.getElementById(displayControl).innerHTML = "More...";
            }
      
      }



        google.load("feeds", "1");

    function initialize() {
        /*
        if(OSfeedURI != false){
            var feed = new google.feeds.Feed(OSfeedURI);
            //feed.setResultFormat(google.feeds.Feed.XML_FORMAT);
            feed.setResultFormat(google.feeds.Feed.MIXED_FORMAT);
            
            feed.load(function(result) {
              if (!result.error) {
                var OSnamespace = "http://a9.com/-/spec/opensearchrss/1.0/";
                var AtomNamespace = "http://www.w3.org/2005/Atom";
                
                var feedNode = result.xmlDocument.getElementsByTagNameNS(AtomNamespace, "feed");
                //alert(feedNode.length);
                
                var osCountResult = result.xmlDocument.getElementsByTagNameNS("*", "totalResults");
                //alert(osCountResult[0].textContent);
                
                var countContainer = document.getElementById("osCount");
                countContainer.appendChild(document.createTextNode("(First " + result.feed.entries.length + " of "+ osCountResult[0].textContent + ")"));
                
                var container = document.getElementById("feed"); 
                for (var i = 0; i < result.feed.entries.length; i++) {
                  var entry = result.feed.entries[i];
                  var div = document.createElement("div");
		  var alink = document.createElement("a");
                  alink.appendChild(document.createTextNode(entry.title));
		  alink.setAttribute('href', entry.link);
		  div.appendChild(alink);
                  container.appendChild(div);
                }
              }
            });
        }
        */
    }
    google.setOnLoadCallback(initialize);



      -->
        </script>
    </head>
    <body>
        
        <!-- 
            Logo,
        -->    
        <?php echo $this->render('header.phtml'); //reader document top ?>
           
        <!-- 
            Navigation tabs, search box
        -->
        <?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>

        <div id="main"> 
            <div id="main_content">
                <div id="main_row">
                    <div id="left_cont">
                        <div id="filter_options">
                            <h3>Downloadable Data Tables</h3>
                            <p>Click on one of the links below to filter the list of data tables.</p>
                            <div id="search_sort_block">
                            <?php echo  $fulltext; ?>
                            
                            <!-- facet sorting options -->
                            <?php
                            
                            $SortOptionsObj = New SortOptions;
                            $SortOptionsObj->requestParams = $requestParams;
                            echo $SortOptionsObj->makeFacetSortLinks();
                            
                            ?>
                            </div>
                        </div>
                        <div id="all_facets">
                            <?php echo $facet_output; ?>
                        </div>
                    </div> <!--End left content col cell -->
                    <div id="right_cont">
                        <div id="selected_filters" >
                            <p>Open Context has <strong><?php echo $numFound; ?></strong> tables, filtered by the following criteria:</p>
                            <p style="text-align:right;">Last Updated: <em><?php echo date("F j, Y, g:i a", strtotime($this->lastUpdate)); ?></em></p>
                            <br/>
                    
                            <p style="text-align:left;"><strong>Note: </strong>This page lists tables you can download as CSV (comma separated value) files for use in spreadsheet or database applications. However, not all Open Context analytic data are found in these tables. For comprehensive search and queries of analytic data click the <a href="../sets/">browse tab</a> above. To browse images, click the <a href="../lightbox/">lightbox</a> tab above.</p>
                
                        </div>
                        <div id="item_list_outer">
                        
                            <div id="paging_outer">
                                <div id="paging_tab">
                                    <div id="paging_row">
                                        <div class="paging_cell">
                                            <?php
                                            
                                            if($this->firstPage_XHTML && $this->firstPage_XHTML != $this->currentXHTML){
                                                $linkClass = "pager_active";
                                                $pageLink = "<a href=\"".$this->firstPage_XHTML."\" class=\"btn btn-small btn-primary\" title=\"Go to the first page of results\" >|&larr;</a>";
                                            }
                                            else{
                                                $linkClass = "pager_inactive";
                                                $pageLink = "|&larr;";
                                                $pageLink = "<a href=\"\" class=\"btn btn-small btn-primary disabled\">|&larr;</a>";
                                            }
                                            
                                            ?>
                                            <div class="<?php echo $linkClass; ?>" >
                                                <?php echo $pageLink; ?>
                                            </div>
                                        </div>
                                        <div class="paging_cell">
                                            <?php
                                            
                                            if($this->prevPage_XHTML){
                                                $linkClass = "pager_active";
                                                $pageLink = "<a href=\"".$this->prevPage_XHTML."\" class=\"btn btn-small btn-primary\" title=\"Go to the previous page of results\" >&larr;</a>";
                                            }
                                            else{
                                                $linkClass = "pager_inactive";
                                                $pageLink = "&larr;";
                                                $pageLink = "<a href=\"\" class=\"btn btn-small btn-primary disabled\">&larr;</a>";
                                            }
                                            
                                            ?>
                                            <div class="<?php echo $linkClass; ?>" >
                                                <?php echo $pageLink; ?>
                                            </div>
                                        </div>
                                        <div id="paging_cell_center">
                                            <div id="paging_ct_tab">
                                                <div id="paging_ct_row">
                                                    <div id="paging_ct_cell_pageNum">
                                                        <?php
                                                            if(isset($requestParams["page"])){
                                                                $page = $requestParams["page"];
                                                            }
                                                            else{
                                                                $page = 1;
                                                            }
                                                            
                                                            $numRecs = $this->number_recs;
                                                            $lastPage = intval($this->numFound/$numRecs);
                                                            if($lastPage * $numRecs < $numFound){
                                                                $lastPage++;
                                                            }
                                                            echo "Page $page of $lastPage";
                                                            echo ", sorted by ".$this->sorting;
                                                        ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <!-- Add result sort options -->
                                            <?php echo $SortOptionsObj->makeSortLinks("Label / name"); ?>
                                        </div>
                                        <div class="paging_cell">
                                            <?php
                                            
                                            if($this->nextPage_XHTML){
                                                $linkClass = "pager_active";
                                                $pageLink = "<a href=\"".$this->nextPage_XHTML."\" class=\"btn btn-small btn-primary\" title=\"Go to the next page of results\" >&rarr;</a>";
                                            }
                                            else{
                                                $linkClass = "pager_inactive";
                                                $pageLink = "&rarr;";
                                                $pageLink = "<a href=\"\" class=\"btn btn-small btn-primary disabled\">&rarr;</a>";
                                            }
                                            
                                            ?>
                                            <div class="<?php echo $linkClass; ?>" >
                                                <?php echo $pageLink; ?>
                                            </div>
                                        </div>
                                        <div class="paging_cell">
                                            <?php
                                            
                                            if($this->lastPage_XHTML && $this->lastPage_XHTML != $this->currentXHTML){
                                                $linkClass = "pager_active";
                                                $pageLink = "<a href=\"".$this->lastPage_XHTML."\" title=\"Go to the last page of results\" class=\"btn btn-small btn-primary\" >&rarr;|</a>";
                                            }
                                            else{
                                                $linkClass = "pager_inactive";
                                                $pageLink = "&rarr;|";
                                                $pageLink = "<a href=\"\" class=\"btn btn-small btn-primary disabled\">&rarr;|</a>";
                                            }
                                            ?>
                                            <div class="<?php echo $linkClass; ?>" >
                                                <?php echo $pageLink; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>   
                            </div> <!--End paging outer -->
                            
                            <div id="item_list_tab">
                                <?php 
                                if(count($docs)>0){
                                
                                    $il = 0;
                                    foreach($docs as $doc){
                                        if($il & 1){
                                            $rowClass = "item_row_shade";
                                        }
                                        else{
                                            $rowClass = "item_row";
                                        }
                                        $il++;
                                        
                                ?>
                                    <div class="<?php echo $rowClass; ?>" id="item_row_<?php echo $il; ?>">
                                        <div class="item_cell_cl_icon">
                                            <a href="<?php echo $doc["href"]; ?>" ><img src="<?php echo OpenContext_ProjectAtomJson::class_icon_lookup($doc["item_class"]); ?>" alt="<?php echo $doc["item_class"]; ?>" /></a>
                                        </div>
                                        <div class="search_doc_cell">
                                            <strong>Item Label: </strong><br/>
                                            <a href="<?php echo $doc["href"]; ?>"><?php echo str_replace("_", " ", $doc["item_label"]); ?></a>
                                        </div>
                                        <div class="search_doc_cell">
                                            <strong>Project: </strong><br/>
                                            <?php echo $doc["project_name"]; ?>
                                        </div>
                                        <div class="search_doc_cell">
                                            <strong>Table Description: </strong>
                                            <?php
    
                                            $itemUUID = $doc["uuid"];
                                            if($doc["item_type"] == "table"){
                                                $itemObj = New Table;
                                                $itemObj->getByID($itemUUID);
                                                $metadataString = $itemObj->metadata;
                                                $metadata = Zend_Json::decode($metadataString);
                                                $string = "<div>".$metadata["meta"]["table_description"]."</div>";
                                                unset($metadata);
                                                unset($metadataString);
                                            }
                                            
                                            
                                            $termHighlight = new termHighlight;
                                            $termHighlight->xmlString = $string;
                                            $termHighlight->addMarkup = true;
                                            if(isset($requestParams['q'])){
                                                $termHighlight->searchString = $requestParams['q'];
                                            }
                                            $termHighlight->XMLsnippet();
                                            $termHighlight->generateSnippet();
                                            echo "<div class='snippet'>...".$termHighlight->snippet."...</div>";
                                            
                                        ?>
                                        </div>
                                    </div>
                                <?php
                                    }//end loop through docs
                                }//end case with results
                                ?>
                            </div> <!--End item list tab -->
                        </div>
                    </div> <!--End right content col cell -->
                </div> <!--End main content row -->
            </div> <!--End main content tab -->
        </div> <!-- End main id -->
        
        <div id="bottomBuffer">

        </div>
        <?php echo $this->render('footer.phtml'); //reader document footer ?>
    </body>
</html>    