<?php
// used to help create hyperlinks; set to current hostname.

function URIescape($uri){
    return str_replace("&", "&amp;", $uri);
}


$host = OpenContext_OCConfig::get_host_config();

define ('HOST', $host);

$auth = Zend_Auth::getInstance();
if (!$auth->hasIdentity()){
    $displayName = false;
}
else{
    $identity = $auth->getIdentity();
    $displayName = $identity->name;
}


$requestURI = $this->requestURI;
$request_array = explode('?', $requestURI, 2);
//array explode  ( string $delimiter  , string $string  [, int $limit  ] )

if (substr_compare($request_array[0], '/' , -1)) {  // if the uri doesn't end in a slash (minus query parameters), 
    $request_array[0] = $request_array[0] . '/';  // add one
}


if (isset($request_array[1])) { // if there are query parameters,
    $request_array[1] = "?" . $request_array[1];  // prepend a '?' to the set of parameters since we exploded on the '?' to get this string.
    //echo $request_array[1]; // for testing
} else {
    $request_array[1] = null;
}




$requestParams = $this->requestParams;
if(!isset($requestParams["q"])){
    
    $checkParam = $requestParams;
    unset($checkParam["page"]);
    unset($checkParam["recs"]);
    unset($checkParam["sort"]);
    
    if(count($checkParam)>3){
        $searchMessage = "Search this set of data";
    }
    else{
        $searchMessage = "Search all analytic data";
    }
    
    $full_link = $host.$requestURI;
    $full_link  = str_replace("&", "&amp;", $full_link );
    $full_link  = str_replace("&amp;amp;", "&amp;", $full_link );

    $fulltext = '';
    $fulltext .= '<input id="act_uri" type="hidden" value="'.$full_link.'" />';
    $fulltext .= '<span style="text-align:left; margin-left:2%; font-size:.75em;" >';
    $fulltext .= 'Or, type a search term in the box';
    $fulltext .= '</span><br/>';
    $fulltext .= '<div id="b_search_tab">
                    <div id="b_search_row" class="b_search">
                        <div id="b_search_cell_in" >
                                <input name="q" class="bb" type="text" id="q_string" placeholder="Search here..." />
                        </div>
                        <div id="b_search_cell_button">
                                <button class="bb" type="submit" onclick="textSearch();">Search</button>
                        </div>
                    </div>
                </div>
    ';
    
}
else{
    $fulltext = "";
}



$numFound = 0;
$facets = $this->facets;
$fulltext = "";


$filter_output = OpenContext_FacetOutput::make_filters_html($requestParams, $host);


$facet_fields = $facets["facet_fields"];
$facet_queries = $facets["facet_queries"];
$extendedFacets = true; //show more available facets 


//do advanced search interface
if(substr_count($requestURI, "advanced=true")>0){
    $advanced = true;
}
else{
    $advanced = false;
}

if($numFound>0){
    $facet_output = OpenContext_FacetOutput::facets_available($extendedFacets, $facet_fields, $facet_queries, $requestParams, $request_array, $host,    $advanced);
}
else{
    $facet_output = "<br/>(No results to this query, please try other search options)";
}



$googleURI = "";
$facetAtomURI = "";
$openSearchURI = "";

$jsonString = file_get_contents($host."/search/.json");
$jsonObj =  Zend_Json::decode($jsonString);


?>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
        <title><?php echo 'Open Context Browse: ('.$numFound.' Items Showing)'; ?></title>
        <link rel="shortcut icon" href="/images/layout/oc-favicon.ico" type="image/x-icon" />
        
        <!--
        <link href="<?php echo $host; ?>/components/css/browse" rel="stylesheet" type="text/css" /> 
        -->
        <link href="<?php echo $host; ?>/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" /> 
        <link href="<?php echo $host; ?>/css/opencontext-browse-rev2.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/atomresults.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/rounded_corners.css" rel="stylesheet" type="text/css" />
        
        <link rel="alternate" type="application/atom+xml" title="Atom facet feed" href="<?php echo URIescape($this->facetURI_Atom); ?>" />
        <link rel="alternate" type="application/atom+xml" title="Atom feed of results" href="<?php echo URIescape($this->currentAtom); ?>" />
        
        <link rel="first" type="application/atom+xml" title="Atom feed of results" href="<?php echo URIescape($this->firstPage_XHTML); ?>" />
        <?php
            if($this->prevPage_XHTML != false){
                echo '<link rel="prev" type="application/atom+xml" title="Atom feed of results" href="'.URIescape($this->prevPage_XHTML).'" />'.chr(13);
            }
            if($this->nextPage_XHTML != false){
                echo '<link rel="next" type="application/atom+xml" title="Atom feed of results" href="'.URIescape($this->nextPage_XHTML).'" />'.chr(13);
            }
        ?>
        
        <link rel="last" type="application/atom+xml" title="Atom feed of results" href="<?php echo URIescape($this->lastPage_XHTML); ?>" />
        <link rel="search" type="application/opensearchdescription+xml" href="<?php echo $openSearchURI; ?>" title="Open Context Web Search" />
        <script src="<?php echo $host; ?>/components/js/browse" type="text/javascript"></script>
        
        <script type="text/javascript">
        <!--
        
        
        -->
        </script>
        
        <script type="text/javascript">
        <!--
            
     
      -->
        </script>
    </head>
    <body>
    
<!-- 
    Logo,
-->    
<?php echo $this->render('header.phtml'); //reader document top ?>
   
<!-- 
    Navigation tabs, search box
-->
<?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>

    
 
<!--
BEGIN Container for main page content
--> 
    <div id="main"> 
        <!--Begin code for showing available facets-->
        <div id="main_content">
            <div id="main_row">
                <div id="left_cont">
                    <div id="filter_options">
                        <h3>Browse and Filter</h3>
                        <p>Click on one of the links below to further limit your view of <em>analytic data</em> in Open Context.</p>
                        <div id="search_sort_block">
                            <br/>
                        </div>
                    </div>
                    <div id="all_facets">
                            <?php echo $facet_output; ?>
                    </div>
                </div>
                <div id="right_cont">   
                    <div id="selected_filters" >
                        <p>Sorry! Open Context does not have any data tables described by your search criteria. However, since Open Context has a total of <strong><?php echo $jsonObj["numFound"]; ?></strong> records, you may find what you want by clicking a browse option below.
                        </p>
                        <br/>
                        <h5>Current Search Filters</h5>
                        <div>
                            <?php echo $filter_output; ?>
                        </div>
                        
                        <br/>
                        <p class="tinyText" style="text-align:right;">Last Updated: <em><?php echo date("F j, Y, g:i a", strtotime($jsonObj["updated"])); ?></em></p>
                        
                    </div>
                    <div id="item_list_outer"  style="background-color: white;">
                        <div style="padding: 3%;">
                            <h4>Types of resources:</h4>
                            <p>
                            <?php
                            $i=0;
                            $dtypes = new DocumentTypes;
                            foreach($jsonObj["facets"]["resource type"] as $actTypes){
                                
                                $dtypes->solrToOutside($actTypes["name"]);
                                $comma = ", ";
                                if($i==0){
                                        $comma = "";
                                }
                                echo $comma."<a title=\"View items from this context\" href=\"".$actTypes["href"]."\">".$dtypes->outsideTerm."</a> (".$actTypes["count"].")";
                                $i++;
                            }
                            ?>
                            </p>
                            <br/>
                            <h4>Items from these contexts:</h4>
                            <p>
                            <?php
                            $i=0;
                            foreach($jsonObj["facets"]["context"] as $actContext){
                                    
                                $comma = ", ";
                                if($i==0){
                                        $comma = "";
                                }
                                echo $comma."<a title=\"View items from this context\" href=\"".$actContext["href"]."\">".$actContext["name"]."</a> (".$actContext["count"].")";
                                $i++;
                            }
                            ?>
                            </p>
                            <br/>
                            <h4>Items belonging to these general categories:</h4>
                            <div style="margin-left:5px">
                                <?php
                                $jj = count($jsonObj["facets"]["category"]);
                                $i=0;
                                foreach($jsonObj["facets"]["category"] as $actCat){
                                    $comma = ", ";
                                    if($i==($jj-1)){
                                        $comma = "";
                                    }
                                    $comma = "";
                                    
                                    $actImage = OpenContext_ProjectAtomJson::class_icon_lookup($actCat["name"]);
                                    echo "<div style='float:left; width:40%; padding-top:4px;'><div style='float:left;'>";
                                    echo "<a title='View items of this type' href='".$actCat["href"]."'>";
                                    echo "<img src='".$actImage."' alt='".$actCat["name"]."'/></a>";
                                    echo "</div>";
                                    echo "<div style='padding:3px; float:left; margin-right:3px;'>";
                                    echo "<span class='bodyText'><a title='View items of this type' href='".$actCat["href"]."'>".$actCat["name"]."</a> (".$actCat["count"].")";
                                    echo $comma."</span>";
                                    echo "</div>";
                                    echo "</div>";
                                    $i++;
                                }
                                ?>
                            </div>
                            <div style="clear:both; width:90%"></div>
                            <br/>
                            <h4>Items from these projects and collections:</h4>
                            <p>
                            <?php
                            $i=0;
                            foreach($jsonObj["facets"]["project"] as $actContext){
                                    
                                $comma = ", ";
                                if($i==0){
                                        $comma = "";
                                }
                                echo $comma."<a title=\"View items from this context\" href=\"".$actContext["href"]."\">".$actContext["name"]."</a> (".$actContext["count"].")";
                                $i++;
                            }
                            ?>
                            </p>
                        </div>
                    </div>
                </div>
            </div>  
   
        <!--
        END of div container for placing main page content
        -->
        </div>
    
    </div>

    <div id="bottomBuffer">

    </div>
    <?php echo $this->render('footer.phtml'); //reader document footer ?>
    </body>
</html>    