<?php


$host = OpenContext_OCConfig::get_host_config();


?>

<div id="footerTop">
    <div id="footer_center">
        <div id="footer_tab">
            <div id="footer_row">
                <div class="footer_cell">
                    <img src="<?php echo $host; ?>/images/layout/neh_logo_horizontal_web.png" alt="NEH-logo" />
                </div>
                <div class="footer_cell">
                    <img src="<?php echo $host; ?>/images/layout/imls-logo.png" alt="IMLS-logo" />
                </div>
                <div class="footer_cell">
                    <img src="<?php echo $host; ?>/images/layout/hewlett.png" alt="Hewlett-logo" />
                </div>
            </div>
        </div>
    </div>
</div>
<div id="footerLower">
</div>