<?php


$navTabArray = array("index"=> array("uri"=>"/",
                                      "name"=>"Home",
                                      "title"=> "Open Context Home Page, map and timeline interface",
                                      "active"=>true),
                      "about"=> array("uri"=>"/about/",
                                      "name"=>"About",
                                      "title"=> "Background, uses, guide for contributors, web services overview",
                                      "active"=>true),
                      "projects"=> array("uri"=>"/projects/",
                                      "name"=>"Projects",
                                      "title"=> "Summary of datasets in Open Context",
                                      "active"=>true),
                      "browse"=> array("uri"=>"/sets/",
                                       "name"=>"Browse",
                                       "title"=> "Search and browse through locations, contexts, finds, etc.",
                                       "active"=>true),
                      "lightbox"=> array("uri"=>"/lightbox/",
                                         "name"=>"Lightbox",
                                         "title"=> "Search and browse through images linked to Open Context records",
                                         "active"=>true),
                      "tables"=> array("uri"=>"/tables/",
                                       "name"=>"Tables",
                                       "title"=> "Tabular data formated for easy download",
                                       "active"=> true),
                      "search"=> array("uri"=>"/search/",
                                       "name"=> "Search",
                                       "title"=> "Global search of all content, policies, and other documentation",
                                        "active"=> true),
                      "details"=> array("uri"=>"/details/",
                                       "name"=> "Details",
                                       "title"=> "Use the Browse or Lightbox feature and select an item for detailed view",
                                        "active"=> false),
                      "accounts"=> array("uri"=>"/auth/",
                                       "name"=> "My Account",
                                       "title"=> "Manage your password and notification settings",
                                        "active"=> true)
                      );


//figure out what the active tab is
$host = OpenContext_OCConfig::get_host_config();
$request = $_SERVER['REQUEST_URI'];
$requestEx = explode("/", $request);
$requestPrefix = $requestEx[0];
if(count($requestEx)>=2){
    $requestPrefix .= $requestEx[1];
}
if(strlen($requestPrefix)>1){
    $requestPrefix = "/".$requestPrefix."/";
}
else{
    $requestPrefix = "/";
}

//now match the request prefix with uri paths from the nav-tab-array
foreach($navTabArray as $navKey => $actNavArray){
    if($requestPrefix == $actNavArray["uri"]){
        $activeTab = $navKey;
        break;
    }
}





    if($activeTab  == "search"){
        unset($navTabArray ["details"]);
    }
    elseif($activeTab  == "details"){
        unset($navTabArray ["search"]);
    }
    else{
        unset($navTabArray ["details"]); 
    }

    unset($navTabArray["index"]);

    $dom = new DOMDocument("1.0", "utf-8");
    $dom->formatOutput = true;
    $root = $dom->createElement("ul");
    $root->setAttribute("class", "nav");
    $dom->appendChild($root);
    
    foreach($navTabArray  as $tab => $tabData){
        
        $element = $dom->createElement("li");
        if($tab == $activeTab){
            $element->setAttribute("class", "active");
        }
        else{
            //$element->setAttribute("class", "headerNavTabLink");
        }
        $elementA = $dom->createElement("a");
        $elementA->setAttribute("href", $host.$tabData["uri"]);
        $elementA->setAttribute("title", $tabData["title"]);
        $elementAtext = $dom->createTextNode($tabData["name"]);
        $elementA->appendChild($elementAtext);
        $element->appendChild($elementA);
        $root->appendChild($element);
    }
    
    /*
    $output = str_replace('<?xml version="1.0"?>', '', $root->saveXML());
    */
    $output = $dom->saveXML($root);

?>

<div id="headerNav">
    <div class="navbar">
        <div class="navbar-inner">
            <?php echo $output; ?>
            <?php if($activeTab != "browse" && $activeTab != "lightbox"){ ?>
            <form method="get" action="<?php echo $host;?>/search/" class="navbar-search pull-right" >
                <input type="text" class="search-query span2" name="q" value="Search">
                
                    <input id="headerSearchSubmit" type="submit" value="" />
                
            </form>
            <?php }//end case for no browse, or lightbox ?>
        </div>
    </div>
</div>