
<div class="newsroom_widget">
    <h2>Latest News</h2>
    <div class="newsfeed_box">
        <h3>
            <a href="http://ux.opencontext.org/blog" class="rsswidget" title="Updates and news about Open Context">Heritage Bytes: Open Context News</a>
        </h3>
        <div id="OC-feed"></div>
        <h3>
            <a href="http://ux.opencontext.org/blog/feed/" class="rss icon" title="Updates and news about Open Context">get the news feed</a>
        </h3>
    </div>
    <div class="newsfeed_box">
        <h3>
            <a href="https://github.com/ekansa/Open-Context-Data/commits/master" class="rsswidget" title="Change-log for Open Context data">Change-log and updates to Open Context data</a>
        </h3>
        <div id="Git-data-feed"></div>
        <h3>
            <a href="https://github.com/ekansa/Open-Context-Data/commits/master.atom" class="rss icon" title="Change-log for Open Context data">get data updates feed</a>
        </h3>
    </div>
    
    <div class="newsfeed_box">
        <h3>
            <a href="https://github.com/ekansa/open-context-code/commits/master" class="rsswidget" title="Updates to Open Context code">Open Context Source-code Updates</a>
        </h3>
        <div id="Git-code-feed"></div>
        <h3>
            <a href="https://github.com/ekansa/open-context-code/commits/master.atom" class="rss icon" title="Updates to Open Context code">get code updates feed</a>
        </h3>
    </div>
</div> 

