<?php
$host = OpenContext_OCConfig::get_host_config();

$archive = $this->archive;
$atomLink = $host."/all/.atom?page=".$archive->currentPage;

?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
      <title>Index of all Open Context Content</title> 
      <link href="/css/opencontext_style.css" rel="stylesheet" type="text/css" /> 
      <link href="/css/test_landing_page.css" rel="stylesheet" type="text/css" />
      <link href="/css/default_banner.css" rel="stylesheet" type="text/css" />
      <link href="/css/rounded_corners.css" rel="stylesheet" type="text/css" />
      <link rel="alternate" type="application/atom+xml" title="Open Context: Feed of All Content" href="<?php echo $atomLink; ?>" /> 
      <link rel="shortcut icon" href="/images/general/oc_favicon.ico" type="image/x-icon" />
    </head>
    
<body>
  <div id="oc_logo">
	<a href="<?php echo $host; ?>" title="Open Context (Home)"><img alt="Open Context Logo" src="/images/general/oc_logo.jpg" border="0" ></img></a>
    </div>
    <div id="oc_tagline">
	<img alt="Open Context Tagline" src="/images/general/oc_tagline.jpg" ></img>
    </div>
    <div id="oc_beta">
	<img alt="Beta Stamp" src="/images/general/oc_betastamp.jpg" ></img>
    </div>
    
    <div id="oc_top_search">
	<form method="get" action="<?php echo $host;?>/search/" id="search-form">
	<div id="search_box">
	<input type='text' name='q' class='tinyText' value='Search' size='30' onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';" />
	</div>
	<div id="search_cntrl">
	    <input class="oc_top_sbutton" type="submit" value="" />
	</div>
	</form>
    </div>
   
   
   <!-- 
    Navigation tabs
    -->    
    <?php echo OpenContext_NavMenus::GeneralNavMenu("about"); ?>
    
    <div id="main">
	<div id="pageTop">
            <div id="pageIntro">
                <p class="pageName" align="center">Index of all Open Context Content</p>
                
                <div style="margin:10px;">
                    <p class="bodyText">This page provides a comprehensive list of all Open Context content, but that's just about it.
		    The Atom feed version of this page can be read by other digital repositories. Items are sorted by updated time, with the most recently changed /
	    updated items first. By providing this list, especially in Atom, Open Context exposes its content
	    in a way that simplifies replication and archiving of content.</p>
                </div>
            </div>
            <div id="about_submenu" class="rounded-corners">
                    <p class="bodyText"><em>More About Open Context:</em></p>
                    <?php echo OpenContext_NavMenus::AboutNavMenu("index", $host); ?>
            </div>
            <div id="pageTopEnd">
                <br/>
            </div>
        </div>
        
        
        <br/>
        <div style="margin:10px;">
            <p class="bodyText"><strong>List of All Content</strong></p>
	    
	    <p class="bodyText">Please note. The Atom feed linked from this page simply provides a list of Open Context content. Please
	    referr to the <a href='<?php echo $host."/about/services"; ?>' title='Working with Machine-readable data in Open Context'>Web-services documentation</a> to learn how to work with other Atom, KML, and JSON services that are
	    more oriented toward research applications including visualizations, mashups, and data interoperability.</p>
	    <table> 
            <tbody> 
              <tr> 
                <th>Item Name</th> 
                <th>Item Type</th> 
                <th>Created / Published</th> 
                <th>Updated / Last Modified</th>
		<th>Archival ID</th>
              </tr> 
	    
	    <?php
		$i=true;
		$itemTypeMap = array("spatial"=> "Location / Object",
				     "media"=> "Media Resource",
				     "document"=> "Document / Narrative",
				     "person"=> "Person / Organization",
				     "project"=> "Project / Collection",
				     "table"=> "Data table"
				     );
		
		foreach($archive->feedItems as $item){
		    
		    if($i){
			$rowStyle = " style='background-color: #F4F4F4;' ";
			$i = false;
		    }
		    else{
			$rowStyle = "";
			$i=true;
		    }
		    
		    echo "<tr".$rowStyle.">".chr(13);
		    echo "<td><a href='".$item["itemURI"]."' title='Link to item' >".$item["label"]."</a></td>".chr(13);
		    echo "<td>".$itemTypeMap[$item["itemType"]]."</td>".chr(13);
		    echo "<td>".$item["ItemCreated"]."</td>".chr(13);
		    echo "<td>".$item["ItemUpdated"]."</td>".chr(13);
		    if($item["noid"] != false){
			echo "<td>".$item["noid"]."</td>".chr(13);
		    }
		    else{
			echo "<td>[Not archived yet]</td>".chr(13);
		    }
		    echo "</tr>".chr(13);
		}//end loop
	    
	    ?>
	    </tbody>
	    </table>
	    
	</div>
	
	<div id="bottom">
	</div>
	
    </div>

</body>
</html>
