<?php

$host = OpenContext_OCConfig::get_host_config();    
$json_string = $this->JSONstring;
$table_data = Zend_Json::decode($json_string);

$tableHTML = "<table>".chr(13);
foreach($table_data["table_fields"] as $actField){
    $tableHTML .= "<th class='tinyText'>".$actField."</th>".chr(13);         
}

$recMax = 200;
$recCount = 0;
foreach($table_data["records"] as $actUUID => $actRecord){
    $tableHTML .= "<tr>";
    foreach($actRecord as $field => $value){
	
	if($field == 'label'){
	    $tableHTML .= "<td><a href='".$host."/subjects/".$actUUID."'>".$value."</a></td>";
	}
	else{
	     $tableHTML .= "<td>".$value."</td>";
	}
    
    }//end loop through fields
    
    $tableHTML .= "</tr>".chr(13);
    if($recCount>=$recMax){
	Break;
    }
    $recCount++;
}
$tableHTML .= "</table>";

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
      <title>Open Context: View a Table</title> 
      <link href="/css/opencontext_style.css" rel="stylesheet" type="text/css" /> 
      <link href="/css/test_landing_page.css" rel="stylesheet" type="text/css" />
      <link href="/css/default_banner.css" rel="stylesheet" type="text/css" />
      
      
    </head>
    
<body>
  <div id="oc_logo">
	<a href="<?php echo $host; ?>"><img alt="Open Context Logo" src="/images/general/oc_logo.jpg" border="0" ></img></a>
    </div>
    <div id="oc_tagline">
	<img alt="Open Context Tagline" src="/images/general/oc_tagline.jpg" ></img>
    </div>
    <div id="oc_beta">
	<img alt="Beta Stamp" src="/images/general/oc_betastamp.jpg" ></img>
    </div>
    
    <div id="oc_main_nav">
        <div class="sides"></div>
        <div class="n_act_nav"><a href="../about" title="Learn more about Open Context">About</a></div>
        <div class="sides"></div>
        <div class="n_act_nav"><a href="../projects/" title="Summary of datasets in Open Context">Projects</a></div>
        <div class="sides"></div>
        <div class="n_act_nav"><a href="../sets/" title="Explore data">Browse</a></div>
        <div class="sides"></div>
        <div class="n_act_nav"><a href="../lightbox/" title="Browse images">Lightbox</a></div>
        <div class="sides"></div>
        <div class="act_nav"><span title="Coming soon">Tables</span></div>
        <div class="sides"></div>
        <div class="n_act_nav"><span title="Browse to get details of items">Details</span></div>
        <div class="sides"></div>
        <div class="n_act_nav"><span title="Coming soon">My Account</span></div>
    </div>
    
    <div id="main">
	<div id="pageTop">
            <div id="pageIntro">
                <p class="subHeader" align="left" style="font-size:14px;">Current Table in Open Context</p>
                
		</div>
            </div>
            
            <div id="pageTopEnd">
                <br/>
		<div style='width:95%; margin:5px; overflow:auto'>
		<?php echo $tableHTML; ?>
		</div>
            </div>
        </div>
        
	 </div>
	
	<div id="bottom">
	</div>
	
    </div>

</body>
</html>
