<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->
<?php if ($this->pageCount): ?>
  <div class="paginator" style="text-align:right;">
    Page through table records: 
  <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
      <a href="<?php echo $this->url.'?page='.$this->previous; ?>">&lt; Previous</a> 
    <?php else: ?>
      <span class="disabled">&lt; Previous</span> 
    <?php endif; ?>

    <!-- Numbered page links -->
    <?php foreach ($this->pagesInRange as $page): ?>
      <?php if ($page != $this->current): ?>
        <a href="<?php echo $this->url.'?page='.$page; ?>"><?php echo $page; ?></a> 
      <?php else: ?>
        <span class="this-page"><?php echo $page; ?> </span>
      <?php endif; ?>
    <?php endforeach; ?>

    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
      <a href="<?php echo $this->url.'?page='.$this->next; ?>">Next &gt;</a>
    <?php else: ?>
      <span class="disabled">Next &gt;</span>
    <?php endif; ?>
  </div>
<?php endif; ?>
