<?php
$host = OpenContext_OCConfig::get_host_config();
$exTableObj = $this->exTableObj;
$metadata = $exTableObj->metadata;

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Open Context: View Table <?php echo $metadata["title"]; ?></title>
        <link rel="alternate" type="text/csv" title="<?php echo $metadata["title"]; ?> (Comma Seperated Values)" href="<?php echo $host.'/tables/'.OpenContext_TableOutput::tableID_toURL($this->table_id).'.csv';?>"/>
        <link rel="alternate" type="application/json" title="<?php echo $metadata["title"]; ?> (JSON)" href="<?php echo $host.'/tables/'.OpenContext_TableOutput::tableID_toURL($this->table_id).'.json';?>"/>
    
        <link href="<?php echo $host; ?>/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/table-rev2.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/bibliographic.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/general-item-rev2.css" rel="stylesheet" type="text/css" />
        
        <script src="<?php echo $host; ?>/js/jquery/jquery-1.7.2.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
        <script src="<?php echo $host; ?>/js/jquery/doubleScroll.js" type="text/javascript"></script>
        
        <!--
        <script src="<?php echo $host; ?>/js/jquery/jquery-1.7.2.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.min.js"></script>
        <script src=https://raw.github.com/sniku/jQuery-doubleScroll/master/jquery.doubleScroll.js" type="text/javascript"></script>
        -->
        <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-transition.js" type="text/javascript"></script>
        <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-tab.js" type="text/javascript"></script>
        <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-dropdown.js" type="text/javascript"></script>
        
        <link rel="shortcut icon" href="/images/layout/oc-favicon.ico" type="image/x-icon" />
        
        
        
    </head>
    
    <body>
    <!-- 
        Logo,
    -->    
        <?php echo $this->render('header.phtml'); //reader document top ?>
           
        <!-- 
            Navigation tabs, search box
        -->
        <?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>
    
        <!--
        BEGIN Container for main page content
        --> 
        <div id="main">
            <div id="main_content">
                <div id="intro-row">
                    <div id="intro-cell">
                        <h1>Table: &ldquo;<?php echo $metadata["title"]; ?>&rdquo;</h1>
                        <p>
                            <?php
                      
                      
                            if(count($metadata["references"])<2){
                                echo "The data in this table comes from one project or collection. Some data relating to the records in this table may depend upon
                                complex structures that cannot be easily represented in a table format. If you need data fully expressing such complex structures, download
                                the XML representations of these data. To learn how to do this, please read the <a href='".$host."/about/services/'
                                title='Methods for retrieving machine-readable data'>web-services documentation</a>.";
                            }
                            else{
                                echo "This table contains data originating from different projects and collections. These different projects may have worked under different
                            assumptions and methodologies which may complicate comparisons. This may be the case even if projects and collections
                            used the same descriptive terminology. In working with these data, you should exercise your best
                            critical judgment as a researcher and examine available dataset documentation and related publications to help
                            inform your interpretations.";
                            }
                          
                            ?>
                        </p>
                        
                        <h2 id="csv-download">Download Table: <a href="<?php echo "CHANGE"; ?>" title="Download and open in Excel or Open Office">CSV format</a></h2>
                    </div>
                    
                    
                    <!-- end intro-cell div -->
                    <div id="otabs-cell">
                        <div id="otabs">
                            <h5>Download File Formats</h5>
                            <ul class="nav nav-list">
                                <!-- <li class="nav-header">Other Recently Made Tables</li> -->
                                <?php
                                if(isset($metadata["files"])){
                                    foreach($metadata["files"] as $typeKey => $fileArray){
                                        
                                        echo "<li>".chr(13);
                                        echo "<a href=\"".$host."/exports/".$fileArray["filename"]."\" title=\"Download as ".$typeKey." \">".$exTableObj->getHumanReadFormat($typeKey)."</a> (".$fileArray["size-note"].")".chr(13);
                                        echo "</li>".chr(13);
                                        
                                    }
                                }
                                ?>
                            </ul>
                        </div>
                    </div>
                    <!-- end otabs-cell div -->
                    
                </div>
                <!-- end intro-row div -->
             </div>
            <!-- end main tab div -->
            
            <div id="meta-area">
                <table id="metadata">
                    <tbody>
                        <tr>
                            <td>
                                Table Name
                            </td>
                            <td>
                                <?php echo $metadata["title"];
                                
                                
                                
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Number of Records
                            </td>
                            <td>
                                <?php echo $metadata["recordCount"]; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Table Description
                            </td>
                            <td>
                                <?php echo $metadata["description"]; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Tags / Keywords
                            </td>
                            <td>
                                <?php echo "CHANGE"; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Download Information
                            </td>
                            <td>
                                <?php echo "CHANGE"; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Query Link
                            </td>
                            <td>
                                <a href="<?php echo "CHANGE" ; ?>" title="Link to browse this set of records"><?php echo "CHANGE" ; ?></a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Principal Analyst(s) / Observers
                            </td>
                            <td>
                                <?php
                                $first = true;
                                foreach($metadata["contributorList"] as $nArray){
                                    $output = "<a href=\"".$nArray["contributor"]["id"]."\">".$nArray["contributor"]["name"]."</a>";
                                    if(!$first){
                                        $output = ", ".$output;
                                    }
                                    echo $output;
                                    $first = false;
                                }
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Directing / Supervisory People (Editorial Role)
                            </td>
                            <td>
                                <?php
                                $first = true;
                                foreach($metadata["editorList"] as $nArray){
                                    $output = "<a href=\"".$nArray["editor"]["id"]."\">".$nArray["editor"]["name"]."</a>";
                                    if(!$first){
                                        $output = ", ".$output;
                                    }
                                    echo $output;
                                    $first = false;
                                }
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Projects and Collections
                            </td>
                            <td>
                                <?php
                                $first = true;
                                foreach($metadata["references"] as $nArray){
                                    $output = "<a href=\"".$nArray["id"]."\">".$nArray["name"]."</a> (".$nArray["count"].")";
                                    if(!$first){
                                        $output = ", ".$output;
                                    }
                                    echo $output;
                                    $first = false;
                                }
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Table Publication Date
                            </td>
                            <td>
                                <?php
                                
                                echo date("F j, Y, g:i a", strtotime($metadata["published"])); 
                                
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Table Metadata Update
                            </td>
                            <td>
                                <?php
                                echo date("F j, Y, g:i a", strtotime($metadata["updated"])); 
                                ?>
                            </td>
                        </tr>
                        <?php
                        if(isset($metadata["doi"])){
                        ?>
                        <tr>
                            <td>
                                Document Object Identifier (DOI)
                            </td>
                            <td>
                                <?php echo "DOI <a href=\"http://dx.doi.org/".$metadata["doi"]."\">".$metadata["doi"]."</a>"; ?>
                            </td>
                        </tr>
                        <?php
                        }//end condiction with DOI
                        elseif(isset($metadata["ark"])){
                        ?>
                        <tr>
                            <td>
                                CDL Archival Identifier (ARK)
                            </td>
                            <td>
                                <?php echo "<a href=\"http://dx.doi.org/".$metadata["ark"]."\">".$metadata["ark"]."</a>"; ?>
                            </td>
                        </tr>
                        <?php
                        }//end conditional with ARK
                        ?>
                        <tr>
                            <td>
                                Suggested Citation
                            </td>
                            <td>
                                <?php echo $exTableObj->citation; ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <!-- end meta-area div -->
            
            <div id="tab-area">
                <?php
                
                $records = $exTableObj->loadSampleRecords();
                if(is_array($records)){
                    echo "<h3>Records ".($exTableObj->recStartIndex + 1)." to ".($exTableObj->recEndIndex)." of ".$metadata["recordCount"]."</h3>";
                }
                else{
                    echo "<h3>Record Preview Not Available</h3>";
                }
                ?>
                
                <div id="tab-box">
                    <div class="double-scroll" id="preview-tab-outer">
                        <table class="table table-striped table-condensed table-hover table-bordered data-tab" id="preview-tab">
                            <thead id="tab-fields">
                                <tr>
                                    <?php
                                    foreach($metadata["tableFields"] as $tfield){
                                        echo "<th>".htmlentities($tfield)."</th>".chr(13);
                                    }
                                    ?>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                
                                if(is_array($records)){
                                    foreach($records as $actRecord){
                                        echo "<tr>".chr(13);
                                        foreach($actRecord as $field=>$value){
                                            //$value = htmlentities($value);
                                            $value = $exTableObj->recXHTMLvalue($value);
                                            echo "<td>";
                                            echo $value;
                                            echo "</td>";
                                        }
                                        echo "</tr>".chr(13);
                                    }
                                }
                                
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- end div for tab-box -->
            </div>
            <!-- end div for tab-area -->
        </div>
        <!-- end main div -->
        <?php echo $this->render('footer.phtml'); //reader document footer ?>
        
        
        <script type="text/javascript">
        <!--
        
        $(document).ready(function(){
            $('#preview-tab-outer').doubleScroll({contentElement: $('#preview-tab') });
        });

        
        -->
        </script>
        
    </body>
</html>
