<?php
$host = OpenContext_OCConfig::get_host_config();
$tableID = $this->table_id;

$tableObj = new Table;
$tableFields = $tableObj->tableFieldFormat($this->table_fields); //format table fields
$table_metadata = $tableObj->tableMetadataFormat($tableID, $this->table_metadata);
$tableObj->checkCurrentData($tableID);
$otherTables = $tableObj->otherTables($tableID);

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Open Context: View Table <?php echo $tableObj->showTabName; ?></title>
        <link rel="alternate" type="text/csv" title="<?php echo $tableObj->showTabName; ?> (Comma Seperated Values)" href="<?php echo $host.'/tables/'.OpenContext_TableOutput::tableID_toURL($this->table_id).'.csv';?>"/>
        <link rel="alternate" type="application/json" title="<?php echo $tableObj->showTabName; ?> (JSON)" href="<?php echo $host.'/tables/'.OpenContext_TableOutput::tableID_toURL($this->table_id).'.json';?>"/>
        <?php
        if($tableObj->archiveID != false){
            echo '<link rel="archival" type="application/xhtml+xml" href="http://n2t.net/ezid/id/ark:/'.$tableObj->archiveID.'"/>'.chr(13);
        }
        ?>
        <link href="<?php echo $host; ?>/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/table-rev2.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/bibliographic.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/general-item-rev2.css" rel="stylesheet" type="text/css" />
        <script src="<?php echo $host; ?>/js/jquery/jquery-1.7.2.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
        <script src="<?php echo $host; ?>/js/jquery/doubleScroll.js" type="text/javascript"></script>
        <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-transition.js" type="text/javascript"></script>
        <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-tab.js" type="text/javascript"></script>
        <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-dropdown.js" type="text/javascript"></script>
        
        <link rel="shortcut icon" href="/images/layout/oc-favicon.ico" type="image/x-icon" />
        
        
        
    </head>
    
    <body>
    <!-- 
        Logo,
    -->    
        <?php echo $this->render('header.phtml'); //reader document top ?>
           
        <!-- 
            Navigation tabs, search box
        -->
        <?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>
    
        <!--
        BEGIN Container for main page content
        --> 
        <div id="main">
            <div id="main_content">
                <div id="intro-row">
                    <div id="intro-cell">
                        <h1>Table: &ldquo;<?php echo $tableObj->showTabName; ?>&rdquo; <?php echo $tableObj->titleMessage; ?></h1>
                        <p>
                            <?php
                      
                      
                            if(count($tableObj->tabProjects)<2){
                                echo "The data in this table comes from one project or collection. Some data relating to the records in this table may depend upon
                                complex structures that cannot be easily represented in a table format. If you need data fully expressing such complex structures, download
                                the XML representations of these data. To learn how to do this, please read the <a href='".$host."/about/services/'
                                title='Methods for retrieving machine-readable data'>web-services documentation</a>.";
                            }
                            else{
                                echo "This table contains data originating from different projects and collections. These different projects may have worked under different
                            assumptions and methodologies which may complicate comparisons. This may be the case even if projects and collections
                            used the same descriptive terminology. In working with these data, you should exercise your best
                            critical judgment as a researcher and examine available dataset documentation and related publications to help
                            inform your interpretations.";
                            }
                          
                            ?>
                        </p>
                        
                        <h2 id="csv-download">Download Table: <a href="<?php echo $tableObj->csvURI; ?>" title="Download and open in Excel or Open Office">CSV format</a></h2>
                    </div>
                    <!-- end intro-cell div -->
                    <div id="otabs-cell">
                        <div id="otabs">
                            <h5>Other Recently Made Tables</h5>
                            <ul class="nav nav-list">
                                <!-- <li class="nav-header">Other Recently Made Tables</li> -->
                                <?php
                                //echo print_r($otherTables);
                                foreach($otherTables as $tabRec){
                                    
                                    echo "<li>".chr(13);
                                    echo "<a href=\"".$tabRec["uri"]."\" title=\"Downloadable table with ".$tabRec["num_records"]." records\">".$tabRec["table_name"]."</a>".chr(13);
                                    echo "</li>".chr(13);
                                    
                                }
                                ?>
                            </ul>
                        </div>
                    </div>
                    <!-- end otabs-cell div -->
                </div>
                <!-- end intro-row div -->
             </div>
            <!-- end main tab div -->
            
            <div id="meta-area">
                <table id="metadata">
                    <tbody>
                        <tr>
                            <td>
                                Table Name
                            </td>
                            <td>
                                <?php echo $tableObj->showTabName;
                                
                                if(strlen($tableObj->titleMessage)>1){
                                    echo " <em>".$tableObj->titleMessage."</em>";
                                }
                                
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Number of Records
                            </td>
                            <td>
                                <?php echo $table_metadata["numFound"]; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Table Description
                            </td>
                            <td>
                                <?php echo $table_metadata["table_description"]; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Tags / Keywords
                            </td>
                            <td>
                                <?php echo $table_metadata["tagstring"]; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Download Information
                            </td>
                            <td>
                                <?php echo $tableObj->showSegmentNote; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Query Link
                            </td>
                            <td>
                                <a href="<?php echo $tableObj->queryURL ; ?>" title="Link to browse this set of records"><?php echo $tableObj->queryURL ; ?></a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Principal Analyst(s) / Observers
                            </td>
                            <td>
                                <?php echo implode(", ", $tableObj->showContributors); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Directing / Supervisory People
                            </td>
                            <td>
                                <?php echo implode(", ", $tableObj->DCcreators); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Projects and Collections
                            </td>
                            <td>
                                <?php echo implode(", ", $tableObj->tabProjects); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Latest Publication Date of Items in Table
                            </td>
                            <td>
                                <?php
                                if($table_metadata["setLastPublished"] != false){
                                    echo date("F j, Y, g:i a", strtotime($table_metadata["setLastPublished"]));
                                }
                                else{
                                    echo "[Metadata not documented when table was created]";
                                }
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Latest Update / Revision Time of Items in Table
                            </td>
                            <td>
                                <?php
                                if($table_metadata["setLastUpdate"] != false){
                                    echo date("F j, Y, g:i a", strtotime($table_metadata["setLastUpdate"]));
                                }
                                else{
                                    echo "[Metadata not documented when table was created]";
                                }
                                ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Time of Table Creation
                            </td>
                            <td>
                                <?php echo date("F j, Y, g:i a", strtotime($table_metadata["TabCreated"])); ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Table Generated by
                            </td>
                            <td>
                                <?php echo $table_metadata["TabCreator"]; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                CDL Archival Identifier
                            </td>
                            <td>
                                <?php echo $tableObj->archiveID; ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Suggested Citation
                            </td>
                            <td>
                                <?php echo $tableObj->citeString; ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <!-- end meta-area div -->
            
            <div id="tab-area">
                <!-- pagination -->
                <?php echo $this->paginationControl($this->table_data, 'Sliding', 'tables/pagination_control.phtml',array('host'=>$host,'hash'=>$table_metadata["setHash"])); ?>
                
                <div id="tab-box">
                    <div class="double-scroll">
                        <table class="table table-striped table-condensed table-hover table-bordered data-tab" style="width:3337px;">
                            <thead id="tab-fields">
                                <tr>
                                    <?php
                                    foreach($tableFields as $tfield){
                                        echo "<th>".htmlentities($tfield)."</th>".chr(13);
                                    }
                                    ?>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                
                                foreach($this->table_data as $actUUID => $actRecord){
                                    echo "<tr>".chr(13);
                                    foreach($actRecord as $field=>$value){
                                        $value = htmlentities($value);
                                        echo "<td>";
                                        if ($field == "label"){
                                            echo "<a href=\"".$host."/subjects/".$actUUID."\">".$value."</a>";
                                        }
                                        else{
                                            echo $value;
                                        }
                                        echo "</td>";
                                    }
                                    echo "</tr>".chr(13);
                                }
                                
                                
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- end div for tab-box -->
            </div>
            <!-- end div for tab-area -->
        </div>
        <!-- end main div -->
        <?php echo $this->render('footer.phtml'); //reader document footer ?>
        
        
        <script type="text/javascript">
        <!--
        
        $(document).ready(function(){
            $('.double-scroll').doubleScroll();
        });
        
        
        -->
        </script>
        
    </body>
</html>
