<?php
$host = OpenContext_OCConfig::get_host_config();
$tableID = $this->table_id;

$tableObj = new Table;
$tableFields = $tableObj->tableFieldFormat($this->table_fields); //format table fields
$tableObj->tableMetadataFormat($tableID, $this->table_metadata);
$tableObj->checkCurrentData($tableID);

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Open Context: View Table <?php echo $tableObj->showTabName; ?></title>
        <link rel="alternate" type="text/csv" title="<?php echo $tableObj->showTabName; ?> (Comma Seperated Values)" href="<?php echo $host.'/tables/'.OpenContext_TableOutput::tableID_toURL($this->table_id).'.csv';?>"/>
        <link rel="alternate" type="application/json" title="<?php echo $tableObj->showTabName; ?> (JSON)" href="<?php echo $host.'/tables/'.OpenContext_TableOutput::tableID_toURL($this->table_id).'.json';?>"/>
        <?php
        if($tableObj->archiveID != false){
            echo '<link rel="archival" type="application/xhtml+xml" href="http://n2t.net/ezid/id/ark:/'.$tableObj->archiveID.'"/>'.chr(13);
        }
        ?>
        <link href="<?php echo $host; ?>/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/subject-rev2.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/general-item-rev2.css" rel="stylesheet" type="text/css" />
        <script src="<?php echo $host; ?>/js/jquery/jquery-1.7.2.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
        <script src="<?php echo $host; ?>/js/jquery/double-scroll.js" type="text/javascript"></script>
        <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-transition.js" type="text/javascript"></script>
        <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-tab.js" type="text/javascript"></script>
        <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-dropdown.js" type="text/javascript"></script>
        
        <link rel="shortcut icon" href="/images/layout/oc-favicon.ico" type="image/x-icon" />
        
        <script type="text/javascript">
        <!--
        
        $(document).ready(function(){
            $('.double-scroll').doubleScroll();
        });
        
        
        -->
        </script>
        
        <style type="text/css">
            .double-scroll{
                width: 100%;
            }
            .double-scroll-out {
                border: 1px solid #9FB6CD;
            }
            .data-tab {
                
            }
        </style>
        
        
    </head>
    
    <body>
    <!-- 
        Logo,
    -->    
        <?php echo $this->render('header.phtml'); //reader document top ?>
           
        <!-- 
            Navigation tabs, search box
        -->
        <?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>
    
        <!--
        BEGIN Container for main page content
        --> 
        <div id="main">
            <h1>Table: &ldquo;<?php echo $tableObj->showTabName; ?>&rdquo; <?php echo $tableObj->titleMessage; ?></h1>
            
            
            <div class="double-scroll-out">
                <div class="double-scroll">
                    <table class="table table-striped table-condensed table-hover table-bordered data-tab">
                            <thead>
                                <tr>
                                    <?php
                                    foreach($tableFields as $tfield){
                                        echo "<th>".$tfield."</th>".chr(13);
                                    }
                                    ?>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                
                                foreach($this->table_data as $actUUID => $actRecord){
                                    echo "<tr>".chr(13);
                                    foreach($actRecord as $field=>$value){
                                        echo "<td>";
                                        if ($field == "label"){
                                            echo "<a href=\"".$host."/subjects/".$actUUID."\">".$value."</a>";
                                        }
                                        else{
                                            echo $value;
                                        }
                                        echo "</td>";
                                    }
                                    echo "</tr>".chr(13);
                                }
                                
                                
                                ?>
                            </tbody>
                        </table>
                </div>
            </div>
        </div>
        
        <?php echo $this->render('footer.phtml'); //reader document footer ?>
    </body>
</html>
