
<?php
$requestURI = $this->requestURI;
$host = OpenContext_OCConfig::get_host_config();
header('HTTP/1.0 503 Service Unavailable');
header('Retry-After: '.OpenContext_UserMessages::solrResartEstimate());
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
      <title>Open Context 503 (Service Not Available) Error</title>
      
      
      <link href="/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" /> 
		  <link href="/css/about-rev2.css" rel="stylesheet" type="text/css" /> 
		
      <link rel="shortcut icon" href="/images/layout/oc-favicon.ico" type="image/x-icon" />
		 <script src="<?php echo $host; ?>/js/jquery/jquery-1.7.2.min.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-transition.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-carousel.js" type="text/javascript"></script>
	 <script src="https://www.google.com/jsapi?key=<?php echo $GoogleAPIkey; ?>" type="text/javascript"></script>
    
	 <script type="text/javascript">
        <!--
        
        $('.carousel').carousel();
        
        -->
    </script>

	 <?php echo $this->render('news-widget-js.phtml'); //render javascript for displaying news feeds ?>

	 </head>
    
<body>

<!-- 
    Logo,
-->    
<?php echo $this->render('header.phtml'); //reader document top ?>
   
<!-- 
    Navigation tabs, search box
-->
<?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>


<div id="main">
    <div id="main_content">
		  <div id="main_row">
				<div id="left_sidebar">
					 <div id="gksm-custom-menu-widget-3" class="widget gksm-custom-menu-widget">
						  <h2 class="widgettitle">About:</h2>
						  <div class="submenu-widget submenu-widget-projects">
								<?php echo OpenContext_NavMenus::AboutNavMenu("index", $host); ?>
						  </div>
					 </div>
				<?php echo $this->render('news-widget-dom.phtml'); //render news-widget-dom area ?>
				</div><!-- End Left Sidebar div -->
				
				<div id="right_sidebar">
					 <div id="pageTop">
						  <div id="pageIntro">
								<h1 style="text-align:center;">Service Not Available Error</h1>
								<p>Open Context is down for the time being! Please check back again later (after 45 seconds or so).
								</p>
								<p>Open Context often has periods of high demand. Sometimes this demand causes the
								<a href="http://lucene.apache.org/solr/">Solr</a> index
								to crash. If you are seeing this page, Solr has likely crashed and Open Context will
								have emailed the system administrators notifying them of the problem.
								</p>
								<p>Open Context automatically monitors the health of its Solr index. It will restart Solr in the event
								of a crash. Please try your search after 45 seconds or so, to allow time for the index to restart.</p>
								<p>If the problem persists, there is probably an error or bug in the way Open Context makes a query to
								Solr to respond to your request. Please let us know by reporting an error to our
								<a href="https://github.com/ekansa/open-context-code/issues">GitHub</a>
								open source code repository.
								</p>
								<div class="fourOhFour">
									 <p class="big-code"><?php echo $requestURI; ?></p>
									 <div class="fourOhFour-img">
										  <img src="http://farm1.staticflickr.com/28/93569705_1c562b413a.jpg" title="A little humor for a sad subject" alt="Sad 503 graphic" />
										  <p>Image Source: <a href="http://www.flickr.com/photos/racatumba/93569705/sizes/m/in/photostream/" title="Flickr Link">Racatumba</a> via Flickr (Creative Commons Share-a-like License)</p>
									 </div>
								</div>
						  </div>
					 </diV>
				</div>
				<!-- end right side div -->
		  </div>
		  <!-- end main row div -->
    </div>
	 <!-- end main content div -->
	
    
</div> <!-- end main div -->	 
	 <?php echo $this->render('footer.phtml'); //reader document footer ?>
	
</body>
</html>

