<?php
// used to help create hyperlinks; set to current hostname.

function URIescape($uri){
    return str_replace("&", "&amp;", $uri);
}


$host = OpenContext_OCConfig::get_host_config();

define ('HOST', $host);

$auth = Zend_Auth::getInstance();
if (!$auth->hasIdentity()){
    $displayName = false;
}
else{
    $identity = $auth->getIdentity();
    $displayName = $identity->name;
}


$requestURI = $this->requestURI;
$request_array = explode('?', $requestURI, 2);
//array explode  ( string $delimiter  , string $string  [, int $limit  ] )

if (substr_compare($request_array[0], '/' , -1)) {  // if the uri doesn't end in a slash (minus query parameters), 
    $request_array[0] = $request_array[0] . '/';  // add one
}


if (isset($request_array[1])) { // if there are query parameters,
    $request_array[1] = "?" . $request_array[1];  // prepend a '?' to the set of parameters since we exploded on the '?' to get this string.
    //echo $request_array[1]; // for testing
} else {
    $request_array[1] = null;
}




$requestParams = $this->requestParams;
if(!isset($requestParams["q"])){
    
    $checkParam = $requestParams;
    unset($checkParam["page"]);
    unset($checkParam["recs"]);
    unset($checkParam["sort"]);
    
    if(count($checkParam)>3){
        $searchMessage = "Search this set of data";
    }
    else{
        $searchMessage = "Search all analytic data";
    }
    
    $full_link = $host.$requestURI;
    $full_link  = str_replace("&", "&amp;", $full_link );
    $full_link  = str_replace("&amp;amp;", "&amp;", $full_link );

    $fulltext = '';
    $fulltext .= '<input id="act_uri" type="hidden" value="'.$full_link.'" />';
    $fulltext .= '<span style="text-align:left; margin-left:2%; font-size:.75em;" >';
    $fulltext .= 'Or, type a search term in the box';
    $fulltext .= '</span><br/>';
    $fulltext .= '<div id="b_search_tab">
                    <div id="b_search_row" class="b_search">
                        <div id="b_search_cell_in" >
                                <input name="q" class="bb" type="text" id="q_string" placeholder="Search here..." />
                        </div>
                        <div id="b_search_cell_button">
                                <button class="bb" type="submit" onclick="textSearch();">Search</button>
                        </div>
                    </div>
                </div>
    ';
    
}
else{
    $fulltext = "";
}



$numFound = $this->numFound;
$facets = $this->facets;
$docs = $this->docs;

if(!isset($requestParams["rel"])){
    $link_filter_message = "<p>Some data in Open Context uses shared terminology systems published by experts in various fields:</p>";
    $link_filter_message .= "<ul>".chr(13);
    
    $eolLink = OpenContext_FacetOutput::generateFacetURL($requestParams, "rel", "http://purl.org/NET/biol/ns#term_hasTaxonomy", true);
    $pleiadesLink = OpenContext_FacetOutput::generateFacetURL($requestParams, "rel", "http://gawd.atlantides.org/terms/origin", true);
    
    $link_filter_message .= "<li><a href='$eolLink'>Browse Items</a> with <strong>biological taxa</strong> (from <a href='http://wwww.eol.org'>Encyclopedia of Life</a>)</li>".chr(13);
    $link_filter_message .= "<li><a href='$pleiadesLink'>Browse Items</a> linked to <strong>ancient places</strong> (from <a href='http://pleiades.stoa.org'>Pleaides</a>)</li>".chr(13);
    $link_filter_message .= "<li><a href='../about/concepts#linked-data'><em>More about Linked Data in Open Context</em></a></li>".chr(13);
    $link_filter_message .= "</ul>".chr(13);
}
else{
    $link_filter_message = "<p><a href='../about/concepts#linked-data'><em>More about Linked Data in Open Context</em></a></p>".chr(13);
}

$filter_output = OpenContext_FacetOutput::make_filters_html($requestParams, $host);


$facet_fields = $facets["facet_fields"];
$facet_queries = $facets["facet_queries"];
$extendedFacets = true; //show more available facets 


//do advanced search interface
if(substr_count($requestURI, "advanced=true")>0){
    $advanced = true;
}
else{
    $advanced = false;
}

if($numFound>0){
    $facet_output = OpenContext_FacetOutput::facets_available($extendedFacets, $facet_fields, $facet_queries, $requestParams, $request_array, $host, $advanced);
}
else{
    $facet_output = "(No results to this query, please try other search options)";
}



$googleURI = "";
$facetAtomURI = "";
$openSearchURI = "";


?>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
        <title><?php echo 'Open Context Browse: ('.$numFound.' Items Showing)'; ?></title>
        <link rel="shortcut icon" href="/images/general/oc_favicon.ico" type="image/x-icon" />
        
        <!--
        <link href="<?php echo $host; ?>/components/css/browse" rel="stylesheet" type="text/css" /> 
        -->
        <link href="<?php echo $host; ?>/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" /> 
        <link href="<?php echo $host; ?>/css/opencontext-browse-rev2.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/atomresults.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/rounded_corners.css" rel="stylesheet" type="text/css" />
        
        <link rel="alternate" type="application/atom+xml" title="Atom facet feed" href="<?php echo URIescape($this->facetURI_Atom); ?>" />
        <link rel="alternate" type="application/atom+xml" title="Atom feed of results" href="<?php echo URIescape($this->currentAtom); ?>" />
        
        <link rel="first" type="application/atom+xml" title="Atom feed of results" href="<?php echo URIescape($this->firstPage_XHTML); ?>" />
        <?php
            if($this->prevPage_XHTML != false){
                echo '<link rel="prev" type="application/atom+xml" title="Atom feed of results" href="'.URIescape($this->prevPage_XHTML).'" />'.chr(13);
            }
            if($this->nextPage_XHTML != false){
                echo '<link rel="next" type="application/atom+xml" title="Atom feed of results" href="'.URIescape($this->nextPage_XHTML).'" />'.chr(13);
            }
        ?>
        
        <link rel="last" type="application/atom+xml" title="Atom feed of results" href="<?php echo URIescape($this->lastPage_XHTML); ?>" />
        <link rel="search" type="application/opensearchdescription+xml" href="<?php echo $openSearchURI; ?>" title="Open Context Web Search" />
        <script src="<?php echo $host; ?>/components/js/browse" type="text/javascript"></script>
        
        <script type="text/javascript">
        <!--
        
        function makeGeoTile(id, link, count, swLat, swLon, neLat, nwLon){
            this.id = id;
            this.link = link;
            this.count = count;
            this.swLat;
            this.swLon;
            this.neLat;
            this.nwLon;
        }
        
        
        <?php
        
        echo "var baseURI = '".$host.$requestURI."'; \n";
        echo "var contextBase = '".$host.$request_array[0]."'; \n";
        echo "var paramterBase = '".$request_array[1]."'; \n";
        echo "var numItems = ".count($this->spaceResults)."; \n";
        
        echo chr(13).chr(13);
        
        $activeTaxaValue = OpenContext_FacetOutput::active_taxon_value($requestParams); //for local taxonomies
        echo "var activeTaxaValue = '".$activeTaxaValue."'; \n";
        
        echo chr(13);
        $activeRelationValue = OpenContext_FacetOutput::active_taxon_value($requestParams, false); //for linked data relations
        echo "var activeRelationValue = '".$activeRelationValue."'; \n";
        
        if(is_array($this->geoTileFacets)){
            echo chr(13);
            echo "var geoTiles = new Array(); \n";
            $ti = 0;
            foreach($this->geoTileFacets as $tileFacet){
                $id = $tileFacet["linkQuery"];
                $link = $tileFacet["href"];
                $tileCount = $tileFacet["count"];
                $geoBounding = implode(",", $tileFacet["geoBounding"]);
                echo "geoTiles[$ti] = new makeGeoTile('$id', '$link', $tileCount, $geoBounding); \n";
                $ti++;
            }

        }
        
        
        ?>
        
        
        -->
        </script>
        
        <script type="text/javascript">
        <!--
            
     window.onload = function(){
        ConvertRowsToLinks("item_list_tab");
        //AddRowLinks();
      }
      
      function ConvertRowsToLinks(xTableId){
            convertRows(xTableId, "item_row");
            convertRows(xTableId, "item_row_shade");
      }


      function convertRows(xTableId, rowClass){
        var rows = document.getElementById(xTableId).getElementsByClassName(rowClass);
        for(i=0; i < rows.length; i++){
          var link = rows[i].getElementsByTagName("a")
          if(link.length >= 1){
            rows[i].onclick = new Function("document.location.href='" + link[0].href + "'");
            rows[i].onmouseover = new Function("this.style.cursor = 'pointer'");
            rows[i].onmouseout = new Function("this.style.cursor = 'default'");
          }
        }
      }
      
      
      
      function openList(listId){
            var displayControl = listId + "control";
            var displayStatus = document.getElementById(listId).style.display;
            if( displayStatus == "none"){
                document.getElementById(listId).style.display = "";
                document.getElementById(displayControl).innerHTML = "<em>(Hide list below)</em>";
            }
            else{
                document.getElementById(listId).style.display = "none";
                document.getElementById(displayControl).innerHTML = "More...";
            }
      
      }

      -->
        </script>
    </head>
    <body>
    
<!-- 
    Logo,
-->    
<?php echo $this->render('header.phtml'); //reader document top ?>
   
<!-- 
    Navigation tabs, search box
-->
<?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>

    
 
<!--
BEGIN Container for main page content
--> 
    <div id="main"> 
        <!--Begin code for showing available facets-->
        <div id="main_content">
            <div id="main_row">
                <div id="left_cont">
                    <div id="filter_options">
                        <h3>Browse and Filter</h3>
                        <p>Click on one of the links below to further limit your view of <em>analytic data</em> in Open Context.</p>
                        <div id="search_sort_block">
                        <?php echo  $fulltext; ?>
                        
                        <!-- facet sorting options -->
                        <?php
                        
                        $SortOptionsObj = New SortOptions;
                        $SortOptionsObj->requestParams = $requestParams;
                        echo $SortOptionsObj->makeFacetSortLinks();
                        
                        ?>
                        </div>
                    </div>
                    <div id="all_facets">
                            <?php echo $facet_output; ?>
                        <br/>
                            <?php
                            
                            $pelagios = New Pelagios;
                            $pelagios->initialize($requestParams);
                            $pelagios->getRelated();
                            $pelagios->displayPelagiosData();
                            
                            echo $pelagios->HTMLoutput;
                            
                            ?>
                        <br/>
                        <p>View in <a href="<?php echo URIescape($this->facetURI_KML); ?>">GoogleEarth</a></p>
                        <p>Get in <a href="<?php echo URIescape($this->facetURI_Atom); ?>">Atom</a></p>
                        <br/>
                            <?php echo $link_filter_message; ?>
                    </div>
                </div>
                <div id="right_cont">   
                    <div id="selected_filters" >
                        <p>Open Context currently has <strong><?php echo $numFound; ?></strong> items, filtered by the following criteria:</p>
                        <div>
                            <?php echo $filter_output; ?>
                        </div>
                        
                        <div style="text-align:right;">
                        <?php
                        
                        $tableMax = OpenContext_OCConfig::get_maxExport();
                        if($numFound <= $tableMax && $displayName != false){
                            echo "<br/>";
                            echo '<p class="tinyText">'.$displayName.', <a href="'.$host.'/createtab/export-table?setURI='.urlencode($host.$requestURI).'">click here</a> to export these search results to a table.</p>';
                           
                           /*
                            echo '<form action="'.$host.'/createtab/export-table" method="post">
                                    <input type="hidden" value="'.$host.$requestURI.'" name="setURI" />
                                    <input type="submit" value="Export to table" />
                                    </form>';
                           */
                        }
                        elseif($numFound > 0 && $numFound > $tableMax && $displayName != false){
                            echo "<br/>";
                            echo '<p class="tinyText">'.$displayName.', please filter your selection to '.$tableMax.' items or less in order to export data to a table.</p>';
                        }
                        elseif($numFound > 0 && $numFound <= $tableMax && !$displayName){
                            echo "<br/>";
                            echo '<p class="tinyText">Please <a href="'.$host.'/auth/" title="User Account Options">login</a> to export this custom selection of data to a table.</p>';
                        }
                        
                        ?>
                        </div>
                        <?php
                        
                        if($numFound >0){
                        
                        ?>
                        
                        <p class="tinyText" style="text-align:right;">Last Updated: <em><?php echo date("F j, Y, g:i a", strtotime($this->lastUpdate)); ?></em></p>
                        <p class="tinyText" style="text-align:right;">
                            <?php
                            echo '<a href="http://maps.google.com/?q='.urlencode($this->facetURI_KML).'">View a map summary</a>';
                            ?>
                        </p>
                        <?php
                        }//end case of search results above zero ?>
                    </div>
                    <div id="item_list_outer">
                        
                        <div id="paging_outer">
                            <div id="paging_tab">
                                <div id="paging_row">
                                    <div class="paging_cell">
                                        <?php
                                        
                                        if($this->firstPage_XHTML && $this->firstPage_XHTML != $this->currentXHTML){
                                            $linkClass = "pager_active";
                                            $pageLink = "<a href=\"".$this->firstPage_XHTML."\" class=\"btn btn-small btn-primary\" title=\"Go to the first page of results\" >|&larr;</a>";
                                        }
                                        else{
                                            $linkClass = "pager_inactive";
                                            $pageLink = "|&larr;";
                                            $pageLink = "<a href=\"\" class=\"btn btn-small btn-primary disabled\">|&larr;</a>";
                                        }
                                        
                                        ?>
                                        <div class="<?php echo $linkClass; ?>" >
                                            <?php echo $pageLink; ?>
                                        </div>
                                    </div>
                                    <div class="paging_cell">
                                        <?php
                                        
                                        if($this->prevPage_XHTML){
                                            $linkClass = "pager_active";
                                            $pageLink = "<a href=\"".$this->prevPage_XHTML."\" class=\"btn btn-small btn-primary\" title=\"Go to the previous page of results\" >&larr;</a>";
                                        }
                                        else{
                                            $linkClass = "pager_inactive";
                                            $pageLink = "&larr;";
                                            $pageLink = "<a href=\"\" class=\"btn btn-small btn-primary disabled\">&larr;</a>";
                                        }
                                        
                                        ?>
                                        <div class="<?php echo $linkClass; ?>" >
                                            <?php echo $pageLink; ?>
                                        </div>
                                    </div>
                                    <div id="paging_cell_center">
                                        <div id="paging_ct_tab">
                                            <div id="paging_ct_row">
                                                <div id="paging_ct_cell_pageNum">
                                                    <?php
                                                        if(isset($requestParams["page"])){
                                                            $page = $requestParams["page"];
                                                        }
                                                        else{
                                                            $page = 1;
                                                        }
                                                        
                                                        $numRecs = $this->number_recs;
                                                        $lastPage = intval($this->numFound/$numRecs);
                                                        if($lastPage * $numRecs < $numFound){
                                                            $lastPage++;
                                                        }
                                                        echo "Page $page of $lastPage";
                                                        echo ", sorted by ".$this->sorting;
                                                    ?>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- Add result sort options -->
                                        <?php echo $SortOptionsObj->makeSortLinks(); ?>
                                    </div>
                                    <div class="paging_cell">
                                        <?php
                                        
                                        if($this->nextPage_XHTML){
                                            $linkClass = "pager_active";
                                            $pageLink = "<a href=\"".$this->nextPage_XHTML."\" class=\"btn btn-small btn-primary\" title=\"Go to the next page of results\" >&rarr;</a>";
                                        }
                                        else{
                                            $linkClass = "pager_inactive";
                                            $pageLink = "&rarr;";
                                            $pageLink = "<a href=\"\" class=\"btn btn-small btn-primary disabled\">&rarr;</a>";
                                        }
                                        
                                        ?>
                                        <div class="<?php echo $linkClass; ?>" >
                                            <?php echo $pageLink; ?>
                                        </div>
                                    </div>
                                    <div class="paging_cell">
                                        <?php
                                        
                                        if($this->lastPage_XHTML && $this->lastPage_XHTML != $this->currentXHTML){
                                            $linkClass = "pager_active";
                                            $pageLink = "<a href=\"".$this->lastPage_XHTML."\" title=\"Go to the last page of results\" class=\"btn btn-small btn-primary\" >&rarr;|</a>";
                                        }
                                        else{
                                            $linkClass = "pager_inactive";
                                            $pageLink = "&rarr;|";
                                            $pageLink = "<a href=\"\" class=\"btn btn-small btn-primary disabled\">&rarr;|</a>";
                                        }
                                        ?>
                                        <div class="<?php echo $linkClass; ?>" >
                                            <?php echo $pageLink; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div id="item_list_tab">
                        <?php
                        //echo $this->result_output;
                        $spaceResults = $this->spaceResults;
                        $il = 0;
                        foreach($spaceResults["items"] as $resItem){
                            
                            if($il & 1){
                                $rowClass = "item_row_shade";
                            }
                            else{
                                $rowClass = "item_row";
                            }
                        
                        
                        ?>
                            <div class="<?php echo $rowClass; ?>" id="item_row_<?php echo $il; ?>">
                                <div class="item_cell_cl_icon">
                                    <a href="<?php echo $resItem["uri"]; ?>">
                                        <img src="<?php echo $resItem["catIcon"]; ?>" alt="<?php echo $resItem["category"]; ?>" />
                                    </a>
                                </div>
                                <div class="item_cell_proj">
                                    <?php echo $resItem["project"]; ?>
                                </div>
                                <div class="item_cell_name_context">
                                    <span class="item_cat_label"><?php echo $resItem["category"]; ?></span>
                                    <span class="item_label">
                                        <a href="<?php echo $resItem["uri"]; ?>"><?php echo $resItem["label"]; ?></a>
                                    </span>
                                    <?php echo $resItem["context"]; ?>
                                </div>
                                <div class="item_cell_detail">
                                    <?php if($resItem["thumbIcon"] !=  $resItem["catIcon"]){ ?>
                                    <a href="<?php echo $resItem["uri"]; ?>">
                                        <img src="<?php echo $resItem["thumbIcon"]; ?>" alt="Thumbnail for <?php echo $resItem["label"]; ?>" />
                                    </a>
                                    
                                    <?php }//end case with a different thumbnails
                                            elseif(is_array($resItem["var_vals"])){
                                    ?> 
                                            <div class="item_sample_data_tab">
                                               
                                                <?php
                                                    $sd = 0;
                                                    $maxSampleRecs = 3;
                                                    $maxSampleChars = 140;
                                                    $LinkedDataObj = new LinkedDataRef;
                                                    foreach($resItem["var_vals"] as $varKey => $val){
                                                        
                                                        if($sd & 1){
                                                            $sampleRowClass = "item_sample_row_shade";
                                                        }
                                                        else{
                                                            $sampleRowClass = "item_sample_row";
                                                        }
                                                        
                                                        $showVal = strip_tags($val);
                                                        if(strlen($showVal)>$maxSampleChars){
                                                            $showVal = substr($showVal, 0, $maxSampleChars)."...";
                                                        }
                                                        
                                                        if((substr($showVal, 0, 7) == "http://") && mb_stristr($varKey, "http://")){
                                                            $LinkedDataObj->lookup_refURI($showVal);
                                                            $showVal = $LinkedDataObj->refLabel;
                                                            $LinkedDataObj->lookup_refURI(str_replace("Rel: ", "", $varKey));
                                                            $varKey = $LinkedDataObj->refLabel;
                                                        }
                                                        ?>
                                                        
                                                        <div class="<?php echo $sampleRowClass; ?>">
                                                            <div class="item_sample_var">
                                                                <span><?php echo $varKey; ?></span>
                                                            </div>
                                                            <div class="item_sample_val">
                                                                <span><?php echo $showVal; ?></span>
                                                            </div>
                                                        </div>
                                                        <?php
                                                        
                                                        $sd++;
                                                        
                                                        if($sd >= $maxSampleRecs){
                                                            break;
                                                        }
                                                    }
                                                ?>
                                            </div>
                                            
                                    <?php           
                                            }//end case where thumb and category icon are the same
                                    ?>
                                </div>
                            </div>
                        <?php
                        $il++;
                        } //end loop
                        
                        //echo print_r($this->docs);
                        ?>
                        </div>
                    </div>
                </div>
            </div>  
   
        <!--
        END of div container for placing main page content
        -->
        </div>
    
    </div>

    <div id="bottomBuffer">

    </div>
    <?php echo $this->render('footer.phtml'); //reader document footer ?>
    </body>
</html>    