<?php

// used to help create hyperlinks; set to current hostname.
//$host = "http://ishmael.ischool.berkeley.edu";
//$host = "http://opencontext";
$host = OpenContext_OCConfig::get_host_config();
$GMapURI = OpenContext_OCConfig::get_google_api();
$GMapURI = "http://maps.google.com/maps?file=api&v=2&key=".$GMapURI;


define ('HOST', $host);


$unfold_vals = $this->unfold_vals;
$requestURI = $this->requestURI;
$requestParams = $this->requestParams;
$solrParams = $this->solrParams;
$extendfacets = $this->extendedFacets;
$unfold_vals = $this->unfold_vals;
$queryString = $this->queryString;
//echo $queryString." <br/><br/>";


//echo var_dump($extendfacets);
//echo var_dump($unfold_vals);
//echo var_dump($solrParams);
//$solrqTerm = $solrParams["fq"];
//echo $solrqTerm ." <br/><br/>";


$request_array = explode('?', $requestURI, 2);
//array explode  ( string $delimiter  , string $string  [, int $limit  ] )

if (substr_compare($request_array[0], '/' , -1)) {  // if the uri doesn't end in a slash (minus query parameters), 
    $request_array[0] = $request_array[0] . '/';  // add one
}


if (isset($request_array[1])) { // if there are query parameters,
    $request_array[1] = "?" . $request_array[1];  // prepend a '?' to the set of parameters since we exploded on the '?' to get this string. 
    //echo $request_array[1]; // for testing
} else {
    $request_array[1] = null;
}


$requestURI = str_replace("/sets","/sets/",$requestURI);
$requestURI = str_replace("/sets//","/sets/",$requestURI);
$requestURI = str_replace(".map","",$requestURI);

/* this complex check is needed because the request parameter 'module' with the value 'default' is present if the user selects a
 * non-context parameter.  The reason for this behavior is not clear.  
 */
if ((count($requestParams) < 3)  ||  ((count($requestParams) < 4) && (in_array('module', array_keys($requestParams))))) {

    $filter_message = "(View is not filtered)";
    
    $googleURI = str_replace("/sets","/sets/facets/.kml",$requestURI);
    $googleURI = str_replace("/sets/","/sets/facets/.kml",$requestURI);
    $facetAtomURI = str_replace("/sets","/sets/facets/.atom",$requestURI);
    $facetAtomURI = str_replace("/sets","/sets/facets/.atom",$requestURI);
    $resultAtomURI = $requestURI.".atom";
    $searchMessage = "Search Open Context";
}//end case with no filters
else{
    
    $filter_message = "";
    $searchMessage = "Search this Set";
    
    $requestURI = str_replace("[", "%5B",$requestURI);
    $requestURI = str_replace("]", "%5D",$requestURI);
    
    $googleURI = str_replace("?",".kml?",$requestURI);
    $googleURI = str_replace("/sets/","/sets/facets/",$googleURI);
    $facetAtomURI = str_replace("?",".atom?",$requestURI);
    $resultAtomURI = $facetAtomURI;
    $facetAtomURI = str_replace("/sets/","/sets/facets/",$facetAtomURI);
    
    if(substr_count($googleURI,".kml?")<1){
        $googleURI .= ".kml";
        $facetAtomURI .= ".atom";
        $resultAtomURI = $requestURI.".atom";
    }
    
    if(substr_count($googleURI,"facets/.kml")<1){
        $googleURI = str_replace("/.kml",".kml",$googleURI);
        $facetAtomURI = str_replace("/.atom",".atom",$facetAtomURI);
        $resultAtomURI = str_replace("/.atom",".atom",$resultAtomURI);
    }
}//end case with filter parameters

$resultAtomURI = $host.$resultAtomURI;
$facetAtomURI = $host.$facetAtomURI;

$resultAtomURI = str_replace("&", "&amp;", $resultAtomURI);
$resultAtomURI = str_replace("&amp;amp;", "&amp;", $resultAtomURI);
$facetAtomURI = str_replace("&", "&amp;", $facetAtomURI);
$facetAtomURI = str_replace("&amp;amp;", "&amp;", $facetAtomURI);
$googleURI = str_replace("&", "&amp;", $googleURI);
$googleURI = str_replace("&amp;amp;", "&amp;", $googleURI);

$openSearchURI = str_replace("sets/facets", "sets/search", $facetAtomURI);
$openSearchURI = str_replace(".atom", ".xml", $openSearchURI);
$openSearchURI = str_replace("search//", "search/", $openSearchURI);
$openSearchURI = str_replace(".xml/", ".xml", $openSearchURI);

$openSearchURI = $host."/sets/search/.xml";
                             
//echo $resultAtomURI."<br/>";
//$googleURI = str_replace("[", "%5B",$googleURI);
//$googleURI = str_replace("]", "%5D",$googleURI);
//$facetAtomURI = str_replace("[", "%5B",$facetAtomURI);
//$facetAtomURI = str_replace("]", "%5D",$facetAtomURI);
//$resultAtomURI = str_replace("[", "%5B",$resultAtomURI);
//$resultAtomURI = str_replace("]", "%5D",$resultAtomURI);

$numFound = $this->numFound;

//this gets rid of the page parameter so that links to new faceted queries are valid
$pageFixing = OpenContext_FacetOutput::remove_page_parameter($requestParams, $request_array);
$requestParams = $pageFixing["new_params"];
$request_array = $pageFixing["new_request"];

$filter_output = $filter_message;
$filter_output .= OpenContext_FacetOutput::facet_removal_context_links($requestParams, $request_array, $host);
$filter_output .= OpenContext_FacetOutput::facet_removal_links($requestParams, $request_array, $host);


// get the facet counts 
$facet_fields = $this->facet_fields;
$facet_queries = $this->facet_queries;
$extendedFacets = $this->extendedFacets; //show more available facets 

$facet_output = OpenContext_FacetOutput::facets_available($extendedFacets, $facet_fields, $facet_queries, $requestParams, $request_array, $host);

$result_output = OpenContext_ResultAtom::atom_to_html($resultAtomURI);
 
//$result_output = file_get_contents($resultAtomURI);


//add a full text form?
if(substr_count($requestURI,"q=")<1){
    $full_link = $host.$requestURI;
    $full_link  = str_replace("&", "&amp;", $full_link );
    $full_link  = str_replace("&amp;amp;", "&amp;", $full_link );

    $fulltext = '<p class="bodyText">Or, type a search term in the box below (works like Google):</p>'.chr(13);
    //$fulltext .= '<form id="searchbox" name="form4" method="get" action="'.$requestURI.'">'.chr(13);
    $fulltext .= '<input id="act_uri" type="hidden" value="'.$full_link.'" />';
    $fulltext .='<input name="q" type="text" id="q_string" size="30" maxlength="100" class="bodyText" alt="Enter full-text search term(s)" />'.chr(13);
    $fulltext .='<input type="submit" id="submit" value="'.$searchMessage.'" class="bodyText" alt="Run full-text search" onclick="textSearch();"/>'.chr(13);
    //$fulltext .='</form>';
}
else{
    $fulltext = "";
}





@$minDate = min($facet_fields["time_start"]);
@$maxDate = max($facet_fields["time_end"]);
$dateSpan = $maxDate - $minDate;

$gg=0;
foreach($facet_fields["geo_lat"] as $geoKey=>$value){
    if($gg==0){
        $maxGeoLat = $geoKey;
        $minGeoLat = $geoKey;
    }
    if($geoKey>$maxGeoLat){
        $maxGeoLat = $geoKey;
    }
    if($geoKey<$minGeoLat){
        $minGeoLat = $geoKey;
    }
    $gg++;
}

$gg=0;
foreach($facet_fields["geo_long"] as $geoKey=>$value){
    if($gg==0){
        $maxGeoLong = $geoKey;
        $minGeoLong = $geoKey;
    }
    if($geoKey>$maxGeoLong){
        $maxGeoLong = $geoKey;
    }
    if($geoKey<$minGeoLong){
        $minGeoLong = $geoKey;
    }
    $gg++;
}

$midGeoLat = ($maxGeoLat + $minGeoLat)/2;
$midGeoLong = ($maxGeoLong + $minGeoLong)/2;
$MaxDist = pow((pow(($maxGeoLat - $minGeoLat),2) + pow(($maxGeoLong - $minGeoLong),2)), .5)+.00000001;
$zoomLevel = round((5000/(100*$MaxDist)),0);
if($zoomLevel<1){
    $zoomLevel = 1;
}
if($zoomLevel>17){
    $zoomLevel = 17;
}

if($dateSpan>1500){
    $bandInfo = '
    {
                      width:          "50%",
                      intervalUnit:   Timeline.DateTime.CENTURY,
                      intervalPixels: 100
                    },
                    {
                       width:          "50%",
                       intervalUnit:   Timeline.DateTime.MILLENNIUM,
                   intervalPixels: 65,
                       showEventText:  true,
                       trackHeight:    0.4,
                       trackGap:       0.2
                    }
    ';
}
else{
    
    $bandInfo = '
    {
                      width:          "50%",
                      intervalUnit:   Timeline.DateTime.CENTURY,
                      intervalPixels: 100
                      trackHeight:    1
                    }
    ';   
}




?>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
        <title><?php echo 'Open Context Browse: ('.$numFound.' Items Showing)'; ?></title> 
        <link href="/css/opencontext_style.css" rel="stylesheet" type="text/css" /> 
        <link href="/css/opencontext_browse.css" rel="stylesheet" type="text/css" />
        <link href="/css/atomresults.css" rel="stylesheet" type="text/css" />
        <link href="/css/default_banner.css" rel="stylesheet" type="text/css" />
        <link rel="alternate" type="application/atom+xml" title="Atom facet feed" href="<?php echo $facetAtomURI; ?>" />
        <link rel="search" type="application/opensearchdescription+xml" href="<?php echo $openSearchURI; ?>" title="Open Context Web Search" />
        
        <script src="<?php echo $GMapURI; ?>" type="text/javascript"></script> 
        <link href="/css/timemap.css" type="text/css" rel="stylesheet"/> 
        <style> 
            div#timelinecontainer{ height: 210px; }
            div#mapcontainer{ height: 400px; }
        </style>
        
        <script type="text/javascript">
        var map;
        var geoXml;
        function TMonLoad() {
            
            
            if (GBrowserIsCompatible()) {
                map = new GMap2(document.getElementById("map")); 
                geoXml = new GGeoXml("<?php echo $host.$googleURI; ?>");
                map.addControl(new GLargeMapControl());
                map.setMapType(G_HYBRID_MAP);
                map.setCenter(new GLatLng(0, 45), 2);
                map.addControl(new GLargeMapControl());
                map.addControl(new GMapTypeControl());
                map.addOverlay(geoXml);
                animate();
            }
            //ConvertRowsToLinks("result_tab");
        }
        
        function animate() {    
            map.panTo(new GLatLng(<?php echo $midGeoLat; ?>, <?php echo $midGeoLong; ?>));
            map.setCenter(new GLatLng(<?php echo $midGeoLat; ?>, <?php echo $midGeoLong; ?>), <?php echo $zoomLevel; ?>);
        }
        
        </script>
        
    </head>
    <body onload="TMonLoad();" onunload="GUnload();">
        
    <div id="oc_logo">
	<a href="<?php echo $host;?>/sets/" title="Home (Browse)"><img alt="Open Context Logo" src="/images/general/oc_logo.jpg" border="0" ></img></a>
    </div>
    <div id="oc_tagline">
	<img alt="Open Context Tagline" src="/images/general/oc_tagline.jpg" ></img>
    </div>
    <div id="oc_beta">
	<img alt="Beta Stamp" src="/images/general/oc_betastamp.jpg" ></img>
    </div>
    
    <div id="oc_main_nav">
        <div class="sides"></div>
        <div class="n_act_nav"><a href="<?php echo $host;?>/about/" title="Learn more about Open Context">About</a></div>
        <div class="sides"></div>
        <div class="n_act_nav"><a href="<?php echo $host;?>/projects/" title="Summary of Projects in Open Context">Projects</a></div>
        <div class="sides"></div>
        <div class="act_nav"><a href="<?php echo $host;?>/sets/" title="Explore data">Browse</a></div>
        <div class="sides"></div>
        <div class="n_act_nav"><a href="<?php echo $host;?>/lightbox/" title="Browse images">Lightbox</a></div>
        <div class="sides"></div>
        <div class="n_act_nav"><span title="Coming soon">Tables</span></div>
        <div class="sides"></div>
        <div class="n_act_nav"><span title="Browse to get details of items">Details</span></div>
        <div class="sides"></div>
        <div class="n_act_nav"><span title="Coming soon">My Account</span></div>
    </div>
    
    
        
<!--
BEGIN Container for main page content
--> 
    <div id="main_page"> 
        <!--Begin code for showing available facets-->
        <div id="main_content">
            <div id="left_cont">
                <div id="filter_options" class="bodyText">
                    <p class="bodyText"><strong>Click on one of the links below to further limit your view of items in Open Context.</strong></p>
                        <?php echo  $fulltext; ?>
                    <br/>
                        <?php echo $facet_output; ?>
                            
                    <br/>
                    <p>View in <a href="<?php echo $googleURI; ?>">GoogleEarth</a></p>
                    <p>Get in <a href="<?php echo $facetAtomURI; ?>">Atom</a></p>
                </div>
            </div>
            <div id="right_cont">   
                <div id="selected_filters">
                    <p class="subHeader">Open Context currently has <strong><?php echo $numFound; ?></strong> items, filtered by the following criteria:</p>
                    <p class="bodyText"><?php echo $filter_output; ?></p>
                    <p class="tinyText" style="text-align:right;">Last Updated: <em><?php echo date("F j, Y, g:i a", strtotime(OpenContext_OCConfig::last_update())); ?></em></p>
                    <!--
                    <form action="<?php echo $host."/tables/add"; ?>" method="post">
                        <input type="hidden" value="<?php echo $requestURI; ?>" name="set" />
                        <input type="hidden" value="<?php echo htmlentities($filter_output); ?>" name="filter" />
                        <input type="submit" value="make table" />
                    </form>
                    -->
                </div>
                        
                <br />
                <br />
                        
                <div id="timemap"> 
                    <div id="mapcontainer"> 
                      <div id="map"></div> 
                    </div> 
                </div> 
            </div>
                    
   
        <!--
        END of div container for placing main page content
        -->
        <div id="bottom_cont"> 
          <br /> 
          <br /> 
        </div> 
        <!--
        END Code for showing the database-like content
        -->
   
     </div>
    <br />
    
        <div id="footer"> 
            <div id="w3c_val_logo"> 
              <a href="http://validator.w3.org/check?uri=referer"> 
                <img src="http://www.w3.org/Icons/valid-xhtml10-blue" alt="Valid XHTML 1.0 Transitional" height="31" width="88" /> 
              </a> 
            </div>     
        </div>
   
     </div>
    </body>
</html>    