<?php
$host = OpenContext_OCConfig::get_host_config();

//echo htmlentities($this->solr_out);
$XML = false;
$XML = $this->XML;

if ($XML) {

    //temporary hack to display polygon for
    //reduced precision geospatial data
    $geoJSON = 0;
    if($this->geoJSON != false){
	   $geoJSON = json_encode($this->geoJSON);
    }

    $doc = new DOMDocument();
    $useragent = @$_SERVER['HTTP_USER_AGENT'];

    /*
    if(strstr($useragent,"MSIE")){
        $doc->load("xsl/defaultSpatial.xsl");
    }    
    else{
        $doc->load("xsl/defaultSpatial_rdfa.xsl");
    }
    */
    $doc->load("xsl/rev2-subject.xsl");
    
    $proc = new XSLTProcessor();
    $xslt = $proc->importStylesheet($doc);
    $archaeoMLDoc = new DomDocument();
    $archaeoMLDoc->loadXML($XML->asXML());
    //$XHTMLbody = $proc->transformToXML($archaeoMLDoc);
    $newDom = $proc->transformToDoc($archaeoMLDoc);
    $newDom->formatOutput = true;
    //$rootNode = $newDom->getElementsByTagName("div")->item(0);
    //$XHTMLbody = $newDom->saveXML($rootNode);
	 $XHTMLbody = $newDom->saveHTML();
	 $XHTMLbody = str_replace('<!DOCTYPE div PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">','', $XHTMLbody); // a hack to get rid of this for older php

	 
}
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">

    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    
    <title>Open Context view of Item: <?php echo $this->label; ?></title>
    
    <link rel="shortcut icon" href="/images/layout/oc-favicon.ico" type="image/x-icon" />
    <link rel="alternate" type="application/atom+xml" tilte="Atom representation" href="<?php echo $host; ?>/subjects/<?php echo $this->itemUUID; ?>.atom" />
	 <link rel="alternate" type="application/xml" tilte="XML representation" href="<?php echo $host; ?>/subjects/<?php echo $this->itemUUID; ?>.xml" />
	 <link rel="alternate" type="application/rdf+xml" tilte="RDF-XML representation" href="<?php echo $host; ?>/subjects/<?php echo $this->itemUUID; ?>.rdf" />
    <link href="<?php echo $host; ?>/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $host; ?>/css/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $host; ?>/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $host; ?>/css/subject-rev2.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $host; ?>/css/general-item-rev2.css" rel="stylesheet" type="text/css" />
	 <link href="<?php echo $host; ?>/css/bibliographic.css" rel="stylesheet" type="text/css" />
    <script src="<?php echo $host; ?>/js/jquery/jquery-1.7.2.min.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-transition.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-tab.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-dropdown.js" type="text/javascript"></script>
	 <?php
		  $doMap = true;
		  if($doMap || $this->projectUUID == "64013C33-4039-46C9-609A-A758CE51CA49" || $this->projectUUID == "81204AF8-127C-4686-E9B0-1202C3A47959"){
				$doMap = true;
	 ?>
	 <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.css" />
	 <script src="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.js"></script>
	 <script src="http://maps.google.com/maps/api/js?v=3.2&sensor=false"></script>
    <script src="http://opencontext.org/js/map-browse/GoogleLayers.js" type="text/javascript"></script>
	 <style>
		  
		  .leaflet-popup{
				max-width: 150px;
		  }
		  
	 </style>
	 
	 
	 <?php
		  }
		  else{
		  //put in the awld stuff
	 ?>
    <script src="http://isawnyu.github.com/awld-js/lib/requirejs/require.min.js" type="text/javascript"></script>
    <script src="http://isawnyu.github.com/awld-js/awld.js?autoinit" type="text/javascript"></script>
	 <?php
		  }//end case with awld
	 ?>
    <script type="text/javascript">
        <!--
        
        $('.dropdown-toggle').dropdown()
        
        
        -->
    </script>
   
    </head>
    <body>
        <!-- 
            Logo,
        -->    
        <?php echo $this->render('header.phtml'); //reader document top ?>
           
        <!-- 
            Navigation tabs, search box
        -->
        <?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>
    
        <?php echo $XHTMLbody; ?>
        
        <div id="bottomBuffer">
        </div>
        </div>
        <?php echo $this->render('footer.phtml'); //reader document footer ?>
        <script type="text/javascript">
        <!--
         $('#obsTabs a').click(function (e) {
            e.preventDefault();
            $(this).tab('show');
          });
         
            var url = document.location.toString();
            if (url.match('#')) {
                $('.nav-tabs a[href=#'+url.split('#')[1]+']').tab('show') ;
                scroll(0,0);
            }
            
            // Change hash for page-reload
            $('.nav-tabs a').on('shown', function (e) {
                window.location.hash = e.target.hash;
                scroll(0,0);
            })
         -->
		  </script>
		  
		  <?php if($doMap){
		  ?>
		  
		  <script type="text/javascript">
				var actLatDom = document.getElementById("geo-lat");
				var actLonDom = document.getElementById("geo-lon");
				var actGeoNoteDom = document.getElementById("geo-note");
				var actGeoSourceDom = document.getElementById("geo-source");
				var actLat = actLatDom.innerHTML;
				var actLon = actLonDom.innerHTML;
				var actGeoNote = actGeoNoteDom.innerHTML;
				var actGeoSource = actGeoSourceDom.innerHTML;
				var geoJSON = <?php echo $geoJSON; ?>;
		  
				var satelliteView = 1;
				if (!geoJSON) {
				    var mapZoom = 6;
				    var popUpMessage = "<div><p class=\"tinyText\">[Lat: "+ actLat + ", Lon: " + actLon  +"] " + actGeoNote + " " + actGeoSource + "</p></div>";
				}
				else{
				    var mapZoom = 7;
				    var popUpMessage = "<div><p class=\"tinyText\">Nearby [Lat: "+ Math.round(actLat*100)/100 + ", Lon: " + Math.round(actLon*100)/100  +"] " + actGeoNote + " " + actGeoSource + "</p></div>";
		  
				}
				var map = L.map('map').setView([actLat, actLon], mapZoom);
				var bounds = new L.LatLngBounds();
				var osmTiles = L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
            });
            
            var mapboxTiles = L.tileLayer('http://api.tiles.mapbox.com/v3/ekansa.map-tba42j14/{z}/{x}/{y}.png', {
                attribution: '&copy; <a href="http://MapBox.com">MapBox.com</a> '
            });
            
            var ESRISatelliteTiles = L.tileLayer('http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
                attribution: '&copy; <a href="http://services.arcgisonline.com/">ESRI.com</a> '
            });
            
            var gmapRoad = new L.Google('ROADMAP');
            var gmapSat = new L.Google('SATELLITE');
            var gmapTer = new L.Google('TERRAIN');
            
            var baseMaps = {
                "Google-Terrain": gmapTer,
                "Google-Satellite": gmapSat,
                "ESRI-Satellite": ESRISatelliteTiles,
                "Google-Roads": gmapRoad,
                "OpenStreetMap": osmTiles,
                "MapBox": mapboxTiles,
            };
           
            if(satelliteView){
                map.addLayer(gmapSat);
            }
            else{
                map.addLayer(gmapTer);
            }
            map._layersMaxZoom = 20;
            L.control.layers(baseMaps).addTo(map);
				
				
				var popup = L.popup()
					 .setContent(popUpMessage);
				// geoJSON = false;
				if (!geoJSON) {
				    var marker = L.marker([actLat, actLon]).addTo(map).bindPopup(popup);
				}
				else{
				    var polyStyle = {
					   "color": "#ff7800",
					   "weight": 2,
					   "opacity": 0.85,
					   "fillOpacity": 0.5
				    };			    
				    L.geoJson(geoJSON, {style: polyStyle}).addTo(map).bindPopup(popup);
				}
				

				
		  </script>
		  <?php } //end dinaa mapping
		  ?>
		  
		  
    </body>
</html>

