<?php
$host = OpenContext_OCConfig::get_host_config();
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
      <title>About Open Context</title>
      <link rel="schema.DC" href="http://purl.org/dc/terms" />
      <meta name="DC.title" content="About Open Context" />
      <meta name="DC.created" content="January 1, 2010" />
      <meta name="DC.date" content="January 1, 2011" />
      <meta name="DC.creator" content="Open Context Editors" />
      
      <link href="/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
      <link href="/css/oc-about-layout.css" rel="stylesheet" type="text/css" /> 
	<link href="/css/bootstrap.css" rel="stylesheet" type="text/css" />
	<link href="/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" /> 
      
      <link rel="shortcut icon" href="/images/layout/oc-favicon.ico" type="image/x-icon" />
    </head>
    
<body>

<!-- 
    Logo,
-->    
<?php echo $this->render('header.phtml'); //reader document top ?>
   
<!-- 
    Navigation tabs, search box
-->
<?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>



    <div id="main">
	<div id="pageTop">
            <div id="pageIntro">
                <h2 style="text-align:center;">About Open Context</h2>
                
                <div style="margin:10px;">
                    <p class="bodyText">Open Context is a free, open access resource for the electronic
                    publication of primary field research from archaeology and related disciplines.
                    It emerged as a means for scholars and students to easily find and reuse content
                    created by others, which are key to advancing research and education.
                    Open Context's technologies focus on ease of use, open licensing frameworks,
                    informal data integration and, most importantly, data portability. Currently,
                    we are building up an extensive and diverse body of content and exploring
                    different ways of visualizing and remixing it. Please check in frequently
                    for updates and, as always, feel free to drop us a line with comments or
                    suggestions. </p>
                </div>
            </div>
            <div class="nav_area">
                    <p class="bodyText"><em>More About Open Context:</em></p>
                    <?php echo OpenContext_NavMenus::AboutNavMenu("index", $host); ?>
                    <br/>
            </div>
            <div id="pageTopEnd">
                <br/>
            </div>
        </div>
        
        
        <br/>
        <div style="margin:10px;">
            <h3>Key Features</h3>
	      
	    <p class="bodyText">Open Context's main development efforts focus on "data portability," and using open standards
            to share and move content around the web. Some key aspects of Open Context's efforts to
            make cultural heritage data more portable and open include:</p>
		<ul class="bodyText">
		    <li><p class="bodyText"><em>Legal Interoperability:</em> Creative Commons licenses give explicit permissions for
                    users to freely and legally use the material so long as they properly attribute the original creator. Creative
                    Commons licenses include RDFa metadata that facilitates discovery of openly licensed content.</p></li>
		    <li><p class="bodyText"><em>Faceted Search:</em> Simple web services delivering machine-readable data can
                    help make archaeological information open and reusable for research, instruction, and creativity. Searching
                    and retrieving information from large bodies of complex data is a challenge for many digital libraries
                    and information services. To avoid some of the hit-or-miss difficulties associated with keyword searches,
                    Open Context uses a faceted navigation system. Faceted navigation allows users to explore hierarchically
                    structured metadata with point-and-click selections and progressively home in on more specific information
                    from a larger collection. Because filters are applied across an entire collection, users have greater
                    certainty in comprehensiveness of results than with keyword searches and can simultaneously navigate
                    between and within individual projects and collections. Feedback, as subtotals of the numbers of items
                    in each facet, helps guide user selection of additional filters. </p></li>
                    <li><p class="bodyText"><em>Atom Syndication Format:</em> Designed to supersede various RSS formats,
                    <a href="http://www.atomenabled.org/developers/syndication/atom-format-spec.php">Atom</a> is a widely adopted XML standard
		    ideal for the exchange and aggregation of content between systems, especially via RESTful web services.  Atom permits
		    custom "payloads" of XML content (referenced to other namespaces). For example, geographic data expressed in the
                    <a href="http://georss.org/">GeoRSS</a>
		    format are common XML payloads in cultural heritage implementations of Atom. The additional XML payloads do not
                    invalidate an Atom Feed. Using Atom, resources can be shared in a way that enables complex data-structures
                    (such as ArchaeoML) to be communicated, while at the same time ensuring that even if they cannot be fully
                    processed by a recipient, they will at least gain some basic utility from the content. Atom gives recipients
                    the ability to incrementally use richer markup based on their need and capacity.</p></li>
		    <li><p class="bodyText"><em>Data Granularity:</em> Systems that make specific items of content individually
                    addressable enable others to reference those items according to their own needs and organizational principles.
                    For example, Open Context makes individual records of each location and object retrievable with a URI.
                    Other users can therefore use folksonomy services like Delicious to "tag" Open Context items
                    (and thus informally relate them to other Web content). Similarly, semantically enhanced tagging systems,
                    perhaps using a complex formal ontology such as the <a href="http://cidoc.ics.forth.gr/">CIDOC-CRM</a>,
		    can similarly reference Open Context content.  Data granularity when coupled with a powerful faceted query
		    interface, also supports greater precision in data aggregation and mash-ups. Such features give users a great deal
		    of control and specificity in how they retrieve content.</p></li>
                    
		</ul>
	    
	</div>
	
		<div id="bottom">
		</div>
	
    </div>
	
    <?php echo $this->render('footer.phtml'); //reader document footer ?>
	
</body>
</html>
