<?php
$host = OpenContext_OCConfig::get_host_config();
$GoogleAPIkey = OpenContext_OCConfig::get_google_api();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
		xml:lang="en"
	 xmlns:bibo="http://purl.org/ontology/bibo/"
	 xmlns:cc="http://creativecommons.org/ns#"
	 xmlns:dcmitype="http://purl.org/dc/dcmitype/"
	 xmlns:dcterms="http://purl.org/dc/terms/"
	 xmlns:foaf="http://xmlns.com/foaf/0.1/"
	 xmlns:owl="http://www.w3.org/2002/07/owl#"
	 xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
	 xmlns:rdfa="http://www.w3.org/ns/rdfa#"
	 xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
	 xmlns:skos="http://www.w3.org/2004/02/skos/core#" 
>
    <head> 
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
      <title>About Open Context: Bibliography</title>
       <link rel="schema.DC" href="http://purl.org/dc/elements/1.1/"/>
	   <link rel="schema.DCTERMS" href="http://purl.org/dc/terms/"/>
      <meta name="DC.title" content="About Open Context" />
      <meta name="DC.created" content="January 1, 2010" />
      <meta name="DC.date" content="January 1, 2011" />
      <meta name="DC.creator" content="Open Context Editors" />
      
      <link href="/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" /> 
		  <link href="/css/about-rev2.css" rel="stylesheet" type="text/css" /> 
	 
      <link rel="shortcut icon" href="/images/layout/oc-favicon.ico" type="image/x-icon" />
		 <script src="<?php echo $host; ?>/js/jquery/jquery-1.7.2.min.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-transition.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-carousel.js" type="text/javascript"></script>
	 <script src="https://www.google.com/jsapi?key=<?php echo $GoogleAPIkey; ?>" type="text/javascript"></script>
    
	 <script type="text/javascript">
        <!--
        
        $('.carousel').carousel();
		  
        -->
    </script>

	 
	 <?php echo $this->render('news-widget-js.phtml'); //render javascript for displaying news feeds ?>
	 
	 
	 
	 
	 
	 </head>
    
<body>

<!-- 
    Logo,
-->    
<?php echo $this->render('header.phtml'); //render document top ?>
   
<!-- 
    Navigation tabs, search box
-->
<?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>


<div id="main">
    <div id="main_content">
		  <div id="main_row">
				
				<div id="left_sidebar">
					 
					 <div id="gksm-custom-menu-widget-3" class="widget gksm-custom-menu-widget">
						  <h2 class="widgettitle">About:</h2>
						  
						  <div class="submenu-widget submenu-widget-projects">
								<?php echo OpenContext_NavMenus::AboutNavMenu("bibliography", $host); ?>
						  </div>
						  
					 </div>
					 
					 <?php echo $this->render('news-widget-dom.phtml'); //render news-widget-dom area ?>
					 
				</div>
				
				<!-- end left side div -->
				
				<div id="right_sidebar">
					 <div id="pageTop">
						  <div id="pageIntro">
								<h1 style="text-align:center;">Bibliography Relating to Open Context</h1>
								<p>Open Context publishes archaeological data to facilitate reuses,
		    including those that require more sophisticated forms of data integration. However, many of the
		    problems involved with data publication are difficult and complex, especially because
		    community expectations and technologies continually change. Because of these challenges, we continually work to improve Open Context. This page lists
		    publications that help document our efforts.</p> 
						  </div>
					 </div>

					 <div resource="http://opencontext.org/" >
						  <div id="references" >
								<ul id="pub-list" class="big-list">
									 <li id="pub-2013-1" rel="dcterms:isReferencedBy">
										  <a style="display:none;" href="#pub-2013-1" ></a>
										  <span typeof="dcterms:BibliographicResource bibo:Article" resource="#pub-2013-1">
												<span property="dcterms:bibliographicCitation">Faniel, Ixchel, Eric Kansa, Sarah Whitcher Kansa,Julianna Barrera-Gomez, and Elizabeth Yakel.
												(2013) "The Challenges of Digging Data: A Study of Context in Archaeological Data Reuse."
												<em>JCDL 2013 Proceedings of the 13th ACM/IEEE-CS Joint Conference on Digital Libraries</em>, 295-304. New York, NY: ACM</span>
												<span class="ref-links">
													 [<a rel="bibo:uri" href="http://dl.acm.org/citation.cfm?doid=2467696.2467712">Article</a>]
													 [<a rel="dcterms:hasVersion" href="http://www.oclc.org/content/dam/research/publications/library/2013/faniel-archae-data.pdf" title="Self-archived preprint">Open Access Preprint</a>]
													 [<a rel="dcterms:identifier" href="http://dx.doi.org/10.1145/2467696.2467712">DOI</a>]
												</span>
										  </span>
									 </li>
									 <li id="pub-2012-2" rel="dcterms:isReferencedBy">
										  <a style="display:none;" href="#pub-2012-2" ></a>
										  <span typeof="dcterms:BibliographicResource bibo:Article" resource="#pub-2012-2">
												<span property="dcterms:bibliographicCitation">Kansa, Eric (2012) Openness and archaeology's information ecosystem. <em>World Archaeology</em> 44(4): 498-520.</span>
												<span class="ref-links">
													 [<a rel="bibo:uri" href="http://www.tandfonline.com/doi/full/10.1080/00438243.2012.737575">Article</a>]
													 [<a rel="dcterms:hasVersion" href="http://alexandriaarchive.org/blog/wp-content/uploads/2012/Kansa-Open-Archaeology-Self-Archive-Draft.pdf" title="Self-archived preprint">Open Access Preprint</a>]
													 [<a rel="dcterms:identifier" href="http://dx.doi.org/10.1080/00438243.2012.737575">DOI</a>]
												</span>
										  </span>
									 </li>
									 <li id="pub-2012-1" rel="dcterms:isReferencedBy">
										  <a style="display:none;" href="#pub-2012-1" ></a>
										  <span typeof="dcterms:BibliographicResource bibo:Article" resource="#pub-2012-1">
												<span property="dcterms:bibliographicCitation">Atici, Levent., Sarah Kansa, Justin Lev-Tov, and Eric Kansa (2012) Other People's Data: A Demonstration of the Imperative of Publishing Primary Data. <em>Journal of Archaeological Method and Theory</em> 1(3): 1-19.</span>
												<span class="ref-links">
													 [<a rel="bibo:uri" href="http://www.springerlink.com/content/61636x6w32662243/">Article</a>]
													 [<a rel="dcterms:identifier" href="http://dx.doi.org/10.1007/s10816-012-9132-9">DOI</a>]
												</span>
										  </span>
									 </li>
									 <li id="pub-2011-3" rel="dcterms:isReferencedBy">
										  <a style="display:none;" href="#pub-2011-3" ></a>
										  <span typeof="dcterms:BibliographicResource bibo:Article" resource="#pub-2011-3">
												<span property="dcterms:bibliographicCitation">Matei, Sorin Adam., Eric Kansa, and Nicholas Rauh (2011) The Visible Past / Open Context Loosely Coupled Model for Digital Humanities Ubiquitous Collaboration and Publishing: Collaborating Across Print, Mobile, and Online Media. <em>Spaces and Flows: An International Journal of Urban and ExtraUrban Studies</em> 1(3): 33-48.</span>
												<span class="ref-links">
													 [<a rel="bibo:uri" href="http://ijf.cgpublisher.com/product/pub.203/prod.50">Article</a>]
													 [<a rel="dcterms:isPartOf" href="http://ijf.cgpublisher.com/product/pub.203/prod.38">Issue</a>]
												</span>
										  </span>
									 </li>
									 <li id="pub-2011-2" rel="dcterms:isReferencedBy">
										  <a style="display:none;" href="#pub-2011-2" ></a>
										  <span typeof="dcterms:BibliographicResource bibo:Chapter" resource="#pub-2011-2">
												<span property="dcterms:bibliographicCitation">Kansa, Eric C. and Sarah Whitcher Kansa (2011) Towards a Do-it-yourself Cyberinfrastructure: Open Data, Incentives, and Reducing Costs and Complexities of Data Sharing. In <em>Archaeology 2.0: New Approaches to Communication and Collaboration</em>, pp. 57-91, edited by E.C. Kansa, S.W. Kansa, and E. Watrall. Cotsen Institute of Archaeology Press: Los Angeles, CA.</span>
												<span class="ref-links">
													 [<a rel="dcterms:hasVersion" href="http://escholarship.org/uc/item/1r6137tb#page-73">Chapter</a>]
													 [<a rel="dcterms:isPartOf" href="http://www.worldcat.org/oclc/744560396">WorldCat</a>]
												</span>
										  </span>
									 </li>
									 <li id="pub-2011-1" rel="dcterms:isReferencedBy">
										  <a style="display:none;" href="#pub-2011-1" ></a>
										  <span typeof="dcterms:BibliographicResource bibo:Article" resource="#pub-2011-1">
												<span property="dcterms:bibliographicCitation">Kansa, Sarah Whitcher and Eric C. Kansa. (2011) Beyond BoneCommons: Recent Developments in Zooarchaeological Data Sharing. <em>The SAA Archaeological Record</em> 11(1): 26-29.</span>
												<span class="ref-links">
													 [<a rel="dcterms:hasVersion" href="http://alexandriaarchive.org/bonecommons/archive/files/kansa_kansa_icaz_saa_jan2011_d7f38e2b2b.pdf">Article</a>]
													 [<a rel="dcterms:isPartOf" href="http://digitaleditions.sheridan.com/publication/?i=58423">Issue</a>]
												</span>
									 </span>
									 </li>
									 <li id="pub-2010-5" rel="dcterms:isReferencedBy">
										  <a style="display:none;" href="#pub-2010-5" ></a>
										  <span typeof="dcterms:BibliographicResource bibo:Article" resource="#pub-2010-5">
												<span property="dcterms:bibliographicCitation">Kansa, Eric C. (2010) Open Context in Context: Cyberinfrastructure and Distributed Approaches to Publish and Preserve Archaeological Data. <em>SAA Archaeological Record</em> 10(5):12-16.</span>
												<span class="ref-links">
													 [<a rel="dcterms:isPartOf" href="http://www.saa.org/Portals/0/SAA/Publications/thesaaarchrec/Nov2010.pdf">Issue</a>]
												</span>
										  </span>
									 </li>
									 <li id="pub-2010-4" rel="dcterms:isReferencedBy">
										  <a style="display:none;" href="#pub-2010-4" ></a>
										  <span typeof="dcterms:BibliographicResource bibo:Article" resource="#pub-2010-4">
												<span property="dcterms:bibliographicCitation">Kansa, Eric C., Sarah Whitcher Kansa, Margie M. Burton, and Cindy Stankowski. (2010)	 Googling the Grey: Open Data, Web Services, and Semantics. <em>Archaeologies, Journal of the World Archaeological Congress</em> 6(2):301-326.</span>
												<span class="ref-links">
													 [<a rel="bibo:uri" href="http://www.springerlink.com/content/c259133070q276vg/"
													 title="Link to open access paper">Article</a>]
													 [<a rel="dcterms:identifier" href="http://dx.doi.org/10.1007/s11759-010-9146-4">DOI</a>]
												</span>
										  </span>
									 </li>
									 <li id="pub-2010-3" rel="dcterms:isReferencedBy">
										  <a style="display:none;" href="#pub-2010-3" ></a>
										  <span typeof="dcterms:BibliographicResource bibo:Article" resource="#pub-2010-3">
												<span property="dcterms:bibliographicCitation">Kansa, Eric C., Sarah Whitcher Kansa (2010) Publishing Data in Open Context: Methods and Perspectives. <em>CSA Newsletter</em>. Vol. XXIII, No. 2 (September 2010). Bryn Mawr: Center for the Study of Architecture.</span>
												<span class="ref-links">
													 [<a rel="bibo:uri" href="http://csanet.org/newsletter/fall10/nlf1001.html">Article</a>]
												</span>
										  </span>
									 </li>
									 <li id="pub-2010-2" rel="dcterms:isReferencedBy">
										  <a style="display:none;" href="#pub-2010-2" ></a>
										  <span typeof="dcterms:BibliographicResource bibo:Article" resource="#pub-2010-2">
												<span property="dcterms:bibliographicCitation">Kansa, Eric C. and Ahrash Bissell (2010) Web Syndication Approaches for Sharing Primary Data in "Small Science" Domains. <em>Data Science Journal</em> 9:42-53</span>
												<span class="ref-links">
													 [<a rel="bibo:uri" href="https://www.jstage.jst.go.jp/article/dsj/9/0/9_009-012/_article" title="Link to open access paper">Article</a>]
													 [<a rel="dcterms:identifier" href="http://dx.doi.org/10.2481/dsj.009-012">DOI</a>]
													 [<a rel="dcterms:isPartOf" href="https://www.jstage.jst.go.jp/browse/dsj/9/0/_contents">Issue</a>]
												</span>
										  </span>
									 </li>
									 <li id="pub-2010-1" rel="dcterms:isReferencedBy">
										  <a style="display:none;" href="#pub-2010-1" ></a>
										  <span typeof="dcterms:BibliographicResource bibo:Chapter" resource="#pub-2010-1">
												<span property="dcterms:bibliographicCitation">Kansa, Eric C. and Sarah Whitcher Kansa. (2010) &#8220;Mashable&#8221; heritage: formats, licenses and the allure of openness. <em>Heritage in the Digital Era</em>, edited by Marinos Ioannides. London: Multi-Science Publishers, pp 105-112.</span>
												<span class="ref-links">
													 [<a rel="dcterms:hasVersion" href="http://www.amazon.com/heritage-digital-era-Marinos-Ioannides/dp/1907132252">Amazon</a>]
													 [<a rel="dcterms:isPartOf" href="http://www.worldcat.org/oclc/720901432">WorldCat</a>]
												</span>
										  </span>
									 </li>
									 <li id="pub-2009-4" rel="dcterms:isReferencedBy">
										  <a style="display:none;" href="#pub-2009-4" ></a>
										  <span typeof="dcterms:BibliographicResource bibo:Chapter" resource="#pub-2009-4">
												<span property="dcterms:bibliographicCitation">Kansa, Eric C. (2009) Indigenous Heritage and the Digital Commons. In <em>Traditional Knowledge, Traditional Cultural Expressions and Intellectual Property Law in the Asia Pacific Region</em>, edited by Christoph Antons. Kluwer Law International: Alphen aan den Rijn, pp.219-244.</span>
												<span class="ref-links">
													 [<a rel="dcterms:hasVersion" href="http://www.amazon.com/Traditional-Knowledge-Expressions-Intellectual-Asia-Pacific/dp/9041127216">Amazon</a>]
													 [<a rel="dcterms:isPartOf" href="http://www.worldcat.org/oclc/300407998">WorldCat</a>]
												</span>
										  </span>
									 </li>
									 <li id="pub-2009-3" rel="dcterms:isReferencedBy">
										  <a style="display:none;" href="#pub-2009-3" ></a>
										  <span typeof="dcterms:BibliographicResource bibo:Article" resource="#pub-2009-3">
												<span property="dcterms:bibliographicCitation">Kansa, Eric C. (2009)   Opening Archaeology to Mash-ups: Field Data and an Incremental Approach to Semantics. In <em>Digital Heritage in the New Knowledge Environment: Shared spaces &amp; open paths to cultural content</em> (Conference Proceedings), edited by Metaxia Tsipopoulou. Hellenic Ministry of Culture: Athens, Greece.</span>
												<span class="ref-links">
													 [<a rel="dcterms:isPartOf" href="http://www.worldcat.org/oclc/431230377">WorldCat</a>]
												</span>
										  </span>
									 </li>
									 <li id="pub-2009-2" rel="dcterms:isReferencedBy">
										  <a style="display:none;" href="#pub-2009-2" ></a>
										  <span typeof="dcterms:BibliographicResource bibo:Article" resource="#pub-2009-2">
												<span property="dcterms:bibliographicCitation">Kansa, Sarah Whitcher and Eric C. Kansa (2009) Yes, it is all about you: User needs, archaeology and digital data. <em>CSA Newsletter</em>. Vol. XXII, No. 1 (April 2009). Bryn Mawr: Center for the Study of Architecture.</span>
												<span class="ref-links">
													  [<a rel="bibo:uri" href="http://csanet.org/newsletter/spring09/nls0902.html">Article</a>]
												</span>
										  </span>
									 </li>
									 <li id="pub-2009-1" rel="dcterms:isReferencedBy">
										  <a style="display:none;" href="#pub-2009-1" ></a>
										  <span typeof="dcterms:BibliographicResource bibo:Article" resource="#pub-2009-1">
												<span property="dcterms:bibliographicCitation">Kansa, Eric C and Sarah Whitcher (2009) Open Context: Developing Common Solutions for Data Sharing. <em>CSA Newsletter</em>. Vol. XXI, No. 3 (January 2009). Bryn Mawr: Center for the Study of Architecture.</span>
												<span class="ref-links">
													 [<a rel="bibo:uri" href="http://csanet.org/newsletter/spring09/nls0902.html">Article</a>]
												</span>
										  </span>
									 </li>
									 <li id="pub-2007-5" rel="dcterms:isReferencedBy" >
										  <a style="display:none;" href="#pub-2007-5" ></a>
										  <span typeof="dcterms:BibliographicResource bibo:Article" resource="#pub-2007-5">
												<span property="dcterms:bibliographicCitation">Kansa, Sarah Whitcher and Eric C Kansa (2007) Open Content in Open Context. <em>Educational Technology Magazine</em>. Vol. XLVII. (Nov-Dec 2007):26-31.</span>
												<span class="ref-links">
													 [<a rel="dcterms:hasVersion" href="http://www.alexandriaarchive.org/publications/KansaEdTecArticle.pdf" title="Self-archived offprint">Article</a>]
													 [<a rel="dcterms:isPartOf" href="http://asianvu.com/bookstoread/etp/Educational_Technology_Nov-Dec2007_issue.pdf">Issue</a>]
												</span>
										  </span>
									 </li>
									 <li id="pub-2007-4" rel="dcterms:isReferencedBy">
										  <a style="display:none;" href="#pub-2007-4" ></a>
										  <span typeof="dcterms:BibliographicResource bibo:Article" resource="#pub-2007-4">
												<span property="dcterms:bibliographicCitation">Kansa, Sarah Whitcher, Eric C Kansa and Jason M Schultz (2007) An Open Context for Near Eastern Archaeology. <em>Near Eastern Archaeology</em> 70(4): 187-193.</span>
												<span class="ref-links">
													 [<a rel="dcterms:hasVersion" href="http://www.alexandriaarchive.org/publications/KansaKansaSchultz_NEADec07.pdf" title="Self-archived offprint">Article</a>]
													 [<a rel="rdfs:isDefinedBy" href="http://www.jstor.org/stable/20361331">JSTOR</a>]
													 [<a rel="dcterms:isPartOf" href="http://www.jstor.org/stable/i20361328">Issue</a>]
												</span>
										  </span>
									 </li>
									 <li id="pub-2007-3" rel="dcterms:isReferencedBy">
										  <a style="display:none;" href="#pub-2007-3" ></a>
										  <span typeof="dcterms:BibliographicResource bibo:Article" resource="#pub-2007-3">
												<span property="dcterms:bibliographicCitation">Kansa, E., and S. Whitcher Kansa (2007) Open Context: Collaborative Data Publication to Bridge Field Research and Museum Collections. <em>International Cultural Heritage Informatics Meeting (ICHIM07): Proceedings</em>, edited by J. Trant and D. Bearman. Toronto: Archives &amp; Museum Informatics. 2007. Published September 30, 2007.</span>
												<span class="ref-links">
													 [<a rel="bibo:uri" href="http://www.archimuse.com/ichim07/papers/kansa/kansa.html" title="Conference proceedings">Article</a>]
												</span>
										  </span>
									 </li>
									 <li id="pub-2007-2" rel="dcterms:isReferencedBy">
										  <a style="display:none;" href="#pub-2007-2" ></a>
										  <span typeof="dcterms:BibliographicResource bibo:Article" resource="#pub-2007-2">
												<span property="dcterms:bibliographicCitation">Kansa, Eric C (2007) An Open Context for Small-scale Field Science Data. <em>Proceedings of the International Association of Technical University Libraries Annual Conference</em>, Stockholm, Sweden.</span>
												<span class="ref-links">
													 [<a rel="dcterms:abstract" href="http://www.archimuse.com/ichim07/papers/kansa/kansa.html" title="Conference Abstract">Abstract</a>]
												</span>
										  </span>
									 </li>
									 <li id="pub-2007-1" rel="dcterms:isReferencedBy">
										  <a style="display:none;" href="#pub-2007-1" ></a>
										  <span typeof="dcterms:BibliographicResource bibo:Article" resource="#pub-2007-1">
												<span property="dcterms:bibliographicCitation">Kansa, Eric C (2007) Publishing Primary Data on the World Wide Web: Opencontext.org and an Open Future for the Past. <em>Technical Briefs in Historical Archaeology</em>, 2(1):1-11.</span>
												<span class="ref-links">
													 [<a rel="bibo:uri" href="http://www.sha.org/publications/technical_briefs/volume02/article_01.pdf">Article</a>]
												</span>
										  </span>
									 </li>
									 
								</ul>
						  
						  </div>
					 </div>
			 
			 
				</div>
				<!-- end right side div -->
		  </div>
		  <!-- end main row div -->
    
	 </div> <!-- end main div -->
	
    
</div> <!-- end main div -->	 
	 <?php echo $this->render('footer.phtml'); //reader document footer ?>
	
</body>
</html>
