<?php
$host = OpenContext_OCConfig::get_host_config();
$GoogleAPIkey = OpenContext_OCConfig::get_google_api();
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ocsem="http://opencontext.org/about/concepts#"
	 xmlns:skos="http://www.w3.org/2008/05/skos#"
> 
    <head> 
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
      <title>About Open Context: Concepts</title>
      <link rel="schema.DC" href="http://purl.org/dc/terms" />
      <meta name="DC.title" content="About Open Context" />
      <meta name="DC.created" content="January 1, 2010" />
      <meta name="DC.date" content="January 1, 2011" />
      <meta name="DC.creator" content="Open Context Editors" />
      
      <link href="/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" /> 
		  <link href="/css/about-rev2.css" rel="stylesheet" type="text/css" /> 
		
      <link rel="shortcut icon" href="/images/layout/oc-favicon.ico" type="image/x-icon" />
		 <script src="<?php echo $host; ?>/js/jquery/jquery-1.7.2.min.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-transition.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-carousel.js" type="text/javascript"></script>
	 <script src="https://www.google.com/jsapi?key=<?php echo $GoogleAPIkey; ?>" type="text/javascript"></script>
    
	 <script type="text/javascript">
        <!--
        
        $('.carousel').carousel();
		  
        -->
    </script>

	 
	 
	  <?php echo $this->render('news-widget-js.phtml'); //render javascript for displaying news feeds ?>
	 
	 
	 
	 
	 </head>
    
<body>

<!-- 
    Logo,
-->    
<?php echo $this->render('header.phtml'); //reader document top ?>
   
<!-- 
    Navigation tabs, search box
-->
<?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>


<div id="main">
    <div id="main_content">
		  <div id="main_row">
				<div id="left_sidebar">
					 <div id="gksm-custom-menu-widget-3" class="widget gksm-custom-menu-widget">
						  <h2 class="widgettitle">About:</h2>
						  <div class="submenu-widget submenu-widget-projects">
								<?php echo OpenContext_NavMenus::AboutNavMenu("concepts", $host); ?>
						  </div>
					 </div>
				<?php echo $this->render('news-widget-dom.phtml'); //render news-widget-dom area ?>
				</div><!-- End Left Sidebar div -->
				
				<div id="right_sidebar">
					 <div id="pageTop">
						  <div id="pageIntro">
								<h1 style="text-align:center;">Concepts behind Open Context</h1>
								<p>For those wishing to have a look "under the hood" this page will provide you with a good start. You can find even more of the nitty-gritty on the <a href=""../about/technology">Technology</a> and <a href=""../about/technology">APIs &amp; Web-Services</a> pages. If you still have questions, <a href="mailto:ekansa@alexandriaarchive.org">Eric Kansa</a>, Open Context's Lead Developer, would be happy to chat.</p>
								<p>Open Context facilitates research by publishing data in a manner optimized for the Web.
								Open Context implements a subset of the Archaeological Markup Language (ArchaeoML), developed
		    by David Schloen for the University of Chicago OCHRE project. ArchaeoML uses an
		    item-based information model, where individual atomic units of observation are
		    related to each other and their descriptive attributes. Each item does not belong
		    to a predetermined class (pottery, bone, deposit, grave good, etc.), but is,
		    instead, an abstract entity that can have multiple descriptive properties and
		    different forms of linking relations with other items. As discussed below,
		    ArchaeoML's item-based model greatly facilitates information retrieval and opens
		    the door toward greater semantic enrichment of content over time.
								</p>		
						  </div>
					 </div>

					 <div>
						  
						  <h3 id="archaeoml">Open Context and ArchaeoML</h3>
					  
						  <p>Open Context can accommodate a variety of different field research datasets by mapping 
	    to the ArchaeoML global schema. Open Context editors map project datasets to ArchaeoML with a Web-based tool
		 called <em>Penelope</em>. This tool helps editors and contributors to collaborate describe research data
	    according to the ArchaeoML global schema, so that it can be ready for public dissemination in Open Context. The
						  editing workflow also includes steps to check and improve the consistency of data.</p>
						  <p>Mapping data to ArchaeoML helps make datasets more useful to others. The process helps to explicitly
	    express a number of tacit or implicit relationships and meanings in a dataset. By expressing these tacit meanings,
	    Open Context helps make it easier for others to understand a given dataset. The import process also asks researchers
	    for explanatory and descriptive metadata to further describe research methods and 
	    recording systems and provide critical attribution information needed for citation. Because ArchaeoML is very
	    simple, mapping data into ArchaeoML is relatively rapid. Nevertheless, while we implement ArchaeoML, we continually
		 adapt our publishing activities to meet new needs (see below).</p>
	 
						  <h4>Key ArchaeoML concepts used in Open Context:</h4>
						  <ul class="big-list">
								<li id="subjects" typeof="skos:Concept" about="[ocsem:subjects]">
									 <strong property="skos:prefLabel" xml:lang="en">Subjects</strong>
									 <span property="skos:definition" xml:lang="en">These are the primary subjects of observation in
									 a field study or in a collection. These are typically locations and objects that can be of any
									 scale and relate to one another spatially. Examples include: <em>sites</em>, <em>survey areas</em>,
									 <em>areas (of excavation)</em>, <em>stratigraphic units</em>, <em>artifacts</em>, <em>specimen</em>, etc.</span>
								</li>
								<li id="media" typeof="skos:Concept" about="[ocsem:media]">
									 <strong property="skos:prefLabel" xml:lang="en">Media</strong> <span property="skos:definition" xml:lang="en">These are media files that help make up a body of documentation for a given
								project or collection. They typically relate to and help describe <em>subjects</em>, <em>people</em>, or a <em>project</em>.
								Examples include: <em>image files</em>, <em>PDF documents</em>, <em>videos</em>,
								<em>3-D scans</em>, etc.</span></li>
								<li id="documents" typeof="skos:Concept" about="[ocsem:documents]"><strong property="skos:prefLabel" xml:lang="en">Documents</strong> <span property="skos:definition" xml:lang="en">These are textual documents that help make up a body of documentation for a given project
								or collection. They typically relate to and help describe <em>subjects</em>, <em>people</em>, or a <em>project</em>.
								They differ from <em>media</em> items in that they are not stored as outside binary files, but are simply
								plain or HTML text documents.</span></li>
								<li id="projects" typeof="skos:Concept" about="[ocsem:projects]"><strong property="skos:prefLabel" xml:lang="en">Projects and Collections</strong> <span property="skos:definition" xml:lang="en">Projects represent a specific study or research effort to collect a
								body of documentation. They can be an archaeological excavation or survey, an ecological survey, a description of
								a museum collection, or even a public health study of disease incidences. All projects and collections must
								identify an institution or person responsible for collecting and publishing data.</span></li>
								<li id="persons" typeof="skos:Concept" about="[ocsem:persons]"><strong property="skos:prefLabel" xml:lang="en">Persons and Organizations</strong> <span property="skos:definition" xml:lang="en">Persons and organizations represent the people and institutions that
								participated in a project. They are responsible for creating, editing, curating, analyzing, and
								reporting data published in Open Context.</span></li>
								<li id="properties" typeof="skos:Concept" about="[ocsem:properties]"><strong property="skos:prefLabel" xml:lang="en">Descriptive Properties</strong> <span property="skos:definition" xml:lang="en">Properties describe <em>subjects</em>, <em>people</em>, <em>media</em>, etc.
								A property represents a unique combination of a variable (like a field in a database) and a value (the values of records
								in a given database field). Each descriptive property is unique within the context of a given <em>project</em>. So, even if two
								different projects have a common property like "Taxon: <em>Canis familiaris</em>", this property will have different addresses for
								each project. This guards against falsely assuming that just because two different research <em>projects</em> may share common
								terminologies, those terminologies are used in the same, semantically equivalent way. However, since
								the use of common terminologies often does reflect semantic equivalence, the faceted browse tool also
								allows users to search properties across different <em>projects</em> as if they were equivalent.  
								Properties can have free-form alphanumeric text values, nominal values, numeric values, or calendar dates.</span></li>
						  </ul>
						  
						  <h3>Open Context, ArchaeoML and CIDOC</h3>
						  <p>Because ArchaeoML is so simple and generalized, it is less specific in expressing
						  semantic relationships than some other formal ontologies, including the <a href="http://cidoc.ics.forth.gr/">CIDOC-CRM</a>.
						  This makes Open Context's semantic relations much more ambiguous, requiring some background knowledge to interpret and
						  properly use its datasets. Nevertheless, we chose to implement ArchaeoML because of its simplicity, long
						  history of development, and implementation in current excavation databases. Many other ontologies, though sophisticated and
						  useful, require much more specialized expertise to apply and cost more to implement and use. </p>
						  <p>At the same time, we recognize the increasing need to publish data according to formal ontology standards. 
						  Our onging work is extending <em>Penelope</em> so that published data link to key shared vocabularies and other
						  Web-based collections. We are also extending <em>Penelope</em>  to capture additional information needed to relate
						  data in Open Context to the CIDOC-CRM ontology, a major standard for cultural heritage data. Open Context currently
						  publishes partial mappings to the CIDOC-CRM ontology in using RDF (see <a href="services#rdf">here</a>).</p>
						  
						  <p>For more information on how Open Context works to promote interoperability, [<a href="../about/technology">click here</a>].</p>
						  
						  </div>
					 </div>
			 
			 
				</div>
		
    </div> <!-- end main div -->
	
    
</div> <!-- end main div -->	 
	 <?php echo $this->render('footer.phtml'); //reader document footer ?>
	
</body>
</html>
