<?php
$host = OpenContext_OCConfig::get_host_config();
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ocsem="http://opencontext.org/about/concepts#"
	xmlns:skos="http://www.w3.org/2008/05/skos#"
> 
    <head> 
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
      <title>About Open Context: Key Concepts</title>
      <link rel="schema.DC" href="http://purl.org/dc/terms" />
      <meta name="DC.title" content="About Open Context: Key Concepts" />
      <meta name="DC.created" content="January 1, 2010" />
      <meta name="DC.date" content="August 30, 2011" />
      <meta name="DC.creator" content="Open Context Editors" />
      
      <link href="/css/opencontext_style.css" rel="stylesheet" type="text/css" /> 
      <link href="/css/test_landing_page.css" rel="stylesheet" type="text/css" />
      <link href="/css/default_banner.css" rel="stylesheet" type="text/css" />
      <link href="/css/rounded_corners.css" rel="stylesheet" type="text/css" />
      
      <link rel="shortcut icon" href="/images/general/oc_favicon.ico" type="image/x-icon" />
    </head>
    
<body>
    <div id="oc_logo">
	<a href="<?php echo $host; ?>" title="Open Context (Home)"><img alt="Open Context Logo" src="/images/general/oc_logo.jpg" style="border: none;" ></img></a>
    </div>
    <div id="oc_tagline">
	<img alt="Open Context Tagline" src="/images/general/oc_tagline.jpg" ></img>
    </div>
    <div id="oc_beta">
	<img alt="Beta Stamp" src="/images/general/oc_betastamp.jpg" ></img>
    </div>
    
    <div id="oc_top_search">
	<form method="get" action="<?php echo $host;?>/search/" id="search-form">
	<div id="search_box">
	<input type='text' name='q' class='tinyText' value='Search' size='30' onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';" />
	</div>
	<div id="search_cntrl">
	    <input class="oc_top_sbutton" type="submit" value="" />
	</div>
	</form>
    </div>
   
   
   <!-- 
    Navigation tabs
    -->    
    <?php echo OpenContext_NavMenus::GeneralNavMenu("about"); ?>
    
    <div id="main">
	<div id="pageTop">
            <div id="pageIntro">
                <h2 style="text-align:center;">Concepts Behind Open Context</h2>
                
                <div style="margin:10px;">
                    <p class="bodyText">Open Context facilitates greater cultural heritage data sharing
		    and access in a manner optimized for public dissemination on the Web. Open Context
		    implements a subset of the Archaeological Markup Language (ArchaeoML), developed
		    by David Schloen for the University of Chicago OCHRE project. AchaeoML uses an
		    item-based information model, where individual atomic units of observation are
		    related to each other and their descriptive attributes. Each item does not belong
		    to a predetermined class (pottery, bone, deposit, grave good, etc.), but is,
		    instead, an abstract entity that can have multiple descriptive properties and
		    different forms of linking relations with other items. As discussed below,
		    ArchaeoML's item-based model greatly facilitates information retrieval and opens
		    the door toward greater semantic enrichment of content over time.</p>
                </div>
            </div>
            <div id="about_submenu" class="rounded-corners">
                    <p class="bodyText"><em>More About Open Context:</em></p>
                    <?php echo OpenContext_NavMenus::AboutNavMenu("concepts", $host); ?>
            </div>
            <div id="pageTopEnd">
                <br/>
            </div>
        </div>
        
        
        <br/>
        <div style="margin:10px;">
            <h3>Open Context and ArchaeoML</h3>
	    <p class="bodyText">Open Context can accommodate a variety of different field research datasets through mapping these
	    datasets to the ArchaeoML global schema. A tool for mapping project datasets to ArchaeoML, called <em>Penelope</em>
	    will move from alpha release to beta release in the summer of 2009. This tool enables users to describe their research data
	    according to the ArchaeoML global schema, so that it can be ready for public dissemination in Open Context.</p>  
	    <p class="bodyText">Mapping data in ArchaeoML helps make datasets more useful to others. The process helps to explicitly
	    express a number of tacit or implicit relationships and meanings in a dataset. By expressing these tacit meanings,
	    Open Context helps make it easier for others to understand a given dataset. The import process also asks researchers
	    to provide additional explanatory and descriptive metadata to further describe research methods and approaches,
	    recording systems, and provide critical attribution information needed for citation. Because ArchaeoML is very
	    simple, mapping data into ArchaeoML is relatively easy, and can be accomplished by people with no special
	    expertise.  We hope to make the
	    <em>Penelope</em> data import tool easy enough for individual data contributors to use.</p>
	    <p class="bodyText">Key concepts in the data model are described below:</p>
	    <ul class="bodyText">
		<li id="subjects" typeof="skos:Concept" about="[ocsem:subjects]"><strong property="skos:prefLabel" xml:lang="en">Subjects</strong> <span property="skos:definition" xml:lang="en">These are the primary subjects of observation in a field study or in a collection.
		These are typically locations and objects that can be of any scale and relate to one another spatially.
		Examples include: <em>sites</em>, <em>survey areas</em>, <em>areas (of excavation)</em>,
		<em>stratigraphic units</em>, <em>artifacts</em>, <em>specimen</em>, etc.</span></li>
		<li id="media" typeof="skos:Concept" about="[ocsem:media]"><strong property="skos:prefLabel" xml:lang="en">Media</strong> <span property="skos:definition" xml:lang="en">These are media files that help make up a body of documentation for a given
		project or collection. They typically relate to and help describe <em>subjects</em>, <em>people</em>, or a <em>project</em>.
		Examples include: <em>image files</em>, <em>PDF documents</em>, <em>videos</em>,
		<em>3-D scans</em>, etc.</span></li>
		<li id="documents" typeof="skos:Concept" about="[ocsem:documents]"><strong property="skos:prefLabel" xml:lang="en">Documents</strong> <span property="skos:definition" xml:lang="en">These are textual documents that help make up a body of documentation for a given project
		or collection. They typically relate to and help describe <em>subjects</em>, <em>people</em>, or a <em>project</em>.
		They differ from <em>media</em> items in that they are not stored as outside binary files, but are simply
		plain or HTML text documents.</span></li>
		<li id="projects" typeof="skos:Concept" about="[ocsem:projects]"><strong property="skos:prefLabel" xml:lang="en">Projects and Collections</strong> <span property="skos:definition" xml:lang="en">Projects represent a specific study or research effort to collect a
		body of documentation. They can be an archaeological excavation or survey, an ecological survey, a description of
		a museum collection, or even a public health study of disease incidences. All projects and collections must
		identify an institution or person responsible for collecting and publishing data.</span></li>
		<li id="persons" typeof="skos:Concept" about="[ocsem:persons]"><strong property="skos:prefLabel" xml:lang="en">Persons and Organizations</strong> <span property="skos:definition" xml:lang="en">Persons and organizations represent the people and institutions that
		participated in a project. People and organizations are responsible for creating, editing, curating, analyzing, and
		reporting data published in Open Context.</span></li>
		<li id="properties" typeof="skos:Concept" about="[ocsem:properties]"><strong property="skos:prefLabel" xml:lang="en">Descriptive Properties</strong> <span property="skos:definition" xml:lang="en">Properties describe <em>subjects</em>, <em>people</em>, <em>media</em>, etc.
		A property represents a unique combination of a variable (like a field in a database) and a value (the values of records
		in a given database field). Each descriptive property is unique within the context of a given <em>project</em>. So even if two
		different projects have a common property like "Taxon: canis familiaris", this property will have different addresses for
		each project. This guards against false assuming that just because two different research <em>projects</em> may share common
		terminologies, that these terminologies are used in the same, semantically equivalent way. However, since
		the use of common terminologies often does reflect semantic equivalence, the faceted browse tool also
		allows users to search properties across different <em>projects</em> as if they were equivalent.  
		Properties can have either free-form alphanumeric text values, nominal values, numeric values, or calendar dates.</span></li>
	    </ul>
	    <p class="tinyText">Note: these concepts are formally described in XSD documents associated with the University of Chicago
	    OCHRE project. <a href="http://ochre.lib.uchicago.edu/">Click here</a> to learn more.</p>
	    <p class="bodyText">Because ArchaeoML is so simple and generalized, it is less specific in expressing
	    semantic relationships than many formal ontologies, including the <a href="http://cidoc.ics.forth.gr/">CIDOC-CRM</a>.
	    This makes Open Context's semantic relations much more ambiguous, requiring some background knowledge to interpret and
	    properly use its datasets. Nevertheless, we chose to implement ArchaeoML because of its simplicity and long
	    history of development and use in working field databases. Many other ontologies, while sophisticated and
	    useful, require much more specialized expertise to apply and cost more to implement and use. Instead,
	    we chose to go with a simple and cost-effective solution, despite its initial limitations.</p>
	    <br/>
	    <h3 id="linked-data">Open Context and Linked Open Data</h3>
	    <p class="bodyText">Open Context participates in the "<a href='http://lod-lam.net/' title='Digital Humanities Community Hub for Linked Data'>Linked
	    Open Data</a>" community by publishing data linked to URI-identified concepts published by others. We currently link to
	    the <a href="http://www.eol.org/" title="EOL Homepage">Encyclopedia of Life</a> to reference biological taxa. We also link to
	    places published by the <a href="http://pleiades.stoa.org" title="Pleiades homepage">Pleiades Gazetteer</a>. To learn how to query
	    Open Context over linked data URIs, please review our API documentation <a href="services#query-rel">here</a>.
	    </p>
	    <p class="bodyText">In addition, Open Context publishes data easy to reference with stable URIs to specific records.
	    Each location and object has its own ID and its own web-address.
	    Similarly, each project, project, person, media item, and even each descriptive property has its own unique address.
	    These items are linked to one another through network graph relationships (expressed in ArchaeoML, a machine-readbile XML format). We are also working
	    on expressing these data as RDF-triples using the CIDOC-CRM.</p>
	    <p class="bodyText">By publishing data where every record can be referenced with URIs, everything in Open Context can be addressed and annotated by simple folksonomy systems (user-generated tagging
	    systems like <a href="http://delicious.com/">Delicious</a>) or by outside systems using more sophisticated semantics and "Linked Data" methods.
	    For instance, experts familiar with the CIDOC-CRM can describe relationships among Open Context content using the
	    semantically richer framework of the CIDOC-CRM even before we provide our own expressions of CIDOC-mapped data.
	    </p>
	    <p class="bodyText">Moreover, Open Context licenses all content with Creative Commons, and makes all data
	    available in a machine-readible XML format. This makes all Open Context data legally and technologically portable.
	    Individuals who find its semantics and other features too limiting are free (and welcome) to simply copy all
	    data of interest and deploy these data in other systems. This openness and data portability is a critical aspect
	    in making sure that Open Context supports innovative research applications for the long term.
	    </p>
	</div>
	
	<div id="bottom">
	</div>
	
    </div>

</body>
</html>
