<?php

function showProblem($key, $problems, $manyErrors, $offset = true){
    
    $output = "";
    
    if($problems != false){
		  if((array_key_exists($key, $problems)) && !$manyErrors){
			  
				$output = "<span class='tinyText' style='color:#660000; background-color:#FFFFCC;'>".$problems[$key]."</span>";
			
				if($offset){
					  $output = "<p>".$output."</p>";		
				}
		  }
    }
    
    return $output;
}


function radioChecked($key, $valueKey, $badRequest){
    $output = "";
    
    if($badRequest != false){
		  if(array_key_exists($key, $badRequest)){
				if($badRequest[$key] == $valueKey){
					 $output = 'checked="checked"';
				}
		  }
    }
    
    return $output;
}

function make_radio_inputs($key, $numFieldsValues, $badRequest){
    
    $output = "<ul>";
    foreach($numFieldsValues[$key] as $valueKey => $viewText){
		  $radioChecked = radioChecked($key, $valueKey, $badRequest);
		  $output .= '<li><input name="'.$key.'" type="radio" value="'.$valueKey.'" '.$radioChecked.' /> '.$viewText.' </li>'.chr(13);
    }
    $output .= "</ul>".chr(13);
	 
    return $output;
}




function showFormValues($key, $badRequest){
    $goodValues = array("name" => "(Your name)",
			"email" => "(Valid email)",
			"phone" => "(Phone number)",
			"projname" => "(Project Name)",
			"num_years" => "",
			"num_sets" => "",
			"num_tabs" => "",
			"comment" => "If you have additional comments about your project's data, or if you have questions for Open Context's editors, please type them here.",
			"rlicense" => "(Other Creative Commons License)",
			"restrict_com" => "To help us better understand legal and licensing issues faced by researchers, please describe why you believe a more restrictive license is required for your content.");
    
    $output = "";
    if(array_key_exists($key, $goodValues)){
		  $output = $goodValues[$key];
    }
    if($badRequest != false){
		  if(array_key_exists($key, $badRequest)){
				$output = $badRequest[$key];
		  }
    }
    
    return $output;
}

$problems = $this->problems;
$badRequest = $this->badRequests;
$numFieldsValues = $this->numFieldsValues;

$errorIntro = "";

if($problems != false){   
    $errorIntro = "<div style='background-color:#FFFFCC; padding:10px;'>".chr(13);
    $errorIntro .= "<p style='color:#660000;'><strong>We're sorry! We cannot process this form as completed. ";
    $errorIntro .= "Please fix the errors indicated below and resubmit this form.</strong></p>".chr(13);
    $errorIntro .= "</div>".chr(13);
}

$host = OpenContext_OCConfig::get_host_config();
$GoogleAPIkey = OpenContext_OCConfig::get_google_api();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">  
    <head> 
		  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
		  <title>About Open Context: Estimate Data Management + Publication Costs</title>
		  <link rel="schema.DC" href="http://purl.org/dc/terms" />
		  <meta name="DC.title" content="About Open Context:  Estimate Data Management + Publication Costs" />
		  <meta name="DC.created" content="January 1, 2010" />
		  <meta name="DC.date" content="November 7, 2012" />
		  <meta name="DC.creator" content="Open Context Editors" />
		  
		  <link href="/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" /> 
		  <link href="/css/about-rev2.css" rel="stylesheet" type="text/css" /> 
		  
		  <link rel="shortcut icon" href="/images/layout/oc-favicon.ico" type="image/x-icon" />
		  <script src="<?php echo $host; ?>/js/jquery/jquery-1.7.2.min.js" type="text/javascript"></script>
		  <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-transition.js" type="text/javascript"></script>
		  <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-carousel.js" type="text/javascript"></script>
		  <script src="https://www.google.com/jsapi?key=<?php echo $GoogleAPIkey; ?>" type="text/javascript"></script>
		  
		  <script type="text/javascript">
				<!--
				
				$('.carousel').carousel();
				
				-->
		  </script>
		
		  <?php echo $this->render('news-widget-js.phtml'); //render javascript for displaying news feeds ?>

	 </head>
    
<body>

<!-- 
    Logo,
-->    
<?php echo $this->render('header.phtml'); //reader document top ?>
   
<!-- 
    Navigation tabs, search box
-->
<?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>


<div id="main">
    <div id="main_content">
		  <div id="main_row">
				<div id="left_sidebar">
					 <div id="gksm-custom-menu-widget-3" class="widget gksm-custom-menu-widget">
						  <h2 class="widgettitle">About:</h2>
						  <div class="submenu-widget submenu-widget-projects">
								<?php echo OpenContext_NavMenus::AboutNavMenu("estimate", $host); ?>
						  </div>
					 </div>
				<?php echo $this->render('news-widget-dom.phtml'); //render news-widget-dom area ?>
				</div><!-- End Left Sidebar div -->
				
				<div id="right_sidebar">
					 <div id="pageTop">
						  <div id="pageIntro">
								<h1 style="text-align:center;">Data Management, Publishing, &amp; Budgeting</h1>
								<p>Open Context is primarily suited for publishing datasets that come from spreadsheets and relational databases,
								as well as relating digital media files (images, video, etc.) to records in those datasets.
								Open Context's main emphasis is to support data dissemination relating to excavations and the
								analysis of collections (zooarchaeological, ceramic, lithic, osteological, paleoethnobotanical, etc.).
								</p>
								<p>
								Although Open Context has geospatial search features, it does not have full-featured GIS capabilities.
								For the most part, Open Context would offer rich search and retrieval functions based on the descriptions
								(metadata) of GIS data. Open Context's current capabilities are useful for sharing GIS datasets, but
								Open Context would not act as an online analytical tool for GIS data. Similar limitations apply to
								CAD data, remote sensing data, 3D data, and other specialized datasets. For certain very specialized
								datasets (especially large datasets from highly specialized instrumentation), we may recommend
								alternatives to Open Context, since long-term curation of these data may require specialized expertise
								not currently available at the California Digital Library. Please contact
								<a href='mailto:publish@opencontext.org' title='Email the Editor'>Open Context editors</a> to make
								inquiries about specialized datatypes. While Open Context does not support Web-based analysis of some
								more specialized forms of data, through support of the
								<a href='http://www.cdlib.org/' title='University of California, CDL'>California Digital Library</a>,
								Open Context can help researchers archive and preserve most common forms of documentation.	 
								</p>
						  </div>
					 </div>

					 <div>
						  
						  <h2>Publication &amp; Archiving Cost Estimation Form</h2>
					  
						  <p>The form provided below will help you prepare and budget for your grant "Data Management Plan". Once you successfully complete this form, you will receive an email with a budget estimate and language to add to your Data Management Plan. This language will include a description of interoperability, access, and archiving issues that help determine the research value of shared data. Please note, completing this form does not imply or constitute a binding agreement.</p>
						 
						  <div id="error-div">
								<?php echo $errorIntro; ?>
						  </div>
						 
						 
						  <form method="post" action="<?php echo $host."/about/results"; ?>">
								<div id="estimate-form-outer">
									 
									 <h5>Project Contact Information:</h5>
									 <div class="estimate-form-part" id="estimate-contact">
										  <table style='width:80%;'>
												<tr>
													 <td class="field-name-n">Name:
													 </td>
													 <td class="field-input">
														  <input class="alpha" name="name" type="text" value="<?php echo showFormValues("name", $badRequest); ?>" />
														  <?php echo showProblem("name", $problems, false, true); ?> 
													 </td>
												</tr>
												<tr>
													 <td class="field-name-n">Email:
													 </td>
													 <td class="field-input">
														  <input class="alpha" name="email" type="text" value="<?php echo showFormValues("email", $badRequest); ?>" />
													 <?php echo showProblem("email", $problems, false, true); ?>
													 </td>
												</tr>
												<tr>
													 <td class="field-name-n">Phone:
													 </td>
													 <td class="field-input">
														  <input class="alpha" name="phone" type="text" value="<?php echo showFormValues("phone", $badRequest); ?>" />
													 <?php echo showProblem("phone", $problems, false, true); ?>
													 </td>
												</tr>
												<tr>
													 <td class="field-name-n">Project Name:
													 </td>
													 <td class="field-input">
														  <input class="alpha" name="projname" type="text" value="<?php echo showFormValues("projname", $badRequest); ?>" />
													 <?php echo showProblem("projname", $problems, false, true); ?>
													 </td>
												</tr>
												<tr>
													 <td class="field-name-n">Is this a doctoral dissertation grant? (Check if 'yes')</td>
													 <td class="field-input">
														  <input name="diss" type="checkbox" value="true" <?php echo radioChecked("diss", "true", $badRequest); ?> />
														  <em>(Receives a 25% discount)</em>
													 </td>
												</tr>
										  </table>
									 </div>
									 
									 <h5>Project Database Size and Complexity:</h5>
									 <div class="estimate-form-part" id="estimate-db-size">
										  <table>
												<tr>
													 <td class="field-name-w">Duration of Proposed Project (Years): 
													 </td>
													 <td class="field-input"><input name="num_years" type="text" value="<?php echo showFormValues("num_years", $badRequest); ?>" class="num"/>
													<?php echo showProblem("num_years", $problems, false, false); ?>
													 </td>
												</tr>
												<tr>
													 <td class="field-name-w">Estimated Number of Specialists Datasets (zooarchaeology, lithic analysis, etc.):
													 </td>
													 <td class="field-input"><input name="num_sets" type="text" value="<?php echo showFormValues("num_sets", $badRequest); ?>" class="num"/>
														  <?php echo showProblem("num_sets", $problems, false, false); ?>
													 </td>
												</tr>
												<tr>
													 <td class="field-name-w">Estimated Total Number of Tables (for data to be published from relational databases and spreadsheets):
													 </td>
													 <td class="field-input"><input name="num_tabs" type="text" value="<?php echo showFormValues("num_tabs", $badRequest); ?>" class="num"/>
														  <?php echo showProblem("num_tabs", $problems, false, false); ?>
													 </td>
												</tr>
										  </table>
									 </div>
									 
									 <h5>Project Media Size and Complexity:</h5>
									 <div class="estimate-form-part" id="estimate-media-size">
										  <p>(1) Number of Image Files: <?php echo showProblem("num_images", $problems, false, false); ?></p>
										  <?php echo make_radio_inputs("num_images", $numFieldsValues, $badRequest); ?>
									 
									 <p>(2) Number of Audio and Video Files:  <?php echo showProblem("num_vids", $problems, false, false); ?></p>
										  <?php echo make_radio_inputs("num_vids", $numFieldsValues, $badRequest); ?>
									 <p>(3) Number of Documents (<em>HTML, text, PDF</em>):  <?php echo showProblem("num_docs", $problems, false, false); ?></p>
										  <?php echo make_radio_inputs("num_docs", $numFieldsValues, $badRequest); ?>
									 <p>(4) Number of GIS layers (<em>By default, GIS data will be accessioned into Open Context as digital objects, i.e. data files that are available for retrieval but not "live" for dynamic analyses or visualizations. If you require more sophisticated Web-based interactions with GIS data, please contact Open Context editors to discuss special arrangements</em>):  <?php echo showProblem("num_gis", $problems, false, false); ?></p>
										  <?php echo make_radio_inputs("num_gis", $numFieldsValues, $badRequest); ?>
									 <p>(5) Number of Other Specialized Datasets (<em>We consider specialized datasets to be those data not typically managed and used in spreadsheet or database applications such as: CADD, remote sensing, 3D point clouds, photogrammetric, etc. By default, these data will be accessioned into Open Context as digital objects, i.e. data files that are available for retrieval but for interactions requiring live-processing of these types of data. Please note: researchers must identify and use appropriate metadata standards needed to document these specialized forms of data.</em>):  <?php echo showProblem("num_other", $problems, false, false); ?></p>
										  <?php echo make_radio_inputs("num_other", $numFieldsValues, $badRequest); ?>
									 </div>
									 
									 <h5>Additional Comments:</h5>
									 <div class="estimate-form-part" id="estimate-comments">
										  <textarea name="comment" cols="60" rows="6"><?php echo stripslashes(showFormValues("comment", $badRequest)); ?>
										  </textarea>
									 </div>
									 
									 <h5>Planning for Copyright Licensing</h5>
									 <p>Unlike most journals, Open Context does not require authors to transfer copyright for publication.
									 Contributors therefor retain rights to use their content in venues other than Open Context.
									 However, to help insure the legal interoperability of content, Open Context requires contributors
									 to either dedicate their content to the public domain, or to license their content using a
									 Creative Commons license. Note that copyright and licensing issues are largely independent
									 of scholarly citation and attribution. <em>Professional standards dictate that all users properly
									 cite data contributors even for public domain content, especially for scholarly uses.</em> This
									 professional norm of conduct works independently of the copyright status of content.</p>
	    
									 <p><span style='text-decoration:underline;'>Note:</span> Researchers working in collaborative projects
									 need to determine and agree upon publication rights in advance of submitting content to Open Context.
									 Open Context holds contributors responsible for determining that they have the needed rights to
									 publish all materials. For more background on managing copyright and intellectual property issues,
									 especially with regard to stakeholder communities, please
									 <a href='../about/intellectual-property' title='Data Management and IP'>click here</a>.</p>
	    
									 <p>Please select from the copyright and license options below:
									 <?php echo showProblem("license", $problems, false, false); ?></p>
									 
									 <div class="estimate-form-part" id="estimate-license">
										  <table>
												<tr>
													 <td class="lic-check">
														  <input name="license" type="radio" value="cc0" <?php echo radioChecked("license", "cc0", $badRequest); ?> />
													 </td>
													 <td class="lic-name">CC-0 (Public Domain)
													 </td>
													 <td class="lic-note">If I choose to publish with Open Context, I plan to waive all copyright and other intellectual property rights on my content and dedicate my content to the public domain by using the Creative Commons-Zero (public domain) declaration. Legal experts believe that this choice maximizes scientific interoperability and potential for reuse. While not legally required, citation is expected through norms of professional conduct.
													 </td>
												</tr>
												<tr class="alt-color">
													 <td class="lic-check">
														  <input name="license" type="radio" value="by" <?php echo radioChecked("license", "by", $badRequest); ?> />
													 </td>
													 <td class="lic-name">CC-By (Attribution)
													 </td>
													 <td class="lic-note">If I choose to publish with Open Context, I plan to license my content under a Creative Commons-Attribution License. This license allows others to:<br/>
													 <ul>
														  <li>to copy, distribute and transmit the work</li>
														  <li>to adapt the work</li>
													 </ul>
													 These permissions apply under the condition that others attribute your work in the manner specified by Open Context (which is proper citation). 
													 </td>
												</tr>
												<tr>
													 <td class="lic-check">
														  <input name="license" type="radio" value="other" <?php echo radioChecked("license", "other", $badRequest); ?> />
													 </td>
													 <td class="lic-name">Other
													 </td>
													 <td class="lic-note">Because of special circumstances (such as applicable laws, organizational policies, or ethical concerns regarding community stakeholder claims), my content should have greater restrictions on reuse. If I choose to publish with Open Context, I will need to use the following more restrictive license:
													 </td>
												</tr>
												<tr>
													 <td class="lic-check"></td>
													 <td class="lic-name"></td>
													 <td class="lic-note"><input name="rlicense" type="text" value="<?php echo showFormValues("rlicense", $badRequest); ?>" style='width:70%;'/>
													 </td>
												</tr>
												<tr>
													 <td class="lic-check"></td>
													 <td class="lic-name"></td>
													 <td class="lic-note">
														  <textarea name="restrict_com" cols="50" rows="4"><?php echo stripslashes(showFormValues("restrict_com", $badRequest)); ?>
														  </textarea>
													 </td>
												</tr>
										  </table>
									 </div>
									 <div id="estimate-submit">
										  <input type="submit" value="Submit" />
									 </div>
								</div>
						  </form>
						  
					 </div>
			 
			 
				</div>
				<!-- end right side bar -->
		  
		  </div>
		  <!-- end main row div -->
		
    </div> <!-- end main div -->
	
    
</div> <!-- end main div -->	 
	 <?php echo $this->render('footer.phtml'); //reader document footer ?>
	
</body>
</html>
