

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
      <title>About Open Context</title>
      <link rel="schema.DC" href="http://purl.org/dc/terms" />
      <meta name="DC.title" content="About Open Context" />
      <meta name="DC.created" content="June 1, 2010" />
      <meta name="DC.date" content="January 30, 2011" />
      <meta name="DC.creator" content="Open Context Editors" />
      
      <link href="/css/opencontext_style.css" rel="stylesheet" type="text/css" /> 
      <link href="/css/test_landing_page.css" rel="stylesheet" type="text/css" />
      <link href="/css/default_banner.css" rel="stylesheet" type="text/css" />
      <link href="/css/rounded_corners.css" rel="stylesheet" type="text/css" />
      
      <link rel="shortcut icon" href="/images/general/oc_favicon.ico" type="image/x-icon" />
    </head>
    
<body>
  <div id="oc_logo">
	<a href="http://testing.opencontext.org/"><img alt="Open Context Logo" src="/images/general/oc_logo.jpg" border="0" ></img></a>
    </div>
    <div id="oc_tagline">
	<img alt="Open Context Tagline" src="/images/general/oc_tagline.jpg" ></img>
    </div>
    <div id="oc_beta">
	<img alt="Beta Stamp" src="/images/general/oc_betastamp.jpg" ></img>
    </div>
    
    <div id="main">
	<br/>
	<p class="pageName" align="center">About Open Context</p>
	<br/>
	<div style="margin:10px;">
	    <p class="bodyText">Open Context facilitates greater cultural heritage data sharing and access in a manner optimized for
	    public dissemination on the Web. Open Context implements a subset of the Archaeological Markup Language (ArchaeoML),
	    developed by David Schloen for the University of Chicago <a href="http://ochre.lib.uchicago.edu/">OCHRE project</a>.
            AchaeoML uses an item-based information model, where individual atomic units of observation are related to each other and
            their descriptive attributes. Each item does not belong to a predetermined class (pottery, bone, deposit, grave good, etc.),
            but is, instead, an abstract entity that can have multiple descriptive properties and different forms of linking relations
            with other items. As discussed below, ArchaeoML's item-based model greatly facilitates information retrieval and opens
            the door toward greater semantic enrichment of content over time.</p> 
	    <p class="bodyText">While ArchaeoML is very useful for cultural heritage data management and dissemination (and can even see
	    application in areas as diverse as Public Health and environmental biology), there are many
	    scenarios where users where may want to work with ArchaeoML content in other applications and systems. Some of these scenarios
	    include combining ArchaeoML data with data from other collections. Open Context, or any other cultural heritage data system,
	    cannot always meet the diverse needs of all users. For example, content drawn from Open Context could be far more interesting
	    to some users when visualized in GoogleEarth along with datasets from other sources.</p>  
	    <p class="bodyText">Open Context's main development efforts try to address this need for "data portability". Some key aspects
	    of Open Context's efforts to make cultural heritage data more portable and open include:</p>
	    <p class="bodyText">
		<ul>
		    <li><p class="bodyText"><em>Legal Interoperability:</em> Creative Commons licenses give explicit permissions for users to freely and
		    legally use the material so long as they properly attribute the original creator. Creative Commons licenses
		    include RDFa metadata that facilitates discovery of openly licensed content.</p></li>
		    <li><p class="bodyText"><em>Atom Syndication Format:</em> Designed to supersede various RSS formats,
                    <a href="http://www.atomenabled.org/developers/syndication/atom-format-spec.php">Atom</a> is a widely adopted XML standard
		    ideal for the exchange and aggregation of content between systems, especially via RESTful web services.  Atom permits
		    custom "payloads" of XML content (referenced to other namespaces). For example, geographic data expressed in the
                    <a href="http://georss.org/">GeoRSS</a>
		    format are common XML payloads in cultural heritage implementations of Atom. The additional XML payloads do not
		    invalidate an Atom Feed. Using Atom, resources can be shared in a way that enables complex data-structures
		    (such as ArchaeoML) to be communicated, while at the same time ensuring that even if they cannot be fully processed
		    by a recipient, they will at least gain some basic utility from the content. Atom gives recipients the ability to
		    incrementally use richer markup based on their need and capacity.</p></li>
		    <li><p class="bodyText"><em>Data Granularity:</em> Systems that make specific items of content individually addressable enable others to
		    reference those items according to their own needs and organizational principles. For example, Open Context makes
		    individual records of each location and object retrievable with a URI. Other users can therefore use folksonomy
		    services like Delicious to "tag" Open Context items (and thus informally relate them to other Web content).
		    Similarly, semantically enhanced tagging systems, perhaps using a complex formal ontology such as the <a href="http://cidoc.ics.forth.gr/">CIDOC-CRM</a>,
		    can similarly reference Open Context content.  Data granularity when coupled with a powerful faceted query
		    interface, also supports greater precision in data aggregation and mash-ups. Such features give users a great deal
		    of control and specificity in how they retrieve content.</p></li>
		</ul>
	    </p>
	    <p class="bodyText">Many of the above features are starting to see wider implementation in the cultural heritage sector.
	    Several museums and heritage organizations, including the <a href="http://www.nmm.ac.uk/">National Maritime Museum (London)</a>,
            the <a href="http://www.powerhousemuseum.com/collection/database/">Powerhouse Museum (Sydney)</a> and others implement the
            <a href="http://www.opensearch.org/Home">Open Search</a> protocol to output keyword search requests as
	    RSS feeds. One of the first major Atom implementations is in the <a href="http://pleiades.stoa.org/">Pleiades</a> ancient world-mapping project. Pleiades offers a
	    variety of Atom representations for both query and search results, as well as requests for specific records. The ease of
	    creating and using Atom-based Web services, coupled with Atom's wide support in popular applications, has generated great
	    enthusiasm for this content syndication approach.</p>
	    <p class="bodyText">Atom-based Web services represent an important aspect of data portability. They can enable mash-ups use
	    of cultural heritage content without requiring adherence to complex and difficult semantic frameworks or cumbersome <a href="http://en.wikipedia.org/wiki/SOAP">(WS*/SOAP)</a>
	    Web services. Atom allows users to incrementally work with richer data structures and semantic markup as they need and
	    as they have the capacity. When combined with faceted search features such as those offered by Open Context, Atom
	    implementations can also benefit from sophisticated semantic frameworks that enable more specific and relevant retrieval
	    of content than possible through keyword text searches. In this regard, the Open Context Atom implementation generates feeds
	    requested through a sophisticated faceted query interface that accepts many parameters and Boolean operators. This enables
	    users to take advantage of Open Context's ArchaeoML-based data structures and sophisticated index in order to make search
	    requests with constraints specified in a number of dimensions.</p>
	    <p class="bodyText">Like OCHRE, Open Context now host many different projects, with different methodologies, recording
	    systems, and temporal and geographic coverage. This wide applicability lowers costs, since a common set of ArchaeoML-based
	    software and database tools can be used for many projects without any additional software development.</p>
	</div>
	
	<div id="bottom">
	</div>
	
    </div>

</body>
</html>
