<?php
$host = OpenContext_OCConfig::get_host_config();
$GoogleAPIkey = OpenContext_OCConfig::get_google_api();
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
      <title>About Open Context</title>
      <link rel="schema.DC" href="http://purl.org/dc/terms" />
      <meta name="DC.title" content="About Open Context" />
      <meta name="DC.created" content="January 1, 2010" />
      <meta name="DC.date" content="January 1, 2011" />
      <meta name="DC.creator" content="Open Context Editors" />
      
      <link href="/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" /> 
		  <link href="/css/about-rev2.css" rel="stylesheet" type="text/css" /> 
		
      <link rel="shortcut icon" href="/images/layout/oc-favicon.ico" type="image/x-icon" />
		 <script src="<?php echo $host; ?>/js/jquery/jquery-1.7.2.min.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-transition.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-carousel.js" type="text/javascript"></script>
	 <script src="https://www.google.com/jsapi?key=<?php echo $GoogleAPIkey; ?>" type="text/javascript"></script>
    
	 <script type="text/javascript">
        <!--
        
        $('.carousel').carousel();
        
        -->
    </script>

	 <?php echo $this->render('news-widget-js.phtml'); //render javascript for displaying news feeds ?>
	 
	 </head>
    
<body>

<!-- 
    Logo,
-->    
<?php echo $this->render('header.phtml'); //reader document top ?>
   
<!-- 
    Navigation tabs, search box
-->
<?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>


<div id="main">
    <div id="main_content">
		  <div id="main_row">
				<div id="left_sidebar">
					 <div id="gksm-custom-menu-widget-3" class="widget gksm-custom-menu-widget">
						  <h2 class="widgettitle">About:</h2>
						  <div class="submenu-widget submenu-widget-projects">
		  
								<?php echo OpenContext_NavMenus::AboutNavMenu("index", $host); ?>
								
						  </div>
					 </div>
					 <?php echo $this->render('news-widget-dom.phtml'); //render news-widget-dom area ?>
				</div><!-- End Left Sidebar div -->
				
				<div id="right_sidebar">
					 <div id="pageTop">
						  <div id="pageIntro">
								<h1 style="text-align:center;">About Open Context</h1>
								
								<div id="about-slides">
									 <div id="myCarousel" class="carousel slide">
										  <!-- Carousel items -->
										  <div class="carousel-inner">
												
												<div class="item active">
													 <div class="hero_image">
														  <div style="text-align:center; padding-top:18%; padding-bottom: 4%;">
																<img src="../images/layout/open-context-gen-logo-med.png" alt="Open Context Logo">
														  </div>
														  <!--
														  <div style="padding:10%;">
																Open Context is a digital library-backed system for Web-based publication of
																research data.
																It enables publication, access, and reuse of editorially-reviewed
																data and media contributed by archaeologists and other researchers.
														  </div>
														  -->
													 </div>
													 <div class="carousel-caption">
														  <h4>Open Context publishes data contributed by researchers
														  through a process that reviews, edits, and aligns data to standards</h4>
													 </div>
												</div>
												
												<div class="item">
													 <div class="hero_image">
														  <img src="http://artiraq.org/static/opencontext/kenantepe/preview/Fieldphotos/2005/AreaD/D8L06095F9.JPG" alt="Image of archaeological excavation" />
													 </div>
													 <div class="carousel-caption">
														 <h4>Researchers submit data for Open Context publication that document excavations, surveys, and the analyses of collections</h4>
													 </div>
												</div>
												
												<div class="item">
													 <div class="hero_image">
														  <img src="../images/layout/OC-content-collage.png" alt="Examples of different types of content" />
													 </div>
													 <div class="carousel-caption">
														 <h4>Publishing with Open Context organizes and integrates data, media, documents, geospatial data
														 with authorship</h4>
													 </div>
												</div>
												
												<div class="item">
													 <div class="hero_image">
														  <div style="text-align:center; padding-top: 8%; padding-bottom: 2%;">
																<img src="../images/layout/Dhiban-sherd.png" alt="Pottery drawing">
														  </div>
														  <div style="text-align:center;">
																<a href="http://opencontext.org/subjects/4F8120E4-6DFB-4429-F428-95DD45806452" title="Link to sherd">http://opencontext.org/subjects/4F8120E4-6DFB-4429-F428-95DD45806452</a>
														  </div>
													 </div>
													 <div class="carousel-caption">
														 <h4>Every record in Open Context has its own stable URL, making it easy to reference and cite very specific items of data</h4>
													 </div>
												</div>
												
												
												<div class="item">
													 <div class="hero_image">
														  <div style="text-align:center;">
																<img src="../images/layout/wwwglobe.JPG" alt="World Wide Web Globe" />
														  </div>
													 </div>
													 <div class="carousel-caption">
														 <h4>Open Context links data to other resesearch collections on the Web,
														 making data easier to discover, integrate and use</h4>
													 </div>
												</div>
												
												
												<div class="item">
													 <div class="hero_image">
														  <div style="text-align:center;">
																<img src="../images/layout/open-data.jpg" alt="Open Data" />
														  </div>
													 </div>
													 <div class="carousel-caption">
														 <h4>Open Context's particiption in Linked Open Data enables sophisticated, cross-disciplinary
														 informatics based research</h4>
														 <p style="font-size: 75%;">Image Credit: <a href="http://www.flickr.com/photos/opensourceway/5538036200">Opensource.com</a> Some rights reserved.</p>
													 </div>
												</div>
												
												
												<div class="item">
													 <div class="hero_image">
														  <img src="../images/layout/doe-library.jpg" alt="University Library" />
													 </div>
													 <div class="carousel-caption">
														 <h4>To preserve irreplaceable data, Open Context archives data with the University of California, California Digital Library</h4>
														 <p style="font-size: 75%;">Image Credit: <a href="http://www.flickr.com/photos/parksdh/7796326226">D.H. Parks</a> Some rights reserved.</p>
													 </div>
												</div>
										  </div>
									 
										  <!-- http://www.flickr.com/photos/parksdh/7796326226 -->
									 
											<!-- Carousel nav -->
										  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&#171;</a>
										  <a class="carousel-control right" href="#myCarousel" data-slide="next">&#187;</a>
									 </div>
								</div>
						  </div>
					 </div>

					 <div style="margin-top:10%;">
						  <h3>Data Sharing as Publication</h3>
					  
						  <p>The research community increasingly expects access to high-quality data. Open Context specializes in the
						  review, documentation, and publication of research data contributed by scholars. Publishing data in Open Context
						  can complement and enhance conventional publication through comprehensive dissemination and preservation of
						  rich digital data and media. Major aspects of publishing with Open Contexct include:</p>
						  <ul class="big-list">
								<li>
									 Excavation, survey and collections data published in a citable venue
								</li>
								<li>
									 Expert editorial and peer review of your project's data
								</li>
								<li>
									 Track citations of your data along with your other publications
								</li>
								<li>
									 All content published free and open access, for barrier-free search, discovery and analysis
								</li>
								<li>
									 Alignment of data to key "Linked Open Data" standards to facilitate future analyses, data integration,
									 visualization, and understanding
								</li>
								<li>
									 Data safeguarded and preserved though archiving with the University of California's California Digital Library
								</li>
						  </ul>
						  </div>
					 </div>
			 
			 
				</div>
		
    </div> <!-- end main div -->
	
    
</div> <!-- end main div -->	 
	 <?php echo $this->render('footer.phtml'); //reader document footer ?>
	
</body>
</html>
