<?php
$host = OpenContext_OCConfig::get_host_config();
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
      <title>About Open Context</title>
      <link rel="schema.DC" href="http://purl.org/dc/terms" />
      <meta name="DC.title" content="About Open Context" />
      <meta name="DC.created" content="January 1, 2010" />
      <meta name="DC.date" content="January 1, 2011" />
      <meta name="DC.creator" content="Open Context Editors" />
      
      <link href="/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" /> 
		  <link href="/css/about-rev2.css" rel="stylesheet" type="text/css" /> 
		
      <link rel="shortcut icon" href="/images/layout/oc-favicon.ico" type="image/x-icon" />
		 <script src="<?php echo $host; ?>/js/jquery/jquery-1.7.2.min.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-transition.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-carousel.js" type="text/javascript"></script>
    
	 <script type="text/javascript">
        <!--
        
        $('.carousel').carousel();
        
        -->
    </script>

	 
	 
	 
	 
	 
	 
	 
	 </head>
    
<body>

<!-- 
    Logo,
-->    
<?php echo $this->render('header.phtml'); //reader document top ?>
   
<!-- 
    Navigation tabs, search box
-->
<?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>


<div id="main">
    <div id="main_content">
		  <div id="main_row">
				<div id="left_sidebar">
					 <div id="gksm-custom-menu-widget-3" class="widget gksm-custom-menu-widget">
						  <h2 class="widgettitle">About</h2>
						  <div class="submenu-widget submenu-widget-projects">
								<!--
								<ul id="menu-global-navigation-1" class="menu">
									 <li id="menu-item--11" class="menu-item menu-item-type-post_type menu-item-object-page menu-item--11"><a href="http://alexandriaarchive.org/projects/open-context/">Open Context</a></li>
<li id="menu-item--12" class="menu-item menu-item-type-post_type menu-item-object-page menu-item--12"><a href="http://alexandriaarchive.org/projects/heritage-bytes/">Heritage Bytes</a></li>
<li id="menu-item--13" class="menu-item menu-item-type-post_type menu-item-object-page menu-item--13"><a href="http://alexandriaarchive.org/projects/data-publishing/">Data Publishing</a></li>
<li id="menu-item--14" class="menu-item menu-item-type-post_type menu-item-object-page menu-item--14"><a href="http://alexandriaarchive.org/projects/data-journals/">Data Journals</a></li>
<li id="menu-item--15" class="menu-item menu-item-type-post_type menu-item-object-page menu-item--15"><a href="http://alexandriaarchive.org/projects/ipinch/">IPinCH</a></li>
<li id="menu-item--16" class="menu-item menu-item-type-post_type menu-item-object-page menu-item--16"><a href="http://alexandriaarchive.org/projects/dipir/">DIPIR</a></li>
<li id="menu-item--17" class="menu-item menu-item-type-post_type menu-item-object-page menu-item--17"><a href="http://alexandriaarchive.org/projects/bone-commons/">BoneCommons</a></li>
<li id="menu-item--18" class="menu-item menu-item-type-post_type menu-item-object-page menu-item--18"><a href="http://alexandriaarchive.org/projects/gane/">GANE</a></li>
<li id="menu-item--19" class="menu-item menu-item-type-post_type menu-item-object-page menu-item--19"><a href="http://alexandriaarchive.org/projects/maia/">Maia</a></li>
<li id="menu-item--20" class="menu-item menu-item-type-post_type menu-item-object-page menu-item--20"><a href="http://alexandriaarchive.org/projects/archaeology-2-0/">Archaeology 2.0</a></li>
<li id="menu-item--21" class="menu-item menu-item-type-post_type menu-item-object-page menu-item--21"><a href="http://alexandriaarchive.org/projects/ux-study/">UX Study</a></li>
<li id="menu-item--22" class="menu-item menu-item-type-post_type menu-item-object-page menu-item--22"><a href="http://alexandriaarchive.org/projects/oa-prize/">OA Prizes</a></li>
								</ul>
								-->
								<?php echo OpenContext_NavMenus::AboutNavMenu("index", $host); ?>
								
						  </div>
					 </div>
				</div>
				
				<div id="right_sidebar">
					 <div id="pageTop">
						  <div id="pageIntro">
								<h2 style="text-align:center;">About Open Context</h2>
								
								<div id="about-slides">
									 <div id="myCarousel" class="carousel slide">
										  <!-- Carousel items -->
										  <div class="carousel-inner">
												
												<div class="item active">
													 <div class="hero_image">
														  <div style="text-align:center; padding-top:18%; padding-bottom: 4%;">
																<img src="../images/layout/open-context-gen-logo-med.png" alt="Open Context Logo">
														  </div>
														  <!--
														  <div style="padding:10%;">
																Open Context is a digital library-backed system for Web-based publication of
																research data.
																It enables publication, access, and reuse of editorially-reviewed
																data and media contributed by archaeologists and other researchers.
														  </div>
														  -->
													 </div>
													 <div class="carousel-caption">
														  <h4>Open Context publishes data contributed by researchers
														  through a process that reviews, edits, and aligns data to standards</h4>
													 </div>
												</div>
												
												<div class="item">
													 <div class="hero_image">
														  <img src="http://artiraq.org/static/opencontext/kenantepe/preview/Fieldphotos/2005/AreaD/D8L06095F9.JPG" alt="Image of archaeological excavation" />
													 </div>
													 <div class="carousel-caption">
														 <h4>Researchers submit data for Open Context publication that document excavations, surveys, and the analyses of collections</h4>
													 </div>
												</div>
												
												<div class="item">
													 <div class="hero_image">
														  <img src="../images/layout/OC-content-collage.png" alt="Examples of different types of content" />
													 </div>
													 <div class="carousel-caption">
														 <h4>Publishing with Open Context organizes and integrates data, media, documents, geospatial data
														 with authorship</h4>
													 </div>
												</div>
												
												<div class="item">
													 <div class="hero_image">
														  <div style="text-align:center; padding-top: 8%; padding-bottom: 2%;">
																<img src="../images/layout/Dhiban-sherd.png" alt="Pottery drawing">
														  </div>
														  <div style="text-align:center;">
																<a href="http://opencontext.org/subjects/4F8120E4-6DFB-4429-F428-95DD45806452" title="Link to sherd">http://opencontext.org/subjects/4F8120E4-6DFB-4429-F428-95DD45806452</a>
														  </div>
													 </div>
													 <div class="carousel-caption">
														 <h4>Every record in Open Context has its own stable URL, making it easy to reference and cite very specific items of data</h4>
													 </div>
												</div>
												
												
												<div class="item">
													 <div class="hero_image">
														  <div style="text-align:center;">
																<img src="../images/layout/wwwglobe.JPG" alt="World Wide Web Globe" />
														  </div>
													 </div>
													 <div class="carousel-caption">
														 <h4>Open Context links data to other resesearch collections on the Web,
														 making data easier to discover, integrate and use</h4>
													 </div>
												</div>
												
												
												<div class="item">
													 <div class="hero_image">
														  <div style="text-align:center;padding-top: 8%;">
																<img src="../images/layout/open-data.jpg" alt="Open Data" />
														  </div>
													 </div>
													 <div class="carousel-caption">
														 <h4>Open Context's particiption in Linked Open Data enables sophisticated, cross-disciplinary
														 informatics based research</h4>
														 <p style="font-size: 75%;">Image Credit: <a href="http://www.flickr.com/photos/opensourceway/5538036200">Opensource.com</a> Some rights reserved.</p>
													 </div>
												</div>
												
												
												<div class="item">
													 <div class="hero_image">
														  <img src="../images/layout/doe-library.jpg" alt="University Library" />
													 </div>
													 <div class="carousel-caption">
														 <h4>To preserve irreplaceable data, Open Context archives data with the University of California, California Digital Library</h4>
														 <p style="font-size: 75%;">Image Credit: <a href="http://www.flickr.com/photos/parksdh/7796326226">D.H. Parks</a> Some rights reserved.</p>
													 </div>
												</div>
										  </div>
									 
										  <!-- http://www.flickr.com/photos/parksdh/7796326226 -->
									 
											<!-- Carousel nav -->
										  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&#171;</a>
										  <a class="carousel-control right" href="#myCarousel" data-slide="next">&#187;</a>
									 </div>
								</div>
						  </div>
					 </div>

					 <div>
						  <h3>Key Features</h3>
					  
						  <p>Open Context's main development efforts focus on "data portability," and using open standards
								 to share and move content around the Web. Some key aspects of Open Context's efforts to
								 make cultural heritage data more portable and open include:</p>
						  <ul>
								<li>
									 <p><em>Legal Interoperability:</em> Creative Commons licenses give explicit permissions for
											users to freely and legally use the material so long as they properly attribute the original creator. Creative
											Commons licenses include RDFa metadata that facilitates discovery of openly licensed content.
									 </p>
								</li>
							  <!--
							  <li><p class="bodyText"><em>Faceted Search:</em> Simple web services delivering machine-readable data can
											help make archaeological information open and reusable for research, instruction, and creativity. Searching
											and retrieving information from large bodies of complex data is a challenge for many digital libraries
											and information services. To avoid some of the hit-or-miss difficulties associated with keyword searches,
											Open Context uses a faceted navigation system. Faceted navigation allows users to explore hierarchically
											structured metadata with point-and-click selections and progressively home in on more specific information
											from a larger collection. Because filters are applied across an entire collection, users have greater
											certainty in comprehensiveness of results than with keyword searches and can simultaneously navigate
											between and within individual projects and collections. Feedback, as subtotals of the numbers of items
											in each facet, helps guide user selection of additional filters. </p></li>
							  -->
								<li>
									 <p><em>Machine-Readable Data:</em> Open Context makes data available in a variety of formats,
											both for human and machine consumption. This enables Open Context content to flow freely into other
											systems. Multiple digital archives and repositories can archive Open Context content,
											Open Context data can be freely loaded into other databases, and then used for new
											visualization and analysis.</p>
								</li>
								<li>
									 <p><em>Data Granularity:</em> Open Context makes individual records of each location and object retrievable with a URI.
											Researchers can therefore reference and cite specific records of data.  Open Context editors and outside
											researchers can also link Open Context data to sophisticated formal ontologies that integrate data
											across many disciplines.</p>
								</li>
											
						  </ul>
						  </div>
					 </div>
			 
			 
				</div>
		
    </div> <!-- end main div -->
	
    
</div> <!-- end main div -->	 
	 <?php echo $this->render('footer.phtml'); //reader document footer ?>
	
</body>
</html>
