
<?php
$host = OpenContext_OCConfig::get_host_config();
?>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
      <title>About Open Context: User Privacy</title>
      <link rel="schema.DC" href="http://purl.org/dc/terms" />
      <meta name="DC.title" content="About Open Context: User Privacy" />
      <meta name="DC.created" content="June 1, 2010" />
      <meta name="DC.date" content="June 1, 2011" />
      <meta name="DC.creator" content="Open Context Editors" />
      
      <link href="/css/opencontext_style.css" rel="stylesheet" type="text/css" /> 
      <link href="/css/test_landing_page.css" rel="stylesheet" type="text/css" />
      <link href="/css/default_banner.css" rel="stylesheet" type="text/css" />
      <link href="/css/rounded_corners.css" rel="stylesheet" type="text/css" />
      
      <link rel="shortcut icon" href="/images/general/oc_favicon.ico" type="image/x-icon" />
    </head>
    
<body>
    <div id="oc_logo">
	<a href="<?php echo $host; ?>" title="Open Context (Home)"><img alt="Open Context Logo" src="/images/general/oc_logo.jpg" border="0" ></img></a>
    </div>
    <div id="oc_tagline">
	<img alt="Open Context Tagline" src="/images/general/oc_tagline.jpg" ></img>
    </div>
    <div id="oc_beta">
	<img alt="Beta Stamp" src="/images/general/oc_betastamp.jpg" ></img>
    </div>
    
    <div id="oc_top_search">
	<form method="get" action="<?php echo $host;?>/search/" id="search-form">
	<div id="search_box">
	<input type='text' name='q' class='tinyText' value='Search' size='30' onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';" />
	</div>
	<div id="search_cntrl">
	    <input class="oc_top_sbutton" type="submit" value="" />
	</div>
	</form>
    </div>
   
   
   <!-- 
    Navigation tabs
    -->    
    <?php echo OpenContext_NavMenus::GeneralNavMenu("about"); ?>
    
    <div id="main">
	<div id="pageTop">
            <div id="pageIntro">
                <h2 style="text-align:center;">Open Context's Privacy Policy</h2>
                
                <div style="margin:10px;">
                    <p class="bodyText">All content in Open Context is freely and openly accessible.
		    Open Context requires no login to access and download data. Open Context refrains
		    from monitoring individual user activities, in a policy consistent with the <a href='http://ala.org/'
		    title='ALA Homepage'>American Library Association's</a> guidance for protecting patron rights to privacy,
		    confidentiality, and academic freedom. The absence of a login barrier also allows
		    Open Context content to be indexed by commercial search engines. </p>
		    
		    <p class="bodyText">User rights, as well as our institution's responsibilities, outlined in our privacy policy are based in part
	    on what are known in the United States as the five "Fair Information Practice Principles." These five principles
	    outline the rights of Notice, Choice, Access, Security, and Enforcement.</p>
	    
	    <p class="bodyText">Our commitment to user privacy and confidentiality has deep roots not only in law but also
	    in the ethics and practices of scholarly dissemination. Open Context follows the American Library Association
	    <a href='http://www.ala.org/ala/aboutala/offices/oif/statementspols/otherpolicies/guidelinesdevelopmentimplementation.cfm' title=''>recommendations</a>
	    for crafting user privacy policies that protect each user's "right to privacy and confidentiality with respect to information sought
	    or received and resources consulted, borrowed, acquired, or transmitted."
	    </p>
	    <br/>
	    <p class="bodyText"><em>Dowload the Open Context <a href='http://opencontext.org/docs/OpenContext_Privacy_Policy.pdf' title='Open Context Privacy (PDF)'>privacy policy here</a> (PDF document).</em>
	    </p>
	    
                </div>
            </div>
            <div id="about_submenu" class="rounded-corners">
                    <p class="bodyText"><em>More About Open Context:</em></p>
                    <?php echo OpenContext_NavMenus::AboutNavMenu("privacy", $host); ?>
            </div>
            <div id="pageTopEnd">
                <br/>
            </div>
        </div>
        
        
        <br/>
        <div style="margin:10px;">
            <!--
	    <p class="bodyText"><strong>Privacy Policy</strong></p>
	    <p class="bodyText">User rights, as well as our institution's responsibilities, outlined in our privacy policy are based in part
	    on what are known in the United States as the five "Fair Information Practice Principles." These five principles
	    outline the rights of Notice, Choice, Access, Security, and Enforcement.</p>
	    
	    <p class="bodyText">Our commitment to user privacy and confidentiality has deep roots not only in law but also
	    in the ethics and practices of scholarly dissemination. Open Context follows the American Library Association
	    <a href='http://www.ala.org/ala/aboutala/offices/oif/statementspols/otherpolicies/guidelinesdevelopmentimplementation.cfm' title=''>recommendations</a>
	    for crafting user privacy policies that protect each user's "right to privacy and confidentiality with respect to information sought
	    or received and resources consulted, borrowed, acquired, or transmitted."
	    </p>
	    <br/>
	    <p class="bodyText"><em>Dowload the Open Context <a href='http://opencontext.org/docs/OpenContext_Privacy_Policy.pdf' title='Open Context Privacy (PDF)'>privacy policy here</a> (PDF document).</em>
	    </p>
	    -->
	</div>
	
	<div id="bottom">
	</div>
	
    </div>

</body>
</html>
