<?php
$host = OpenContext_OCConfig::get_host_config();
$GoogleAPIkey = OpenContext_OCConfig::get_google_api();
$OAI_url = $host."/oai/request";
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
      <title>About Open Context: Web Services and APIs</title>
      <link rel="schema.DC" href="http://purl.org/dc/terms" />
      <meta name="DC.title" content="About Open Context: Web Services and APIs" />
      <meta name="DC.created" content="January 1, 2010" />
      <meta name="DC.date" content="November 7, 2012" />
      <meta name="DC.creator" content="Open Context Editors" />
      
      <link href="/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" /> 
		  <link href="/css/about-rev2.css" rel="stylesheet" type="text/css" /> 
		
      <link rel="shortcut icon" href="/images/layout/oc-favicon.ico" type="image/x-icon" />
		 <script src="<?php echo $host; ?>/js/jquery/jquery-1.7.2.min.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-transition.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-carousel.js" type="text/javascript"></script>
	 <script src="https://www.google.com/jsapi?key=<?php echo $GoogleAPIkey; ?>" type="text/javascript"></script>
    
	 <script type="text/javascript">
        <!--
        
        $('.carousel').carousel();
		  
        -->
    </script>

	 
	 <?php echo $this->render('news-widget-js.phtml'); //render javascript for displaying news feeds ?>
	 
	 
	 
	 
	 
	 </head>
    
<body>

<!-- 
    Logo,
-->    
<?php echo $this->render('header.phtml'); //render document top ?>
   
<!-- 
    Navigation tabs, search box
-->
<?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>


<div id="main">
    <div id="main_content">
		  <div id="main_row">
				
				<div id="left_sidebar">
					 
					 <div id="gksm-custom-menu-widget-3" class="widget gksm-custom-menu-widget">
						  <h2 class="widgettitle">About:</h2>
						  
						  <div class="submenu-widget submenu-widget-projects">
								<?php echo OpenContext_NavMenus::AboutNavMenu("services", $host); ?>
						  </div>
						  
					 </div>
					 
					 <?php echo $this->render('news-widget-dom.phtml'); //render news-widget-dom area ?>
					 
				</div>
				
				<!-- end left side div -->
				
				<div id="right_sidebar">
					 <div id="pageTop">
						  <div id="pageIntro">
								<h1 style="text-align:center;">Open Context API/Web-Services Documentation</h1>
								<p>In addition to the <a href="../about/concepts">Concepts</a> and <a href=""../about/technology">Technology</a> pages, this page provides extensive information about the nuts and bolts of how Open Context works. It is not necessary for all Open Context authors and users to understand the system at this level of detail, but we provide it here for those who are interested.</p>
								<p>Open Context provides simple web services to get content expressed in
            XHTML (for human use in browsers), the supported Atom Syndication Format (plus GeoRSS extensions),
	    JSON (Javascript Object Notation), and KML (the format used by GoogleEarth). Atom-based web services
	    provide a powerful set of query options to request items from a collection. Query parameters include: geographic,
            chronological, descriptive (based on how items are described), and social (based on relations
            between people and organizations and items from a collection). Query results are
            expressed as Atom feeds, an open format representing one of the most widely deployed and supported
            standards on the Web. By expressing query results in Atom (and JSON or KML), Open Context collections can be easily
            recombined with collections from Flickr in innovative mashups, with news items from journalists
            or bloggers, or even displayed in personal profiles in Facebook.</p>
								<p>You can make requests to Open Context with queries
            specified in a number of dimensions as indicated in Table 1 below. Note, a very similar web-service
            is available for images. Simply replace 'sets' with 'lightbox' to get image items.
								</p>		
						  </div>
						  
					 </div>

					 <div>
						  <h2>Table 1: Query Parameters to Retrieve Sets of Items</h2>
						  
						  <table class="table table-striped" id="parameters">
								<thead>
									 <tr>
										  <th class="param">Parameter</th>
										  <th class="param-vals">Possible Values</th>
										  <th class="param-des">Description</th>
									 </tr>
								</thead>
								<tbody>
									 <tr>
										  <td>(Context path)</td>
										  <td>Slash separated values of URL-encoded text. Use two pipe characers ('||') for OR terms.</td>
										  <td>
												<p>This represents spatial containment &#8220;paths&#8221; with larger
												locations and objects containing nested (child) locations and objects.
												</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/sets/Turkey/Domuztepe/I/Lot+1704">http://opencontext.org/sets/Turkey/Domuztepe/I/Lot+1704</a>
												retrieves items from inside Lot 1704 at Domuztepe, Operation I.</li>
													 <li><a href="http://opencontext.org/sets/Jordan/Petra+Great+Temple/Propylaeum||Temple?cat=Animal%20Bone">http://opencontext.org/sets/Jordan/Petra+Great+Temple/Propylaeum||Temple?cat=Animal%20Bone</a>
												retrieves items from inside the Petra Great Temple Propylaeum OR from Temple contexts.</li>
												</ul>
										  </td>
									 </tr>
									 
									 <tr>
										  <td>q</td>
										  <td>URL-encoded text</td>
										  <td>
												<p>This works like Google's search, and performs a full-text search of Open Context.
												Multiple text values can be passed to this, or you can search for an exact phrase
												by placing the phrase in quotes.
												</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/sets/?q=gold">http://opencontext.org/sets/?q=gold</a>
			 retrieves items with "gold" somewhere in their description.</li>
												</ul>
										  </td>
									 </tr>
									 
									 <tr>
										  <td>bBox</td>
										  <td>Comma separated list of 4 numbers representing decimal degree coordinates (WGS84 datum).</td>
										  <td>
												<p>These four arguments are used together to form a quadrant of the earth's
												surface for locating data. The first two numbers represent the coordinates of the
												south-west corner of the bounding box, while the last two numbers represent
												the coordinates of the north-east corner of the bounding box. 
												</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a rel="nofollow" href="http://opencontext.org/sets/?bBox=30,30,50,50">http://opencontext.org/sets/?bBox=30,30,50,50</a>
			 retrieves items located in the region bound by the coordinates: 30E, 30N to 50E, 50N (very roughly southwest Asia).</li>
												</ul>
										  </td>
									 </tr>
									 
									 <tr>
										  <td>proj</td>
										  <td>URL-encoded text. Use two pipe characers ('||') for OR terms.</td>
										  <td>
												<p>This parameter filters by the names of projects / collections. Limit of 128 characters. 
												</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/sets/?proj=Domuztepe+Excavations">http://opencontext.org/sets/?proj=Domuztepe+Excavations</a>
			 retrieves items from the "Domuztepe Excavations" project.</li>
												</ul>
										  </td>
									 </tr>
									 
									 <tr>
										  <td>cat</td>
										  <td>URL-encoded text</td>
										  <td>
												<p>This parameter filters content by its general category (&#8220;Animal Bone&#8221;, &#8220;Small Find&#8221;, etc.)
												</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/sets/?cat=Small+Find">http://opencontext.org/sets/?cat=Small+Find</a>
			 retrieves items described by the general category "Small Finds".</li>
													 <li><a href="http://opencontext.org/sets/?cat=Animal+Bone||Shell||Human+Bone">http://opencontext.org/sets/?cat=Animal+Bone||Shell||Human+Bone</a>
			 retrieves items under the general category of "Animal Bone", "Shell", or "Human Bone".
													 </li>
												</ul>
										  </td>
									 </tr>
									 
									 <tr id="query-taxa">
										  <td>taxa[]</td>
										  <td>URL-encoded text. Use this parameter to query for desciptive properties and hierarchic taxonomies.
												These properties can be simple variable-value pairs, or deeper hierarchical taxonomies with nodes
												seperated by two colons ('::'). Numeric values can be proceeded by 'URL-encoded
												'&gt;', '&gt;=', '&lt;', or '&lt;='  to make range queries.) Use two pipe characters ('||') for OR terms.</td>
										  <td>
												<p>This parameter is for querying the descriptive properties and hierarchic taxonomies used by data contributors.
												For the most part, descriptive properties in Open Context have a very "flat" hierarchy, and are simply variable
												/ value pairs, expressed as 'taxa[]={variable}::{value}', where 2 colons ('::') seperate the variable from the value.
												A deeper taxonomic tree can be queried as follows: 'taxa[]={node}::{node}::{node}'.
												</p>
												<h5>Examples:</h5>
												<ol class="service-examples">
													 <li><a href="http://opencontext.org/sets/?cat=Small+Find&amp;taxa%5B%5D=Object">http://opencontext.org/sets/?cat=Small+Find&amp;taxa%5B%5D=Object</a>
			 retrieves items described by the general category "Small Finds", and described by the property "Object" (a variable).</li>
													 <li><a href="http://opencontext.org/sets/?cat=Small+Find&amp;taxa%5B%5D=Object::Lamp">http://opencontext.org/sets/?cat=Small+Find&amp;taxa%5B%5D=Object::Lamp</a> retrieves items described by the general category "Small Finds", and described by the property "Object" (variable), "Lamp" (value).
													 </li>
													 <li><a href="http://opencontext.org/sets/?proj=Domuztepe+Excavations&amp;taxa%5B%5D=Fragment+Length+%28mm%29::%3E%3D116,%3C174">http://opencontext.org/sets/?proj=Domuztepe+Excavations&amp;taxa%5B%5D=Fragment+Length+%28mm%29%3E%3D116,%3C174</a>
			 retrieves items from the "Domuztepe Excavations" project, described by the property "Fragment Length (mm)" (variable), with values ranging from 116 to 174.</li>
												</ol>
										  </td>
									 </tr>
									 
									 <tr id="query-rel">
										  <td>rel[]</td>
										  <td>URL-encoded text. Use this parameter to query Open Context using URI-identified concepts.
										  Use two pipe characters ('||') for OR terms.</td>
										  <td>
												<p>This parameter is for querying Open Context using URI-identified concepts.
												Please note, Open Context does not (yet) have a triple-store nor is this parameter used for SPARQL.
												This parameter is simply used to query Open Context for subjects (URI-identifed documents describing
												individual locations and objects) based on very simple relations to URI identified concepts.
												In 'Linked Data' terms, the items returned in a query are the 'subjects' while the
												'predicate' and 'object' (or 'target') are expressed as URI identified concepts seperated
												by 2 colons ('::') according to this template: 'rel[]={URI identified predicate}::{URI identified object}'.
												</p>
												<h5>Examples:</h5>
												<ol class="service-examples">
													 <li><a href="http://opencontext.org/sets/?rel%5B%5D=http%3A%2F%2Fgawd.atlantides.org%2Fterms%2Forigin">
													 http://opencontext.org/sets/?rel%5B%5D= http%3A%2F%2Fgawd.atlantides.org%2Fterms%2Forigin</a>
			 retrieves items with a predicate 'has origin place', using the Concordia Vocabulary and identified by the URI: http://gawd.atlantides.org/terms/origin</li>
													 <li><a href="http://opencontext.org/sets/?rel%5B%5D=http%3A%2F%2Fgawd.atlantides.org%2Fterms%2Forigin%3A%3Ahttp%3A%2F%2Fpleiades.stoa.org%2Fplaces%2F520985">http://opencontext.org/sets/?rel%5B%5D=http%3A%2F%2Fgawd.atlantides.org%2Fterms%2Forigin:: http%3A%2F%2Fpleiades.stoa.org%2Fplaces%2F520985</a>
			 retrieves items with a predicate 'has origin place' and the object / target place 'Byzantium', identified the URI: http://pleiades.stoa.org/places/520985
													 </li>
													 <li><a href="http://opencontext.org/sets/?rel[]=http%3A%2F%2Fpurl.org%2FNET%2Fbiol%2Fns%23term_hasTaxonomy::http%3A%2F%2Feol.org%2Fpages%2F328699||http%3A%2F%2Feol.org%2Fpages%2F11021570">http://opencontext.org/sets/?rel[]=http%3A%2F%2Fpurl.org%2FNET%2Fbiol%2Fns%23term_hasTaxonomy:: http%3A%2F%2Feol.org%2Fpages%2F328699|| http%3A%2F%2Feol.org%2Fpages%2F11021570</a>
			 retrieves items with a predicate 'has biological taxonomy' and the object / target taxa as 'Bos taurus' OR 'Bos primigenius' (from the Encyclopedia of Life)
													 </li>
												</ol>
										  </td>
									 </tr>
									 
									 <tr>
										  <td>targURI</td>
										  <td>URL-encoded text. Use this parameter to query Open Context using URI-identified concepts
										  of the object / target entities of a relationship. Use two pipe characters ('||') for OR terms.</td>
										  <td>
												<p>This parameter is for querying Open Context using URI-identified concepts where the
												predicate relationship is not known or does not matter.
												It works according to this template: 'targURI={URI identified object}'.
												</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/sets/?targURI=http%3A%2F%2Fpleiades.stoa.org%2Fplaces%2F520985">http://opencontext.org/sets/?targURI=http%3A%2F%2Fpleiades.stoa.org%2Fplaces%2F520985</a>
			 retrieves items with any kind of relationship with the object / target place 'Byzantium', identified the URI: http://pleiades.stoa.org/places/520985
													 </li>
												</ul>
										  </td>
									 </tr>
									 
									 <tr>
										  <td>(DEPRECATED) prop[*]</td>
										  <td>URL-encoded text(variable names within the square brackets)</td>
										  <td>
												<p><strong>NOTE:</strong> This parameter is deprecated. For the time being, Open Context will still
												resolve queries using this parameter, but the preferred parameter for querying
												descriptive properties is "taxa[]", described above.
												</p>
												<p>This parameter is for querying descriptive properties. Properties are variable /
												value pairs in Open Context, and they represent the how data
												providers describe their observations. The name of the variable is indicated in the square bracket,
												and the corresponding value for the property is indicated by the value assigned to this parameter.
												</p>
												<h5>Examples:</h5>
												<ol class="service-examples">
													 <li><a href="http://opencontext.org/sets/?cat=Small+Find&amp;prop%5BObject%5D=Lamp">
													 http://opencontext.org/sets/?cat=Small+Find&amp;prop%5BObject%5D=Lamp</a> retrieves items
													 described by the general category "Small Finds", and described by the property "Object" (variable), "Lamp" (value).
													 </li>
													 <li><a href="http://opencontext.org/sets/?proj=Domuztepe+Excavations&amp;prop%5BFragment+Length+%28mm%29%5D=%3E%3D116,%3C174">
													 http://opencontext.org/sets/?proj=Domuztepe+Excavations&amp;prop%5BFragment+Length+%28mm%29%5D=%3E%3D116,%3C174</a>
														  retrieves items from the "Domuztepe Excavations" project, described by the property "Fragment Length (mm)"
														  (variable), with values ranging from 116 to 174.
													 </li>
												</ol>
										  </td>
									 </tr>
									 
									 <tr>
										  <td>person</td>
										  <td>URL-encoded text</td>
										  <td>
												<p>This parameter filters content by individual people and organizations associated with the content
												(authors, observers, analysts, etc.). Use two pipe characers ('||') for OR terms.
												</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/sets/?proj=Domuztepe+Excavations&amp;person=Elizabeth+Carter">
													 http://opencontext.org/sets/?proj=Domuztepe+Excavations&amp;person=Elizabeth+Carter</a>
														  retrieves items from the "Domuztepe Excavations" project, associated with the person, Elizabeth Carter.
													 </li>
												</ul>
										  </td>
									 </tr>
									 
									 <tr>
										  <td>t-start</td>
										  <td>Numeric value</td>
										  <td>
												<p>This parameter filters content by date, with t-start being the earliest date limit.
												</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/sets/?t-start=-1500&amp;t-end=500">
													 http://opencontext.org/sets/?t-start=-1500&amp;t-end=500</a>
														  retrieves items from Open Context with dates ranging from 1500 BCE to 500 CE.
													 </li>
												</ul>
										  </td>
									 </tr>
									 
									 <tr>
										  <td>t-end</td>
										  <td>Numeric value</td>
										  <td>
												<p>This parameter filters content by date, with t-end being the latest date limit.
												</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/sets/?t-start=-1500&amp;t-end=500">
													 http://opencontext.org/sets/?t-start=-1500&amp;t-end=500</a>
														  retrieves items from Open Context with dates ranging from 1500 BCE to 500 CE.
													 </li>
												</ul>
										  </td>
									 </tr>
									 
									 <tr>
										  <td>image</td>
										  <td>true</td>
										  <td>
												<p>This parameter filters content by links to images. When the value for
												this parameter is true, only items associated with images are retrieved.
												</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/sets/?image=true">http://opencontext.org/sets/?image=true</a>
														  retrieves items from Open Context associated with images.
													 </li>
												</ul>
										  </td>
									 </tr>
									 
									 <tr>
										  <td>diary</td>
										  <td>true</td>
										  <td>
												<p>This parameter filters content by links to documents (diaries, logs, or other narrative documentation). When the value for
												this parameter is true, only items associated with documents are retrieved.
												</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/sets/?diary=true">http://opencontext.org/sets/?diary=true</a>
														  retrieves items from Open Context associated with documents.
													 </li>
												</ul>
										  </td>
									 </tr>
									 
									 <tr>
										  <td>sort</td>
										  <td>"label", "cat", "context", "proj", "created", "updated". (defaults to ascending order. ':desc' changes to descending order)</td>
										  <td>
												<p>This parameter changes the sort-order of search result items retrieved from Open Context.
												By default, Open Context sorts search results by "interestingness". More interesting items
												have more description and more links to associated media (images, documents, etc.).
												By default, these more richly described items are ranked higher in searches.
												To change sort order, add the "sort" parameter to queries as follows:
												</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/sets/Jordan/?proj=Petra+Great+Temple+Excavations&amp;cat=Animal+Bone&amp;sort=label" title="Example sorting by Label">Label</a> sort by item label or name.
													 </li>
													 <li><a href="http://opencontext.org/sets/Jordan/?proj=Petra+Great+Temple+Excavations&amp;cat=Animal+Bone&amp;sort=created" title="Example sorting by Publication time">Created</a> sort by item publication / creation time.
													 </li>
													 <li><a href="http://opencontext.org/sets/Jordan/?proj=Petra+Great+Temple+Excavations&amp;cat=Animal+Bone&amp;sort=updated:desc" title="Example sorting by Update time, descending order">Updated</a> sort by item update time (edits, changes) in descending order.</li>
													 <li><a href="http://opencontext.org/sets/Jordan/?proj=Petra+Great+Temple+Excavations&amp;sort=cat" title="Example sorting by Category">Cat</a> sort by item category ("animal bone", "small find", "locus", etc.).
													 </li>
													 <li><a href="http://opencontext.org/sets/Jordan/?sort=context" title="Example sorting by Context">Context</a> sort by spatial context.</li>
													 <li><a href="http://opencontext.org/sets/?bBox=30,30,50,50&amp;sort=proj" title="Example sorting by Project">Project</a> sort by project.</li>
												</ul>
										  </td>
									 </tr>
									 
									 <tr>
										  <td>recs</td>
										  <td>Positive integer values, ranging from 1 to 50</td>
										  <td>
												<p>This parameter changes the number of items displayed from a query.
												By default, Open Context shows 10 items from queries on locations and objects,
												and 18 thumbnails for image searches. Note: many queries return many more results
												than can be displayed at once. Use the "page" parameter described below to page through long sets of query results.
												</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/sets/Turkey/?recs=50">http://opencontext.org/sets/Turkey/?recs=50</a>
														  displays the first 50 search results for items in Turkey.
													 </li>
												</ul>
										  </td>
									 </tr>
									 
									 <tr>
										  <td>page</td>
										  <td>Positive integer values</td>
										  <td>
												<p>Open Context often returns large numbers of items from queries. Because it is not feasible to
												display hundreds or thousands of results at once, large sets of results are delivered in different "pages".
												Open Context returns search results using the Atom Syndication Format (see below). This Atom representation
												has link elements pointing to different pages of search results.
												</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/sets/Turkey/?recs=50&amp;page=2">http://opencontext.org/sets/Turkey/?recs=50&amp;page=2</a>
														  displays the second page of search results for items in Turkey (50 items per page)
													 </li>
												</ul>
										  </td>
									 </tr>
									 
								</tbody>
						  </table>
		
						  <h2>Faceted Search Results and Representations</h2>
						  <p>Query results are provided both in summary form and as a list of individual records that match your
						  query criteria. Currently, the user interface of Open Context provides both a summary and list of
						  individual records (in the XHTML representation). To be more specific, the summary form is a list of &#8220;facets&#8221;
						  that describe  the overall characteristics of a query result set. These facets can be retrieved in the Atom Syndication Format,
						  JSON or in KML. Individual records of query results can be retrieved in Atom, JSON, or KML. See table 2 below for examples.
						  </p>
						  
						  <h3>Table 2: Query Result Representations</h3>
						  <table class="table table-striped" id="query-representations">
								<thead>
									 <tr>
										  <th>Representation</th>
										  <th>Description and Example</th>
									 </tr>
								</thead>
								<tbody>
									 <tr>
										  <td>XHTML</td>
										  <td>
												<p>XHTML version, showing available facets on the left</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/sets">http://opencontext.org/sets</a>
													 </li>
												</ul>
										  </td>
									 </tr>
									 
									 <tr id="atom-facets" >
										  <td>Atom (facets / summarized query results)</td>
										  <td>
												<p>Atom feed of facets that summarize overall characteristics of the query result set. Feed-entries
												have different facets and facet counts, where <span class="code">&lt;link&gt;</span> elements have links
												to futher filter the query according to the facet expressed in the entry.
												Geo-spatial facets have locational information expressed in GeoRSS. </p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=http:%2F%2Fopencontext.org%2Fsets%2Ffacets%2FJordan||Israel||Palestinian%2BAuthority.atom&amp;sll=37.0625,-95.677068&amp;sspn=45.197878,92.021484&amp;ie=UTF8&amp;ll=31.672083,35.540771&amp;spn=3.052508,5.751343&amp;z=8" title="View contexts mapped in Google">Atom 'facet feed' visualized in Google Maps</a>
													 </li>
												</ul>
										  </td>
									 </tr>
									 
									 <tr id="json-facets" >
										  <td>JSON (facets / summarized query results)</td>
										  <td>
												<p>JSON expression of facets that summarize overall characteristics of the query result set. Geo-spatial facets have
												locational information and chronological expressed in as &#8220;<span class="code">geoLat</span>&#8221;, &#8220;<span class="code">geoLong</span>&#8221;,
												&#8220;<span class="code">timeBegin</span>&#8221; and &#8220;<span class="code">timeEnd</span>&#8221; elements.
												These can be further processed for use with the <a href='http://code.google.com/p/timemap/'>Timemap.js</a> library.</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/sets/facets/.json">http://opencontext.org/sets/facets/.json</a></li>
												</ul>
										  </td>
									 </tr>
									 
									 <tr id="kml-facets" >
										  <td>KML (facets / summarized query results)</td>
										  <td>
												<p>KML of the geo-spatial facets that summarize overall characteristics of the query result set.
												In this case, because there are no query parameters in this request, this returns a summary of all Open Context content.
												Only geo-spatial facets are provided in this representation, since other types of facets don't make visualization
												sense in applications like Google Earth.</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/sets/facets/.kml">http://opencontext.org/sets/facets/.kml</a></li>
												</ul>
										  </td>
									 </tr>
									 
									 <tr id="atom-results" >
										  <td>Atom (individual search result records)</td>
										  <td>
												<p>Atom feed of individual records resulting from a query. Open Search extensions provide a
												summary of the number of results and feed &#8211; paging provides links to other pages of
												a search result set. All items have location information expressed in GeoRSS. The Atom
												&#8220;<span class="code">&lt;link&gt;</span>&#8221; element with the attribute
												<span class="code">rel='self'</span> points to the Atom
												representation of that specific record and its full ArchaeoML representation.</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/sets/.atom">http://opencontext.org/sets/.atom</a></li>
												</ul>
										  </td>
									 </tr>
									 
									 <tr id="json-results" >
										  <td>JSON (individual search result records)</td>
										  <td>
												<p>As a convenience for developers who want to create their own search portal for Open Context
												or a sub-set of Open Context content, we offer a JSON represntation with comprehensive faceted
												search information <em>and</em> individual search result items. As with the JSON-facets service
												above, geo-spatial facets have lat / lon point data as well as time range data.
												These can be further processed for use with the
												<a href='http://code.google.com/p/timemap/'>Timemap.js</a> library.</p>
												<p><strong>Note:</strong> Open context also offers a
												<a href='http://en.wikipedia.org/wiki/JSON#JSONP' title='Link to a Wikipedia discussion'>JSON/P</a>
												("JSON with Padding") representation. JSON/P is a useful workaround for "cross domain problems".
												It lets third-parties create web-pages using Open Context data without having those data first
												go to their server, and then to clients. To make JSON/P requests, simply add the parameter "callback"
												with its value set to the name of the function that you want to use to "pad" the JSON data.</p>
												
												<h5>Plain JSON Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/sets/Palestinian+Authority/Tell+en-Nasbeh/.json?proj=Bade+Museum" title="Plain JSON">http://opencontext.org/sets/Palestinian+Authority/Tell+en-Nasbeh/.json?proj=Bade+Museum</a> plain JSON</li>
													 <li> <a href="http://bade.psr.edu/content/tell-en-nasbeh-database" title="Link to working example of this service">Bade Museum Website</a> uses the Open Context the JSON service shown above</li>
													 <li><a href="http://opencontext.org/sets/.json?cat=Animal+Bone||Shell" title="Plain JSON">http://opencontext.org/sets/.json?cat=Animal+Bone||Shell</a> plain JSON</li>
													 <li> <a href="http://alexandriaarchive.org/bonecommons/datasets" title="Link to working example of this service">BoneCommons- Datasets</a> uses the Open Context the JSON service as shown above</li>
												</ul>
												
												<h5>JSON/P Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/sets/.json?callback=loadit" title="JSON/P example">http://opencontext.org/sets/.json?callback=loadit</a> JSON padded within a function called "loadit"</li>
													 <li><a href="http://visiblepast.net/see/archives/591" title="Link to working example of this service">Visible Past</a> uses the Open Context JSONP service</li>
												</ul>
										  </td>
									 </tr>
									 
									 
									 <tr id="geojson" >
										  <td>GeoJSON (spatial context facets)</td>
										  <td>
												<p>Open Context offers a <a href='http://geojson.org/geojson-spec.html'>GeoJSON</a> representation of geospatial metadata facets.
												GeoJSON is widely supported by many mapping libraries and is an increasingly popular format for expressing spatial data.
												The Open Context GeoJSON service can also be accessed as JSON/P data. To make JSON/P requests, simply add the parameter "callback"
												with its value set to the name of the function that you want to use to "pad" the JSON data.</p>
												
												<h5>Plain GeoJSON Example:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/sets/Turkey/Kenan+Tepe.geojson" title="Plain GeoJSON">http://opencontext.org/sets/Turkey/Kenan+Tepe.geojson</a> plain JSON</li>
												</ul>
												
												<h5>(Geo)JSON/P Example:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/sets/Turkey/Kenan+Tepe.geojson?callback=loadit" title="(Geo)JSON/P example">http://opencontext.org/sets/Turkey/Kenan+Tepe.geojson?callback=loadit</a> GeoJSON padded within a function called "loadit"</li>
												</ul>
										  </td>
									 </tr>
									 
									 
								</tbody>
						  </table>
						  
						  <h2>Representations of Individual Items / Records</h2>
						  <p>Open Context offers multiple representations of individual data records / items in XHTML, Atom, and ArchaeoML-XML.
						  The ArchaeoML-XML representation is currently the richest and most comprehesive expression of Open Context data.
						  We are currently also developing RDF representations representation that include mappings to the CIDOC-CRM.
						  Here are some examples on how to retrieve these representations of Open Context resources:</p>
						  
						  <h3>Table 3: Item Representations</h3>
						  <table class="table table-striped" id="item-representations">
								<thead>
									 <tr>
										  <th>Representation</th>
										  <th>Description and Examples</th>
									 </tr>
								</thead>
								<tbody>
									 <tr>
										  <td>XHTML + RDFa</td>
										  <td>
												<p>This representation is given for rendering content in web browsers. Some linked data information
												(particularly Dublin Core metadata) is expressed in RDFa mark-up in this representation.</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/subjects/E54B6571-265E-45C1-054D-C272E8515E8D">http://opencontext.org/subjects/E54B6571-265E-45C1-054D-C272E8515E8D</a>
														  displays a <a href="../about/concepts#subjects" title="See definition">subject</a> (location or object) item.
													 </li>
													 <li><a href="http://opencontext.org/media/D9EEF2A7-278B-4A16-1D5A-3E1C99CFCB53">http://opencontext.org/media/D9EEF2A7-278B-4A16-1D5A-3E1C99CFCB53</a>
														  displays a <a href="../about/concepts#media" title="See definition">media</a> resource item.
													 </li>
													 <li><a href="http://opencontext.org/media/D9EEF2A7-278B-4A16-1D5A-3E1C99CFCB53/full">http://opencontext.org/media/D9EEF2A7-278B-4A16-1D5A-3E1C99CFCB53/full</a>
														  displays a full-resolution version of a media resource item.
													 </li>
												</ul>
										  </td>
									 </tr>
									 <tr>
										  <td>Atom</td>
										  <td>
												<p>An Atom <span class="code">&lt;entry&gt;</span> representation provides some simple metadata about each
												Open Context resource (data items / records).</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/subjects/E54B6571-265E-45C1-054D-C272E8515E8D.atom">http://opencontext.org/subjects/E54B6571-265E-45C1-054D-C272E8515E8D.atom</a>
														  returns a <a href="../about/concepts#subjects" title="See definition">subject</a> (location or object) item as an Atom entry.
														  If applicable, <span class="code">&lt;link&gt;</span> elements may point to related linked data.
													 </li>
													 <li><a href="http://opencontext.org/media/D9EEF2A7-278B-4A16-1D5A-3E1C99CFCB53.atom">http://opencontext.org/media/D9EEF2A7-278B-4A16-1D5A-3E1C99CFCB53.atom</a>
														  returns a <a href="../about/concepts#media" title="See definition">media</a> resource item, with <span class="code">&lt;link&gt;</span>
														  elements pointing to thumbnail, preview, and full versions of media files.
													 </li>
													 
												</ul>
										  </td>
									 </tr>
									 <tr>
										  <td>ArchaeoML (XML)</td>
										  <td>
												<p>Open Context uses <a href="../about/concepts#archaeoml">ArchaeoML-XML</a> as its internal data
												structure. Making ArchaeoML representations publicly available makes Open Context data full portable.
												ArchaeoML representations are currently the richest and most comprehesive expressions of Open Context data.
												We use <a href="https://github.com/ekansa/Open-Context-Data/" title="Open Context data in GitHub">GitHub</a> for version control of ArchaeoML documents. For long term preservation,
												the California Digital Library archives these data.
												</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/subjects/E54B6571-265E-45C1-054D-C272E8515E8D.xml">http://opencontext.org/subjects/E54B6571-265E-45C1-054D-C272E8515E8D.xml</a>
														  returns a <a href="../about/concepts#subjects" title="See definition">subject</a> (location or object) item as an ArchaeoML document.
													 </li>
													 <li><a href="https://github.com/ekansa/Open-Context-Data/tree/master/data/A5DDBEA2-B3C8-43F9-8151-33343CBDC857/subjects/E54B6571-265E-45C1-054D-C272E8515E8D.xml">https://github.com/ekansa/Open-Context-Data/tree/master/data/A5DDBEA2-B3C8-43F9-8151-33343CBDC857/subjects/E54B6571-265E-45C1-054D-C272E8515E8D.xml</a>
														  returns the GitHub version-control resource for this ArchaeoML document.
													 </li>
													 <li><a href="http://opencontext.org/media/D9EEF2A7-278B-4A16-1D5A-3E1C99CFCB53.atom">http://opencontext.org/media/D9EEF2A7-278B-4A16-1D5A-3E1C99CFCB53.atom</a>
														  returns a <a href="../about/concepts#media" title="See definition">media</a> resource document in ArchaeoML. This descibes a media file
														  that may have one or more versions (thumbnail, preview, full).
													 </li>
													 
												</ul>
										  </td>
									 </tr>
									 <tr>
										  <td>RDF</td>
										  <td>
												<p>We are currently developing RDF representations (in RDF/XML and RDF/Turtle) for richer
												and easier to parse expression of linked data than in the XHTML+RDFa format. 
												</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li>Check back soon!
													 </li>
													 
												</ul>
										  </td>
									 </tr>
								</tbody>
						  </table>
						  
						  <h2>Other Web-Services</h2>
						  <p>Open Context also has a variety of other Web services to share updates, use metrics, metadata, and assist in linked data projects.
						  These services are listed in table 4 below.</p>
						  
						  <h3>Table 4: Other Web Services</h3>
						  <table class="table table-striped" id="other-services">
								<thead>
									 <tr>
										  <th>Service</th>
										  <th>Description and Examples</th>
									 </tr>
								</thead>
								<tbody>
									 <tr>
										  <td>
										  OAI-PMH<br/>
										  <a href="http://www.openarchives.org/" title="Learn more about OAI-PMH"><img src="../images/general/oai_logo.gif" alt="OAI-PMH Logo" /></a>
										  </td>
										  <td><p>In addition to the services described below, Open Context is registered in
										  the <a href="http://www.openarchives.org/Register/BrowseSites?viewRecord=http://opencontext.org/oai/request">OAI database</a>
										  of conforming repositories. Open Context's OAI-PMH (Ver. 2) service is
										  located at: <a href="<?php echo $OAI_url; ?>"><?php echo $OAI_url; ?></a> (Note: Add OAI-PMH parameters)</p>
										  </td>
									 </tr>
									 <tr>
										  <td>
										  Atom Feed of Projects
										  </td>
										  <td>
												<p>Open Context provides an Atom+GeoRSS feed of summary descriptions of all projects and collections.
										  The feed is sorted by date of publication in descending order. This feed most closely parallels more familiar applications of
										  the Atom Syndication format.</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/projects/.atom">http://opencontext.org/projects/.atom</a>
													 </li>
													 
												</ul>
										  </td>
									 </tr>
									 <tr>
										  <td>
										  Atom Feed of All Content
										  </td>
										  <td>
												<p>Open Context provides this update-time sorted (most recent first) feed provides a comprehensive
												list of all Open Context content. Digital archives can use this paged feed to retrieve all resources
												relevant to data curation from Open Context.</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/all/.atom">http://opencontext.org/all/.atom</a>
													 </li>
												</ul>
										  </td>
									 </tr>
									 <tr>
										  <td>
										  Pelagios Annotations (RDF as N-Triples)
										  </td>
										  <td>
												<p>Open Context annotates relevant data with geographic place references using the <a href="http://pleiades.stoa.org/">Pleiades</a>
												and <a href="http://geonames.org">GeoNames</a> gazetteers. These annotations conform to the
												requirements of the <a href="http://pelagios.dme.ait.ac.at/api/datasets/739128af1e9613de03706a57cef46976"
												title="Open Context place annotations">Pelagios Project</a>. We offer a RDF data-dump of these annotations as a fully public
												domain open dataset (CC-Zero).</p>
												<h5>Examples:</h5>
												<ul class="service-examples">
													 <li><a href="http://opencontext.org/export/pelagios">http://opencontext.org/export/pelagios</a> data dump of Pelagios place
													 annotations
													 </li>
													 <li><a href="http://opencontext.org/export/pelagios-void">http://opencontext.org/export/pelagios-void</a> an RDF-Turtle
													 <a href="https://github.com/pelagios/pelagios-cookbook/wiki/Adding-Dataset-Metadata-with-VoID">VoID</a> file describing metadata about the Pelagios place annotations linked above
													 </li>
												</ul>
										  </td>
									 </tr>
								</tbody>
						  </table>
						  
						  <div id="reconcile">
								<h3>Entity Reconciliation Service (IN TESTING)</h3>
								<p>Open Context is currently <strong>alpha-testing</strong> an entity reconciliation service (see this
								<a href="http://wiki.freebase.com/wiki/Reconciliation">definition from Freebase</a>).
								One can use Open Context's service to look up Web identifiers for certain concepts linked by Open Context.
								By doing so, you can precisely relate key concepts and entities in a dataset to concepts published on the Web.
								Currently, Open Context's reconciliation service only supports look-ups to find
								<a href="http://eol.org">Encyclopedia of Life</a> (EOL) identifiers for biological taxa. However,
								we will shortly offer additional options for reconciling terms against other bio-informatics vocabularies. We hope to support
								reconcilation against certain concepts used to describe material culture as well.</p>
								
								<p>Unless you are a programmer, it is easiest to use <a href="http://code.google.com/p/google-refine/">Google Refine</a>
								to use this reconciliation service. Google Refine is an open source data review and editing tool that also has powerful features
								to use Web-APIs. It can be used to work with Open Context's reconciliation service as described below:</p>
								
								<h4>Procedure (in Google Refine)</h4>
								<ol>
									<li class="rec-item">Click on the column with biological taxa terms to select it.
									Create a column for the EOL identifiers of taxa by <em>Add Column By Fetching URLs... </em>
									</li>
									<li class="rec-item">In the expression field, write:<br/>
									<div class="rec-code">
										&quot;http://opencontext.org/sets/reconciliation/.json?rel=http%3A%2F%2Fpurl.org%2FNET%2Fbiol%2Fns%23term_hasTaxonomy&amp;rq=&quot; + escape(value, "url")
									</div>
									The adove expression will get a list of possible EOL identifiers for biological taxa, ranked from most
									commonly used to the least commonly used.
									</li>
									<li class="rec-item">Completing the step above will populate this new column with JSON data (a
									"machine-readable" data format) from Open Context. You'll need to process these results further
									with the <em>Edit Cells > Transform...</em> command.
									</li>
									<li class="rec-item">In the expression field, write:<br/>
										<div class="rec-code">
										value.parseJson()[&quot;reconResults&quot;][0][&quot;uri&quot;]
										</div>
										The above expression generates a link to an EOL Web page representing
										the mostly likely match to the taxonomic term in your dataset.
									</li>
									<li class="rec-item"><strong>Check the results!</strong> This is a <em>semi-automated</em> approach. You'll need
									to check to make sure the results make sense and reference appropriate EOL pages.
									</li>
							 </ol>
						  <p>One can also take advantage of Open Context's powerful index and add additional filters and query parameters to
						  further constrain the search for relevant identifers. For example, a query to get a Web identifier for a biological taxon associated
						  with the term "sheep" can be limited by a geographic bounding box as follows:</p>
						  <div class="rec-code">
							  http://opencontext.org/sets/reconciliation/.json?rel=http%3A%2F%2Fpurl.org%2FNET%2Fbiol%2Fns%23term_hasTaxonomy&amp;bBox=30,30,50,50&amp;rq=sheep
						  </div>
						  <br/>
						  <p><strong>Please note!</strong> This reconciliation service needs testing and evaluation. We welcome feed-back to improve our
						  efforts (<a href='mailto:skansa@alexandriaarchive.org' title='Email the editor, Sarah Kansa'>contact the Editor</a>).</p>
						  </div>
						  <!-- end div for reconcilation -->
						  
					 </div>
					 <!-- end div for content -->
			 
			 
				</div>
				<!-- end right side div -->
		  </div>
		  <!-- end main row div -->
    
	 </div> <!-- end main div -->
	
    
</div> <!-- end main div -->	 
	 <?php echo $this->render('footer.phtml'); //reader document footer ?>
	
</body>
</html>
