
<?php
$host = OpenContext_OCConfig::get_host_config();
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
      <title>Open Context Sponsors and Collaborators</title>
      <link rel="schema.DC" href="http://purl.org/dc/terms" />
      <meta name="DC.title" content="Open Context Sponsors and Collaborators" />
      <meta name="DC.created" content="January 1, 2010" />
      <meta name="DC.date" content="April 10, 2011" />
      <meta name="DC.creator" content="Open Context Editors" />
      
      <link href="/css/opencontext_style.css" rel="stylesheet" type="text/css" /> 
      <link href="/css/test_landing_page.css" rel="stylesheet" type="text/css" />
      <link href="/css/default_banner.css" rel="stylesheet" type="text/css" />
      <link href="/css/rounded_corners.css" rel="stylesheet" type="text/css" />
      
      <link rel="shortcut icon" href="/images/general/oc_favicon.ico" type="image/x-icon" />
    </head>
    
<body>
    <div id="oc_logo">
	<a href="<?php echo $host; ?>" title="Open Context (Home)"><img alt="Open Context Logo" src="/images/general/oc_logo.jpg" border="0" ></img></a>
    </div>
    <div id="oc_tagline">
	<img alt="Open Context Tagline" src="/images/general/oc_tagline.jpg" ></img>
    </div>
    <div id="oc_beta">
	<img alt="Beta Stamp" src="/images/general/oc_betastamp.jpg" ></img>
    </div>
    
    <div id="oc_top_search">
	<form method="get" action="<?php echo $host;?>/search/" id="search-form">
	<div id="search_box">
	<input type='text' name='q' class='tinyText' value='Search' size='30' onfocus="if(this.value=='Search')this.value='';" onblur="if(this.value=='')this.value='Search';" />
	</div>
	<div id="search_cntrl">
	    <input class="oc_top_sbutton" type="submit" value="" />
	</div>
	</form>
    </div>
   
   
   <!-- 
    Navigation tabs
    -->    
    <?php echo OpenContext_NavMenus::GeneralNavMenu("about"); ?>
    
    <div id="main">
	<div id="pageTop">
            <div id="pageIntro">
                <h2 style="text-align:center;">Open Context Sponsors, Funders, and Collaborators</h2>
                
                <div style="margin:10px;">
                    <p class="bodyText">Open Context is maintained and administered by a dedicated staff with the
                    <a href="http://www.alexandriaarchive.org/">Alexandria Archive Institute</a>, a not-for-profit organization.
                    In addition, the <a href="http://isd.berkeley.edu/">Information and Service Design (ISD) Program</a>
                    at the <a href="http://ischool.berkeley.edu/">UC Berkeley School of Information</a> is responsible for
                    continued software development. Open Context development has been funded by a variety of foundation grants and
                    charitable donations.</p>
                    <p class="bodyText">In keeping with the spirit of this public support and to foster collaboration,
                    all software uses open source components and original source code is released under a GNU-GPL open source
                    license (see the "<a href="../about/technology">technology</a>" section).</p>
                </div>
            </div>
            <div id="about_submenu" class="rounded-corners">
                    <p class="bodyText"><em>More About Open Context:</em></p>
                    <?php echo OpenContext_NavMenus::AboutNavMenu("sponsors", $host); ?>
            </div>
            <div id="pageTopEnd">
                <br/>
            </div>
        </div>
        
	<div style="margin:10px;">
	    <h3>Financial Support for Open Context:</h3>
                    <ul class="bodyText">
                        <li><a href="http://www.hewlett.org/">The William and Flora Hewlett Foundation</a>, Open Educational Resources Program</li>
                        <li><a href="http://www.neh.gov">The National Endowment for the Humanities</a></li>
                        <li><a href="http://www.imls.gov/">The Institute of Museum and Library Services</a></li>
                    </ul>
        
            <br/>
            <h3>Collaborative Organizations:</h3>
                <ul class="bodyText">
                    <li><a href="http://isd.ischool.berkeley.edu/">ISD Program</a>, UC Berkeley, School of Information</li>
                    <li><a href="http://www.africancommons.org/">The Africa Commons Project</a></li>
                    <li><a href="http://www.omeka.org">The Omeka Project</a> (George Mason University)</li>
                    <li><a href="http://ochre.lib.uchicago.edu/">The OCHRE Project</a> (University of Chicago)</li>
                </ul>
        </div>
	
	<div id="bottom">
	</div>
	
    </div>

</body>
</html>
