<?php
$host = OpenContext_OCConfig::get_host_config();
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
      <title>About Open Context: Technologies</title>
      <link rel="schema.DC" href="http://purl.org/dc/terms" />
      <meta name="DC.title" content="About Open Context" />
      <meta name="DC.created" content="January 1, 2010" />
      <meta name="DC.date" content="January 1, 2011" />
      <meta name="DC.creator" content="Open Context Editors" />
      
      <link href="/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" /> 
		  <link href="/css/about-rev2.css" rel="stylesheet" type="text/css" /> 
		
      <link rel="shortcut icon" href="/images/layout/oc-favicon.ico" type="image/x-icon" />
		 <script src="<?php echo $host; ?>/js/jquery/jquery-1.7.2.min.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-transition.js" type="text/javascript"></script>
    <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-carousel.js" type="text/javascript"></script>
    
	 <script type="text/javascript">
        <!--
        
        $('.carousel').carousel();
        
        -->
    </script>

	 
	 
	 
	 
	 
	 
	 
	 </head>
    
<body>

<!-- 
    Logo,
-->    
<?php echo $this->render('header.phtml'); //reader document top ?>
   
<!-- 
    Navigation tabs, search box
-->
<?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>


<div id="main">
    <div id="main_content">
		  <div id="main_row">
				<div id="left_sidebar">
					 <div id="gksm-custom-menu-widget-3" class="widget gksm-custom-menu-widget">
						  <h2 class="widgettitle">About: Technologies</h2>
						  <div class="submenu-widget submenu-widget-projects">
								<?php echo OpenContext_NavMenus::AboutNavMenu("technology", $host); ?>
						  </div>
					 </div>
				</div>
				
				<div id="right_sidebar">
					 <div id="pageTop">
						  <div id="pageIntro">
								<h1 style="text-align:center;">Open Context's Technologies</h1>
								<p>Open Context now host many different projects, with different methodologies, recording
									 systems, and temporal and geographic coverage. This wide applicability lowers costs, since a common set
									 of ArchaeoML-based software and database tools can be used for many projects without any additional
									 software development. While ArchaeoML (see the "<a href="../about/concepts">concepts</a>" page) is very
									 useful for cultural heritage data management and dissemination (and can even see
									 application in areas as diverse as Public Health and environmental biology), there are many
									 scenarios where users will need to work with Open Context data in other applications and systems.
									 Therefore, Open Context must enable efficient data portability and interoperability.</p>
								<p>The main focus of Open Context's technical development centers on interoperability. 
								To be of most benefit to the research community, Open Context works to be a &ldquo;good citizen&rdquo;
								and collaborative partner in the Web of Data. We work improve Open Context's interoperability
								to meet preservation and research goals. 
								</p>		
						  </div>
					 </div>

					 <div>
						  <h3>Behind the Scenes</h3>
						  <p>Open Context is a PHP based application using the open source Zend Framework. It uses a MySQL database
						  to manage data and <a href="http://lucene.apache.org/solr/">Apache Solr</a> to support faceted queries.
						  All source code is released under a GNU-GPL version 3 open
						  source license. <a href="https://github.com/ekansa/open-context-code/">Click here</a> to access the code repository
						  in GitHub.
						  </p>
						  
						  <h3>Web Services</h3>
						  <p>Open Context promotes interoperability by offering a variety of Web-Services (APIs). These services make
						  machine-readable data available so that content from Open Context can efficiently flow into digital repositories,
						  other databases, and other applications. In other words, data published by Open Context is not trapped within Open Context.
						  Instead, Open Context works to make data as portable as possible.
						  </p>
						  <p>Open Context uses two main approaches and technical styles to promote interoperability. Its most fully developed
						  approach centers on <a href="http://en.wikipedia.org/wiki/Representational_State_Transfer">RESTful</a>
						  Web Services. RESTful services are widely deployed and used on the Web, in everything from social media applications,
						  mobile information services, and digital library and scholarly communication services. Secondly,
						  Open Context developers increasingly emphasize "Linked Open Data" services to promote interoperability. Linked Open Data
						  approaches are based on over a decade of Semantic Web research and development.
						  Open Context's implementation of these approaches are summarized below:</p>
						  
						  <h4 id="linked-data">Open Context and RESTful Services</h4>
						  <p>Open Context provides a machine-readable data in a variety of formats using RESTful style services.
						  The services support faceted search requests according to a wide variety of query parameters.
						  These services are
						  fully documented [<a href="../about/services">here</a>] and are very simple to access and use.
						  The RESTful services offer data in the following formats:</p>
						  <ul>
								<li><strong>Atom Syndication Format: </strong> Atom is a widely used and widely supported XML format
								ideally suited for sharing lists of Web resources described by some simple metadata. Open Context offers faceted
								search results as a list of resources expressed in Atom. The Atom feeds provide information about when items in
								a search result were published and last updated, enabling users to subscribe to custom-defined (based on
								query parameters) feeds of Open Context content.
								
								The feeds itemize each resource as an Atom
								<span class="code">&lt;entry&gt;</span>, and each entry has <span class="code">&lt;link&gt;</span> elements pointing to
								various representations (formats) of each given resource. Like many other research collections,
								Open Context provides Atom data supplemented with other extensions, including:
									 <ol>
										  <li><a href="http://www.opensearch.org/Home">Open Search</a>:
										  to provide numeric data about search results
										  </li>
										  <li><a href="http://tools.ietf.org/html/rfc5005">Feed Paging</a>: to allow clients to fully retrieve
										  large sets of search results
										  </li>
										  <li><a href="http://georss.org/">GeoRSS</a>: to provide geospatial metadata for resources listed in the Atom feed
										  </li>
									 </ol>
								</li>
								<li><strong>JSON (Javascript Object Notation): </strong> JSON is a popular, light-weight format for expressing
								machine-readable data. Most Web scripting languages easily parse JSON, making it very easy for developers to use.
								Open Context provides faceted search results in JSON and also in GeoJSON, a popular standard for expressing geospatial
								data.</li>
								<li><strong>KML: </strong> KML is a popular XML format for expressing geospatial data on the Web. Open Context
								provides KML to express both summarized search results and lists of individual records retrieved from searches.</li>
								<li><strong>ArchaeoML XML: </strong> Open Context expresses individual records of data using the ArchaeoML XML
								vocabulary. This is the format used internally in Open Context, and AchaeoML representations are the richest
								and most complete representations of data currently available.</li>
						  </ul>
						 
						  
						  
						  <h4 id="linked-data">Open Context and Linked Open Data</h4>
						  <p>Open Context participates in the "<a href='http://lod-lam.net/' title='Digital Humanities Community Hub for Linked Data'>
						  Linked Open Data</a>" community by publishing data linked to URI-identified concepts published by others.
						  We currently link to the <a href="http://www.eol.org/" title="EOL Homepage">Encyclopedia of Life</a>
						  to reference biological taxa. We also link to places published by the
						  <a href="http://pleiades.stoa.org" title="Pleiades homepage">Pleiades Gazetteer</a>. To learn how to query
						  Open Context over linked data URIs, please review our API documentation <a href="services#query-rel">here</a>.
						  </p>
						  <p>In addition, Open Context publishes data easy to reference with stable URIs to specific records.
						  Each location and object has its own ID and its own web-address. Similarly, each project, project, person,
						  media item, and even each descriptive property has its own unique address. These items are linked to one another
						  through network graph relationships (expressed in ArchaeoML, a machine-readbile XML format). We are also working
						  on expressing these data as RDF-triples using the CIDOC-CRM.</p>
						  <p>By publishing data where every record can be referenced with URIs, everything in Open Context can be addressed
						  and annotated by simple folksonomy tagging or by outside systems using more sophisticated semantics
						  and "Linked Data" methods. For instance, experts familiar with the CIDOC-CRM can describe
						  relationships among Open Context content using the semantically richer framework of the CIDOC-CRM
						  even before we provide our own expressions of CIDOC-mapped data.
						  </p>
					 </div>
			 
			 
				</div>
		
    </div> <!-- end main div -->
	
    
</div> <!-- end main div -->	 
	 <?php echo $this->render('footer.phtml'); //reader document footer ?>
	
</body>
</html>
