<?php
// used to help create hyperlinks; set to current hostname.
$host = OpenContext_OCConfig::get_host_config();

define ('HOST', $host);


$requestURI = $this->requestURI;
$request_array = explode('?', $requestURI, 2);
//array explode  ( string $delimiter  , string $string  [, int $limit  ] )

if (substr_compare($request_array[0], '/' , -1)) {  // if the uri doesn't end in a slash (minus query parameters), 
    $request_array[0] = $request_array[0] . '/';  // add one
}


if (isset($request_array[1])) { // if there are query parameters,
    $request_array[1] = "?" . $request_array[1];  // prepend a '?' to the set of parameters since we exploded on the '?' to get this string. 
    //echo $request_array[1]; // for testing
} else {
    $request_array[1] = null;
}


$requestParams = $this->requestParams;
if(!isset($requestParams["q"])){
    
    $checkParam = $requestParams;
    unset($checkParam["page"]);
    unset($checkParam["recs"]);
    unset($checkParam["sort"]);
    
    if(count($checkParam)>3){
        $searchMessage = "Search this set of data";
    }
    else{
        $searchMessage = "Search all analytic data";
    }
    
    $full_link = $host.$requestURI;
    $full_link  = str_replace("&", "&amp;", $full_link );
    $full_link  = str_replace("&amp;amp;", "&amp;", $full_link );

    $fulltext = '';
    $fulltext .= '<input id="act_uri" type="hidden" value="'.$full_link.'" />';
    $fulltext .= '<span style="text-align:left; margin-left:2%; font-size:.75em;" >';
    $fulltext .= 'Or, type a search term in the box';
    $fulltext .= '</span><br/>';
    $fulltext .= '<div id="b_search_tab">
                    <div id="b_search_row" class="b_search">
                        <div id="b_search_cell_in" >
                                <input name="q" class="bb" type="text" id="q_string" placeholder="Search here..." />
                        </div>
                        <div id="b_search_cell_button">
                                <button class="bb" type="submit" onclick="textSearch();">Search</button>
                        </div>
                    </div>
                </div>
    ';
    
}
else{
    $fulltext = "";
}



$numFound = 0;
$fulltext = "";
$facet_output = "<br/>(No results to this query, please try other search options)";
$filter_output = OpenContext_FacetOutput::make_filters_html($requestParams, $host);

$googleURI = "";
$facetAtomURI = "";
$openSearchURI = "";

$jsonString = file_get_contents($host."/search/.json");
$jsonObj =  Zend_Json::decode($jsonString);
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
        <title><?php echo 'Open Context Search: ('.$numFound.' Web-pages Showing)'; ?></title>
        <link rel="shortcut icon" href="/images/layout/oc-favicon.ico" type="image/x-icon" />
        <link href="<?php echo $host; ?>/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/bootstrap.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $host; ?>/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" /> 
        <link href="<?php echo $host; ?>/css/opencontext-browse-rev2.css" rel="stylesheet" type="text/css" />
        <link rel="alternate" type="application/atom+xml" title="Atom facet feed" href="<?php echo $this->facetURI_Atom; ?>" />
        <link rel="alternate" type="application/atom+xml" title="Atom feed of results" href="<?php echo $this->currentAtom; ?>" />
        
        <link rel="first" type="application/atom+xml" title="Atom feed of results" href="<?php echo $this->firstPage_XHTML; ?>" />
        <?php
            if($this->prevPage_XHTML != false){
                echo '<link rel="prev" type="application/atom+xml" title="Atom feed of results" href="'.$this->prevPage_XHTML.'" />'.chr(13);
            }
            if($this->nextPage_XHTML != false){
                echo '<link rel="next" type="application/atom+xml" title="Atom feed of results" href="'.$this->nextPage_XHTML.'" />'.chr(13);
            }
        ?>
        
        <link rel="last" type="application/atom+xml" title="Atom feed of results" href="<?php echo $this->lastPage_XHTML; ?>" />
        <link rel="search" type="application/opensearchdescription+xml" href="<?php echo $openSearchURI; ?>" title="Open Context Web Search" />
       
        
        
    </head>
    <body>
        
    <!-- 
    Logo,
-->    
<?php echo $this->render('header.phtml'); //reader document top ?>
   
<!-- 
    Navigation tabs, search box
-->
<?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>

    
    
    
        
<!--
BEGIN Container for main page content
--> 
    <div id="main">
        
        <div id="generalSearch">
            <div id="searchHero" class="hero-unit">
                <h1>General Search of Open Context</h1>
                <form class="form-search" method="get" action="../search/">
                    <input type="text" class="input-medium search-query" name="q">
                    <button type="submit" class="btn">Search</button>
                </form>
            </div>
            
            <!--Begin code for showing available facets-->
            <div id="g-search-facets">
                <div style="padding: 3%;">
                    <h4>Types of resources:</h4>
                    <p>
                    <?php
                    $i=0;
                    $dtypes = new DocumentTypes;
                    foreach($jsonObj["facets"]["resource type"] as $actTypes){
                        
                        $dtypes->solrToOutside($actTypes["name"]);
                        $comma = ", ";
                        if($i==0){
                                $comma = "";
                        }
                        echo $comma."<a title=\"View items from this context\" href=\"".$actTypes["href"]."\">".$dtypes->outsideTerm."</a> (".$actTypes["count"].")";
                        $i++;
                    }
                    ?>
                    </p>
                    <br/>
                    <h4>Items from these contexts:</h4>
                    <p>
                    <?php
                    $i=0;
                    foreach($jsonObj["facets"]["context"] as $actContext){
                            
                        $comma = ", ";
                        if($i==0){
                                $comma = "";
                        }
                        echo $comma."<a title=\"View items from this context\" href=\"".$actContext["href"]."\">".$actContext["name"]."</a> (".$actContext["count"].")";
                        $i++;
                    }
                    ?>
                    </p>
                    <br/>
                    <h4>Items belonging to these general categories:</h4>
                    <div style="margin-left:5px">
                        <?php
                        $jj = count($jsonObj["facets"]["category"]);
                        $i=0;
                        foreach($jsonObj["facets"]["category"] as $actCat){
                            $comma = ", ";
                            if($i==($jj-1)){
                                $comma = "";
                            }
                            $comma = "";
                            
                            $actImage = OpenContext_ProjectAtomJson::class_icon_lookup($actCat["name"]);
                            echo "<div style='float:left; width:40%; padding-top:4px;'><div style='float:left;'>";
                            echo "<a title='View items of this type' href='".$actCat["href"]."'>";
                            echo "<img src='".$actImage."' alt='".$actCat["name"]."'/></a>";
                            echo "</div>";
                            echo "<div style='padding:3px; float:left; margin-right:3px;'>";
                            echo "<span class='bodyText'><a title='View items of this type' href='".$actCat["href"]."'>".$actCat["name"]."</a> (".$actCat["count"].")";
                            echo $comma."</span>";
                            echo "</div>";
                            echo "</div>";
                            $i++;
                        }
                        ?>
                    </div>
                    <div style="clear:both; width:90%"></div>
                    <br/>
                    <h4>Items from these projects and collections:</h4>
                    <p>
                    <?php
                    $i=0;
                    foreach($jsonObj["facets"]["project"] as $actContext){
                            
                        $comma = ", ";
                        if($i==0){
                                $comma = "";
                        }
                        echo $comma."<a title=\"View items from this context\" href=\"".$actContext["href"]."\">".$actContext["name"]."</a> (".$actContext["count"].")";
                        $i++;
                    }
                    ?>
                    </p>
                </div>
            </div>
            <!--
            END of div container general facets
            -->
        </div>
    </div>

    <div id="bottomBuffer">

    </div>
    <?php echo $this->render('footer.phtml'); //reader document footer ?>
    </body>
</html>    