<?php

// used to help create hyperlinks; set to current hostname.
//$host = "http://ishmael.ischool.berkeley.edu";
//$host = "http://opencontext";
$host = OpenContext_OCConfig::get_host_config();

define ('HOST', $host);


$unfold_vals = $this->unfold_vals;
$requestURI = $this->requestURI;
$requestParams = $this->requestParams;
$solrParams = $this->solrParams;
$extendfacets = $this->extendedFacets;
$unfold_vals = $this->unfold_vals;
$queryString = $this->queryString;
//echo $queryString." <br/><br/>";
//echo var_dump($extendfacets);
//echo var_dump($unfold_vals);
//echo var_dump($solrParams);
//$solrqTerm = $solrParams["fq"];
//echo $solrqTerm ." <br/><br/>";


$request_array = explode('?', $requestURI, 2);
//array explode  ( string $delimiter  , string $string  [, int $limit  ] )

if (substr_compare($request_array[0], '/' , -1)) {  // if the uri doesn't end in a slash (minus query parameters), 
    $request_array[0] = $request_array[0] . '/';  // add one
}


if (isset($request_array[1])) { // if there are query parameters,
    $request_array[1] = "?" . $request_array[1];  // prepend a '?' to the set of parameters since we exploded on the '?' to get this string. 
    //echo $request_array[1]; // for testing
} else {
    $request_array[1] = null;
}


$requestURI = str_replace("/sets","/slides/",$requestURI);
$requestURI = str_replace("/slides//","/slides/",$requestURI);


/* this complex check is needed because the request parameter 'module' with the value 'default' is present if the user selects a
 * non-context parameter.  The reason for this behavior is not clear.  
 */
if ((count($requestParams) < 3)  ||  ((count($requestParams) < 4) && (in_array('module', array_keys($requestParams))))) {

    $filter_message = "(View is not filtered)";
    
    $googleURI = str_replace("/sets","/slides/facets/.kml",$requestURI);
    $googleURI = str_replace("/slides/","/slides/facets/.kml",$requestURI);
    $facetAtomURI = str_replace("/sets","/slides/facets/.atom",$requestURI);
    $facetAtomURI = str_replace("/sets","/slides/facets/.atom",$requestURI);
    $resultAtomURI = $requestURI.".atom";
    $searchMessage = "Search Open Context";
}//end case with no filters
else{
    
    $filter_message = "";
    $searchMessage = "Search this Set";
    
    $requestURI = str_replace("[", "%5B",$requestURI);
    $requestURI = str_replace("]", "%5D",$requestURI);
    
    $googleURI = str_replace("?",".kml?",$requestURI);
    $googleURI = str_replace("/slides/","/slides/facets/",$googleURI);
    $facetAtomURI = str_replace("?",".atom?",$requestURI);
    $resultAtomURI = $facetAtomURI;
    $facetAtomURI = str_replace("/slides/","/slides/facets/",$facetAtomURI);
    
    if(substr_count($googleURI,".kml?")<1){
        $googleURI .= ".kml";
        $facetAtomURI .= ".atom";
        $resultAtomURI = $requestURI.".atom";
    }
    
    if(substr_count($googleURI,"facets/.kml")<1){
        $googleURI = str_replace("/.kml",".kml",$googleURI);
        $facetAtomURI = str_replace("/.atom",".atom",$facetAtomURI);
        $resultAtomURI = str_replace("/.atom",".atom",$resultAtomURI);
    }
}//end case with filter parameters

$resultAtomURI = $host.$resultAtomURI;
$facetAtomURI = $host.$facetAtomURI;

$resultAtomURI = str_replace("&", "&amp;", $resultAtomURI);
$resultAtomURI = str_replace("&amp;amp;", "&amp;", $resultAtomURI);
$facetAtomURI = str_replace("&", "&amp;", $facetAtomURI);
$facetAtomURI = str_replace("&amp;amp;", "&amp;", $facetAtomURI);
$googleURI = str_replace("&", "&amp;", $googleURI);
$googleURI = str_replace("&amp;amp;", "&amp;", $googleURI);

$openSearchURI = str_replace("slides/facets", "slides/search", $facetAtomURI);
$openSearchURI = str_replace(".atom", ".xml", $openSearchURI);
$openSearchURI = str_replace("search//", "search/", $openSearchURI);
$openSearchURI = str_replace(".xml/", ".xml", $openSearchURI);

$openSearchURI = $host."/slides/search/.xml";
                             
//echo $resultAtomURI."<br/>";
//$googleURI = str_replace("[", "%5B",$googleURI);
//$googleURI = str_replace("]", "%5D",$googleURI);
//$facetAtomURI = str_replace("[", "%5B",$facetAtomURI);
//$facetAtomURI = str_replace("]", "%5D",$facetAtomURI);
//$resultAtomURI = str_replace("[", "%5B",$resultAtomURI);
//$resultAtomURI = str_replace("]", "%5D",$resultAtomURI);

$numFound = $this->numFound;

$filter_output = $filter_message;
$filter_output .= OpenContext_FacetOutput::facet_removal_context_links($requestParams, $request_array, $host);
$filter_output .= OpenContext_FacetOutput::facet_removal_links($requestParams, $request_array, $host);


// get the facet counts 
$facet_fields = $this->facet_fields;
$facet_queries = $this->facet_queries;
$extendedFacets = $this->extendedFacets; //show more available facets 

$facet_output = OpenContext_FacetOutput::facets_available($extendedFacets, $facet_fields, $facet_queries, $requestParams, $request_array, $host);

$result_output = OpenContext_ResultAtom::image_atom_to_html($resultAtomURI);
 
//$result_output = "";


//add a full text form?
if(substr_count($requestURI,"q=")<1){
    $full_link = $host.$requestURI;
    $full_link  = str_replace("&", "&amp;", $full_link );
    $full_link  = str_replace("&amp;amp;", "&amp;", $full_link );

    $fulltext = '<p class="bodyText">Or, type a search term in the box below (works like Google):</p>'.chr(13);
    //$fulltext .= '<form id="searchbox" name="form4" method="get" action="'.$requestURI.'">'.chr(13);
    $fulltext .= '<input id="act_uri" type="hidden" value="'.$full_link.'" />';
    $fulltext .='<input name="q" type="text" id="q_string" size="30" maxlength="100" class="bodyText"/>'.chr(13);
    $fulltext .='<input type="submit" id="submit" value="'.$searchMessage.'" class="bodyText" onclick="textSearch();"/>'.chr(13);
    //$fulltext .='</form>';
}
else{
    $fulltext = "";
}



?>


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
        <title><?php echo 'Open Context Browse: ('.$numFound.' Items Showing)'; ?></title> 
        <link href="/css/opencontext_style.css" rel="stylesheet" type="text/css" /> 
        <link href="/css/opencontext_browse.css" rel="stylesheet" type="text/css" />
        <link href="/css/atomresults.css" rel="stylesheet" type="text/css" />
        <link href="/css/default_banner.css" rel="stylesheet" type="text/css" />
        <link rel="alternate" type="application/atom+xml" title="Atom facet feed" href="<?php echo $facetAtomURI; ?>" />
        <link rel="search" type="application/opensearchdescription+xml" href="<?php echo $openSearchURI; ?>" title="Open Context Web Search" />
        <script type="text/javascript">
        /***********************************************
        * Simple Tree Menu-  Dynamic Drive DHTML code library (www.dynamicdrive.com)
        * This notice MUST stay intact for legal use
        * Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code
        ***********************************************/
        
        /***********************************************
        *testing new stylesheet
        ***********************************************/
        </script>
        <!--
        <script type="text/javascript" src="/js/simpletreemenu.js" ></script>
        <link rel="stylesheet" type="text/css" href="/css/simpletree.css" />
        -->
        <script type="text/javascript">
        <!--
            function textSearch(){
               
               
               var dom_act_uri = document.getElementById('act_uri');
               var dom_qstring = document.getElementById('q_string');
               
               var acr_uri  = dom_act_uri.value;
               var q_string = dom_qstring.value;
               var amp_char = String.fromCharCode(38);
               
               q_string = escape(q_string);
               
               if (acr_uri.indexOf("?")>0){
                    acr_uri = acr_uri + amp_char + "q=" + q_string; 
               }
               else{
                    acr_uri = acr_uri + "?q=" + q_string; 
               }
               
               //alert(acr_uri);
               
               window.location = acr_uri;
            }
        
     window.onload = function(){
        ConvertRowsToLinks("result_tab");
      }
      
      function ConvertRowsToLinks(xTableId){

        var rows = document.getElementById(xTableId).getElementsByTagName("tr");
   
        for(i=0; i < rows.length; i++){
          var link = rows[i].getElementsByTagName("a")
          if(link.length == 1){
            rows[i].onclick = new Function("document.location.href='" + link[0].href + "'");
            rows[i].onmouseover = new Function("this.style.cursor = 'pointer'");
            rows[i].onmouseout = new Function("this.style.cursor = 'default'");
          }
        }

      }
      -->
        </script>
    </head>
    <body>
        
    <div id="oc_logo">
	<a href="<?php echo $host;?>/slides/" title="Home (Browse)"><img alt="Open Context Logo" src="/images/general/oc_logo.jpg" border="0" ></img></a>
    </div>
    <div id="oc_tagline">
	<img alt="Open Context Tagline" src="/images/general/oc_tagline.jpg" ></img>
    </div>
    <div id="oc_beta">
	<img alt="Beta Stamp" src="/images/general/oc_betastamp.jpg" ></img>
    </div>
    
    <div id="oc_main_nav">
        <div class="sides"></div>
        <div class="n_act_nav"><a href="<?php echo $host;?>/about/" title="Learn more about Open Context">About</a></div>
        <div class="sides"></div>
        <div class="n_act_nav"><a href="<?php echo $host;?>/projects/" title="Summary of Projects in Open Context">Projects</a></div>
        <div class="sides"></div>
        <div class="n_act_nav"><a href="<?php echo $host;?>/sets/" title="Explore data">Browse</a></div>
        <div class="sides"></div>
        <div class="act_nav"><a href="<?php echo $host;?>/slides/" title="Explore Images">Lightbox</a></div>
        <div class="sides"></div>
        <div class="n_act_nav"><span title="Coming soon">Tables</span></div>
        <div class="sides"></div>
        <div class="n_act_nav"><span title="Browse to get details of items">Details</span></div>
        <div class="sides"></div>
        <div class="n_act_nav"><span title="Coming soon">My Account</span></div>
    </div>
    
    
        
<!--
BEGIN Container for main page content
--> 
    <div id="main_page"> 
        <!--Begin code for showing available facets-->
        <div id="main_content">
            <div id="left_cont">
                <div id="filter_options" class="bodyText">
                    <p class="bodyText"><strong>Click on one of the links below to further limit your view of items in Open Context.</strong></p>
                        <?php echo  $fulltext; ?>
                    <br/>
                        <?php echo $facet_output; ?>
                            
                    <br/>
                    <p>View in <a href="<?php echo $googleURI; ?>">GoogleEarth</a></p>
                    <p>Get in <a href="<?php echo $facetAtomURI; ?>">Atom</a></p>
                </div>
            </div>
            <div id="right_cont">   
                <div id="selected_filters">
                    <p class="subHeader">Open Context currently has <strong><?php echo $numFound; ?></strong> items, filtered by the following criteria:</p>
                    <p class="bodyText"><?php echo $filter_output; ?></p>
                    <!--
                    <form action="<?php echo $host."/tables/add"; ?>" method="post">
                        <input type="hidden" value="<?php echo $requestURI; ?>" name="set" />
                        <input type="hidden" value="<?php echo htmlentities($filter_output); ?>" name="filter" />
                        <input type="submit" value="make table" />
                    </form>
                    -->
                </div>
                        
                <br />
                <br />
                        
                <?php echo $result_output; ?>
            </div>
                    
   
        <!--
        END of div container for placing main page content
        -->
        <div id="bottom_cont"> 
          <br /> 
          <br /> 
        </div> 
        <!--
        END Code for showing the database-like content
        -->
   
     </div>
    <br />
    
        <div id="footer"> 
            <div id="w3c_val_logo"> 
              <a href="http://validator.w3.org/check?uri=referer"> 
                <img src="http://www.w3.org/Icons/valid-xhtml10-blue" alt="Valid XHTML 1.0 Transitional" height="31" width="88" /> 
              </a> 
            </div>     
        </div>
   
     </div>
    </body>
</html>    