<?php
$host = OpenContext_OCConfig::get_host_config();
$GoogleAPIkey = OpenContext_OCConfig::get_google_api();
$OWL = $this->OWL;
$owlArray = $OWL->owlArray;

?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head> 
		  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
		  <title><?php echo $OWL->vocabLabel; ?></title>
		  <link rel="schema.DC" href="http://purl.org/dc/terms" />
		  <meta name="DC.title" content="<?php echo $OWL->vocabLabel."::".$OWL->conceptLabel; ?>" />
		  <meta name="DC.created" content="<?php echo date("Y-m-d", strtotime($OWL->created)); ?>" />
		  <meta name="DC.date" content="<?php echo date("Y-m-d", strtotime($OWL->updated)); ?>" />
		  <meta name="DC.creator" content="<?php echo $OWL->vocabAttribution; ?>" />
		  
		  <link href="/css/oc-layout-rev2.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" /> 
		  <link href="/css/project-rev2.css" rel="stylesheet" type="text/css" />
		  <link href="/css/bibliographic.css" rel="stylesheet" type="text/css" />
		  <link href="/css/general-item-rev2.css" rel="stylesheet" type="text/css" />
		  <link href="/css/property-rev2.css" rel="stylesheet" type="text/css" /> 
		  
		  <link rel="shortcut icon" href="/images/layout/oc-favicon.ico" type="image/x-icon" />
		  <script src="<?php echo $host; ?>/js/jquery/jquery-1.7.2.min.js" type="text/javascript"></script>
		  <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-transition.js" type="text/javascript"></script>
		  <script src="<?php echo $host; ?>/js/bootstrap/bootstrap-carousel.js" type="text/javascript"></script>
		  <script src="https://www.google.com/jsapi?key=<?php echo $GoogleAPIkey; ?>" type="text/javascript"></script>
    
		  <link rel="alternate" href="<?php echo $OWL->vocabCommits; ?>" type="application/atom+xml" />
		  <link rel="alternate" href="<?php echo $OWL->vocabURI.".owl"; ?>" type="application/rdf+xml" />
		  <link rel="alternate" href="<?php echo $OWL->vocabURI.".json"; ?>" type="application/json" />
		  
		  <?php echo $this->render('vocab-update-widget-js.phtml'); //render javascript for displaying news feeds ?>
		  
	 </head>
    
<body>

<!-- 
    Logo,
-->    
<?php echo $this->render('header.phtml'); //reader document top ?>
   
<!-- 
    Navigation tabs, search box
-->
<?php echo $this->render('main-navigation.phtml'); //render main navigation area ?>


<div id="main">
    
	 <!--
		BEGIN Container for gDIV of general item information
		-->
	 <div id="item_top">
		  <div id="item_top_tab">
				<div id="item_top_row">
					 <div id="item_top_icon_cell">
						  <img src="../../images/layout/linked-data-prop.png" alt="Property icon"/>
					 </div>
					 <div id="prop-item_top_name_cell">
						<h1>Vocabulary: <?php echo $OWL->vocabLabel; ?></h1>
						
					 </div>
				  <div id="prop-item_top_des_cell">
					 
				  </div>
				</div>
		  </div>  
	 </div>
	 
	 <!--
		Code for showing the main description content
		-->
	 <div id="main_description">
		  <div id="main_description_tab">
				<div id="main_description_row">
					 <div id="left_des">
						  <div id="prop-all-des">
								<div id="prop-intro">
									 <table class="table table-condensed" id="prop-intro-tab">
										  <tbody>
												<tr>
												  <th>Label</th>
												  <td><?php echo $OWL->vocabLabel; ?></td>
												</tr>
												<?php
												
												$comments = $OWL->VocabGetComment();
												$commentCount = count($comments);
												if($commentCount>0){
													 $i = 1;
													 foreach($comments as $comment){
														  
														  if($commentCount > 1){
																$showI = " ($i)";
														  }
														  else{
																$showI = "";
														  }
														  
														  ?>
														  <tr>
																<th>Note<?php echo $showI; ?></th>
																<td><?php echo $comment; ?></td>
														  </tr>
														  
														  <?php 
														 $i++; 
													 }
												}
												?>
												<tr>
												  <th>URI</th>
												  <td><?php echo $OWL->vocabURI; ?></td>
												</tr>
										  </tbody>
									 </table>
								</div>
								
								
						  
								<div>
									 <?php
									 
									 $conceptPaths = array("do-all");
									 if(is_array($conceptPaths)){
										  
										  ?>
										  <div id="single-prop-stats">
												<h5>Concept Hierachy</h5>
												<p>This vocaubulary ontology describes a hierarchy of concepts as illustrated below:</p>
												<?php
												echo $OWL->outputClassParentsHTML($conceptPaths);
												?>
												
										  </div>
										  <?php
									 }//end case with hierarchy
									 
									 ?>
									 
								</div>
								
								
								<?php
								if(isset($owlArray["properties"])){
									 $propCount = count($owlArray["properties"]);
									 if($propCount > 0){
										  ?>
									 
									 <div id="prop-props">
										  <h5>Properties in this Vocabulary (<?php echo $propCount; ?>)</h5>
										  <p>Properties describe entities and their relationships in a vocabulary or ontology. The following properties are used in the <strong><?php echo $OWL->vocabLabel; ?></strong> vocabulary:</p>
										  <br/>
										  <table class="table table-condensed">
												<thead>
													 <tr>
														  <th>Property Label</th>
														  <th>Property URI</th>
													 </tr>
												</thead>
												<tbody>
												<?php
												foreach($owlArray["properties"] as $propIRI => $propArray){
													 $propURI = $OWL->IRItoURL($propIRI);
													 $propLabel = $OWL->IRIgetLabel($propIRI, $owlArray["properties"]);
													 ?>
													 <tr>
														  <td>
																<?php echo $propLabel; ?>
														  </td>
														  <td>
																<a href="<?php echo $propURI; ?>" title="Link to property definition"><?php echo $propURI; ?></a>
														  </td>
													 </tr>
												<?php	 
												}//end loop
												?>
												</tbody>
										  </table>
									 </div>
										  <?php
									 }
								}//end case with properties
									 ?>
								
						  
								<div style="padding-bottom: 10%;"></div>
						  
						  </div>
						  
					 </div>
					 <!-- end div for left -->
					 
					 <div id="right_des">
						  <div id="editorial">
								<h5>Vocabulary Review Status</h5>
								<div id="project-edit-status">
									<span id="project-edit-stars">
										  <a href="../about/publishing#editorial-status"><?php echo $OWL->reviewStarHTML(); ?></a>
									</span>
									<?php echo $OWL->reviewLabelHTML(); ?>
								</div>
								<br/>
								<br/>
								<h5>Suggested Citation</h5>
								<div id="citation"><?php echo $OWL->vocabAttribution; ?>. "<?php echo $OWL->vocabLabel; ?>" (Updated  <?php echo date("Y-m-d", strtotime($OWL->updated)); ?>). Open Context.  &lt;<?php echo $OWL->vocabURI; ?>&gt; 
								</div>
						  </div>
						  
						  <div id="all_media">
								<h5>Linked Media</h5>
								<p><a href="<?php echo $OWL->vocabReposity; ?>" title="Version control for this vocabulary">Version-control (Github, OWL File)</a></p>
						  </div>
						  
						  <?php echo $this->render('vocab-update-widget-dom.phtml'); //render HTML dom for the vocabulary feed ?>
						  
						   <div id="item-license">
								<?php $licensing = $OWL->getLicenseData(); ?>
								<h5>Copyright Licenseing</h5>
								<div class="list_tab">
									 <div class="list_tab_row">
										  <div class="license-icon">
												<a href="<?php echo $licensing["license_url"]; ?>">
													 <img src="<?php echo $licensing["lic_pict_url"]; ?>" alt="<?php echo $licensing["license_name"]; ?>" />
												</a>
										  </div>
										  <div class="license_text">
												To the extent to which copyright applies, this content is licensed with:
												<a rel="license" href="<?php echo $licensing["license_url"]; ?>">
													 <?php echo $licensing["license_name"]; ?>
												</a> Attribution Required: Citation, and hyperlinks for online uses.
										  </div>
									 </div>
								</div>
						  </div>
						  
						  <div style="padding-bottom: 15%;"></div>
					 </div>
					 <!-- end div for right -->
				</div>
				<!-- end div for main row -->
		  </div>
		  <!-- end div for main tab -->
	 </div>
	 <!-- end div for main description -->
	 
	 
	 
	 
	 
</div> <!-- end main div -->	 
	 <?php echo $this->render('footer.phtml'); //reader document footer ?>
	
</body>
</html>
